### ISSUE TITLE
Spike - Add HTTP/2 to production server

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#1051]
# Description
Since we're using HTTPS for our site, we could also enable HTTP/2 for some easy performance gains. Not sure what the process is for our nginx stack, this ticket would provide some insight.

# Resources
- [HTTP/2 Overview](https://developers.google.com/web/fundamentals/performance/http2/)
- [Random article for adding it to nginx on Ubuntu](https://dev.to/grigorkh/how-to-set-up-nginx-with-http2-support-2mgb)

**Comment by gggrant** [comment]
Adding http/2 in our Redhat/CentOS server environment requires switching to the mainline nginx package.

Azure team says there would be no security issues with making the switch.

This involves installing and configuring the `nginx` package (currently using `nginx14-nginx`), similar to when we switched Postgres versions.

**Comment by gggrant** [comment]
Will investigate configuring http2 when setting up DevOps pipeline with @vid
