### ISSUE TITLE
Application - Long Form Question Word Counter

### ISSUE THREAD

**Issue by JoshBeveridge** [GCTC-NTGC/TalentCloud#1070]
# Description
Lauren would like to have @yonikid15's word counter added to the long form questions on the job application so that applicants have an idea of how long their answers should be. For now, she'd like it set to 250 words for each question.

I'm not sure what the status is on the Word Counter component right now - but it would be great to get this implemented when it's finished.

Tagging @laurenoncoffee just in case she wants to add context.

**Comment by gobyrne** [comment]
I'm gonna put this in the Icebox as I think it's something we should build into Jerbo's redesign of the application process (timeline). Happy to re-prioritise at your suggestion @joshdrink @laurenoncoffee
