### ISSUE TITLE
Bug - Job Builder - Welcome page saving incorrect departments

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#1094]
# Description
The departments shown, and the id saved, don't match with the server. Pull departments from the server to populate the department select.

**Comment by gggrant** [comment]
New department added via `/admin` available to select in JPB.

![Screen Shot 2019-11-12 at 3.56.48 PM.png](https://images.zenhubusercontent.com/5d9ce8bd5fc4fd0001589e3d/f9005e75-7842-43d0-aae3-b1e951078080)
