### ISSUE TITLE
Bug - Job Builder - Details cannot handle an unknown Classification code

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#1116]
# Description
Our database seed generates a random two letter code for the Job Poster classification. If the two letter combination is not one of the available options from the dropdown, the first option is visible as selected and the form throws a `Required` validation error upon submission.

Should either update our seeder with the list of known values to choose from or better handle an 'unknown' choice in this field.

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Go to `/manager/jobs/{id}/builder/details/`, with the `{id}` being a Job Poster that has a random Classification code (`NB` for example)
2. See that the Classification dropdown has `Administrative Services` selected
3. Click `Next` to submit the form
4. View the validation error that occurs

**Comment by tristan-orourke** [comment]
JobPosterFactory now gets classification code from the Classification table.
