### ISSUE TITLE
Feature - Applicant/Manager(?) - Account deletion

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#1144]
# Description

Until we add a self-service account deletion feature, admins should be allowed to soft-delete users.

**Comment by tristan-orourke** [comment]
For applicants, we need to keep anything that's part of their submitted applications (which hopefully, already has copies saved to the application model) and genuinely delete everything we can.

For managers, the key thing is removing a manager's ability to view their jobs/applicants.

**Comment by tristan-orourke** [comment]
For now, we'll do SOFT delete, APPLICANT only.

**Comment by tristan-orourke** [comment]
Button available from the settings page.
