### ISSUE TITLE
Task - Frontend - Add JSON validation for api responses

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#1166]
# Description
The frontend expects data to be returned from the server API in specific formats. Currently, as long the server returns a non-error response, the frontend assumes its in the expected shape. This can (will) lead to errors in the future. We should implement JSON validation schemas on the frontend to catch these kind of errors.

**Comment by gggrant** [comment]
Covered by #2273? @tristan-orourke

**Comment by tristan-orourke** [comment]
> Covered by #2273?

No, not at all. This hasn't been a problem yet, though!
