### ISSUE TITLE
Bug - Clearing fields within your account information autofills additional information.

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#1167]
# Description
I've cleared out my Twitter handle within my profile and saved it. Upon save, the Old Password and the Twitter autofill. The autofill information is incorrect and there's no reason for it to autofill my old password. In fact, if it somehow autofills my old password then hypothetically somebody can change my password and lock myself out.

# Steps to Reproduce
Steps to reproduce the behaviour. Example:
1. Go to My Profile and clear Twitter, LinkedIn and Tagline.
2. Click on Save Changes and click on Save Changes again.
3. See error

Unzip and open the video to see the entire interaction.

# Video
[User Information.zip](https://github.com/GCTC-NTGC/TalentCloud/files/3443722/User.Information.zip)

- [ ] Regression test written.

**Comment by tristan-orourke** [comment]
Add 'autocomplete=off' to html fields
