### ISSUE TITLE
Creating a Job poster with no title breaks other interactions.

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#1297]
# Description
If a Job Poster is created with no title, it breaks the other interactions within that listing within the Manager's view.

# Steps to Reproduce
Steps to reproduce the behaviour. Example:
1. Login an a Manager
2. Go to https://talent.canada.ca/en/manager/jobs
3. Click on [Preview](https://talent.canada.ca/en/manager/jobs/45) or [Edit](https://talent.canada.ca/en/manager/jobs/45/edit) or [Edit Screening Plans](https://talent.canada.ca/en/manager/jobs/45/assessment-plan)

# Images
![image](https://user-images.githubusercontent.com/5738959/63289345-df5af180-c28c-11e9-8b15-dcfb59baed6f.png)

- [ ] Regression test written.

**Comment by joshdrink** [comment]
We can probably set a default title to "Untitled Job Poster" to help alleviate this.

**Comment by gobyrne** [comment]
Is this still a thing with the job poster builder?
