### ISSUE TITLE
[Design] - Manager Job Management

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/TalentCloud#1311]
# Status
- [ ] Being Researched
- [ ] Prototyping and Testing
- [ ] Data Story
- [ ] Ready For Dev

# Design Goal
**Please explain the primary goals of this design work.**

Page for each individual Job Process. With an overview of where the process is at. What are the next steps, and links to view each individual section within the job process.

# Research
**Please list/link to all research performed for or referenced in this design work. This can include research you've done in the past. Include research relevant to insights from team members as well. Don't be afraid to ask for references or documents! This section should also incorporate data collected from user testing.**

- Research Link 01
- etc.

## Assumptions
**Please list all assumptions made during your design work. This should include behavioural assumptions made by the team that have no direct research references.**

- Assumption 01
- etc.

# Important Notes / Copy
**This is a space to include important notes for other team members, including things like key copy, questions that need to be asked at a later date, etc.**

# Wireframes / Images

![Manager Demo Jobs – 6](https://user-images.githubusercontent.com/16977254/63442579-5b764600-c401-11e9-8304-41f390c28a6d.png)

# Final Data Story
**Use this section to summarize where we started, and how and why we got to the approved design. This section must be complete before the issue can be handed off to development.**

**Comment by joshdrink** [comment]
Closing as this has been merged with issue #1763
