### ISSUE TITLE
Bug - Clicking the 'x' in the Error Toast causes Job Builder to crash.

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#1329]
# Description
If something goes wrong while saving the job, the Error Toast pops up in the corner of the page. It will disappear on its own within a couple seconds. However, if you click the 'x' to close it early, the page crashes.

# Steps to Reproduce
If on (or after merging) the feature/demo/permissions branch:
1. Log in to the manager portal.
2. Manually enter the url `https://talent.test/en/manager/jobs/<id>/builder/details`, where id is for a job created by a 'different' manager.
3. Fill the page, and click save.
4. Click the x to close the toast error that appears.

# Images
![error caused from closing toast early](https://user-images.githubusercontent.com/4313717/63616682-1a736280-c5b6-11e9-85e6-d82e5acdceac.png)

- [ ] Regression test written.

**Comment by Khristophor** [comment]
Not able to reproduce locally. Clicking the `x` works as expected, no console errors, and I can continue to use the JPB UI.
