### ISSUE TITLE
Bug - The server does not check that JobPoster is complete before allowing submitForReview

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#1331]
# Description
The backend server only allows correctly authenticated users to submit a Job Poster for review, but it doesn't validate that the job is complete.

**Comment by gobyrne** [comment]
This might actually be preferred for now. It helps us handle the case where the manager wants someone to look at their work but doesn't have all the answers yet.

**Comment by tristan-orourke** [comment]
Now intended behaviour.
