### ISSUE TITLE
Job Builder: Step 1 - Update Copy/Labels

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1345]
# Description
We've taken another stab at the structure/labels here and the changes can be found below. Ideally we'd still have just the first name used here, but until that's an option, go ahead with the full name.

# Images
![image](https://user-images.githubusercontent.com/6960386/63776023-8f90b180-c8ae-11e9-9fb8-06751d2b41e2.png)

**Comment by tristan-orourke** [comment]
First name is an option now! :+1
