### ISSUE TITLE
Bug - Job Poster Builder - some links between steps still not using the navigate() function

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#1353]
# Description
Some links between JPB steps, including the links on the Review page, are still making normal requests, not SPA-style navigation. Switching to SPA-style requests will significantly speed up page transitions.

**Comment by gggrant** [comment]
There is one instance here: https://github.com/GCTC-NTGC/TalentCloud/blob/dev/resources/assets/js/components/JobReview/JobReviewPage.tsx#L83

Changing to the `navigate()` function with `managerJobIndex` route doesn't work work properly. Leads me to believe it's like that for a reason.

@tristan-orourke @Khristophor 

Perhaps this can be closed?

**Comment by tristan-orourke** [comment]
> Perhaps this can be closed?
I'll take a quick look.

**Comment by tristan-orourke** [comment]
I set up a pr that I think fixes this okay. @gggrant can you double check?
