### ISSUE TITLE
Task - Admin - Add Sorting by Status to Job Posters

### ISSUE THREAD

**Issue by xander-miller** [GCTC-NTGC/TalentCloud#1402]
## Description
Add sorting job posters by status

Or a filter.

## Images
![image](https://user-images.githubusercontent.com/663395/64453688-23385e00-d0b7-11e9-8962-99a2a2f2251c.png)

## Acceptance criteria
- [ ] Can sort Job Posters by Status Column

**Comment by tristan-orourke** [comment]
I made the status column orderable. I also made the Manager column orderable at the same time. I accidentally pushed the change on dev instead of making a proper PR. e798b5c29611c48ca54da6ccaf4095b0addb980e

**Comment by gggrant** [comment]
Setting the orderable attribute doesn't work as intended on these columns.

I moved this back to in progress and undid the change in #1515.

**Comment by gggrant** [comment]
See #2192.

Needs re-estimate.
