### ISSUE TITLE
Copy - JPB Skills selection still have placeholder text

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#1409]
# Description
There's still placeholder text under each skill category - I suggest removing the text until the category description is ready.
![image](https://user-images.githubusercontent.com/44560341/64536136-8d831580-d2e6-11e9-8c6e-3394ed3abe01.png)

# Changes
Enter the approved copy here:

| English  | French |
| ------- | ------- |
| Content | Content |

- [ ] Copy provided in English and French.

**Comment by tristan-orourke** [comment]
For now, I'm adding the text from [this doc](https://docs.google.com/document/d/16Yqg5Q8Sruk1ujdaq8nkYMFXz2OReHqLf-8PSWczNzc/edit), but we still require translations.

**Comment by tristan-orourke** [comment]
@rositak For now, I removed the text like you originally suggested. Can you confirm that this file has the copy you want? We'll handle the translation, if you're happy with the text.

**Comment by rositak** [comment]
@tristan-orourke i've made some changes to the text but i think we can use this copy for now - there'll be changes once the recommendation feature is available
