### ISSUE TITLE
Bug - JPB Department not updating on job poster

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#1410]
# Description
After saving the confirming the department for the first time, the department and the mandate wouldn't change after updating the info under 'my profile'

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Confirm the department on 'Welcome'
2. Preview job poster - first impact paragraph
3. Change department in 'my profile'
4. Preview job poster. 

# Images
Place image attachments here.
![image](https://user-images.githubusercontent.com/44560341/64536581-5a8d5180-d2e7-11e9-9163-8f17990292e9.png)

![image](https://user-images.githubusercontent.com/44560341/64536607-624cf600-d2e7-11e9-903b-ecbe98206f98.png)

![image](https://user-images.githubusercontent.com/44560341/64536636-6da02180-d2e7-11e9-8734-01b44f307b5e.png)

- [ ] Regression test written.

**Comment by tristan-orourke** [comment]
Confusing, but working as intended (?)
