### ISSUE TITLE
Bug - JPB vs Profile builder

### ISSUE THREAD

**Issue by mattejackson** [GCTC-NTGC/TalentCloud#1417]
# Description

What is the interaction between the work environment and team culture questions on the Job Poster Builder vs the manager profile builder? Do duplicate questions only draw form the JBP now or is it from whichever section was most recently updated?

Also, there is no easy way to get back to the job poster that I was working on when I click the link to go to the manager profile section.

**Comment by tristan-orourke** [comment]
We should remove fields form the Manager Profile which have been replaced by Job-specific data. I believe this means the Team Culture and Work Env sections, but this should be confirmed.
