### ISSUE TITLE
Bug - JPB English test on French page (Work Environment, Key tasks, preview pages, progress bar, review page)

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#1436]
# Description
Clicked to switch to French, but the text on the Work Environment page remains as English

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Go to JPB
2. Click on 'français'
3. Skip to Work Environment

# Images
Place image attachments here.
![image](https://user-images.githubusercontent.com/44560341/64809466-5bccb180-d567-11e9-8bc5-881b5472315c.png)

- [ ] Regression test written.

**Comment by tristan-orourke** [comment]
Most of the page is translated, but a few paragraphs are still missing french text. Seems they may not be showing up in the `npm run translations` results for some reason.

**Comment by yonikid15** [comment]
The copy was added in, by Grant I believe.
