### ISSUE TITLE
[Design] - Applicant Job Browser

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1470]
# Status
- [x] Being Researched
- [x] Prototyping and Testing
- [ ] Data Story
- [ ] Ready For Dev

# Design Goal
**Please explain the primary goals of this design work.**

Eventually, as the platform scales, the browse jobs page will have to support a far greater number of jobs. This means that users will need a more efficient way to browse, which includes being able to search by keyword, filter by things like classification, language, location, etc.

# Research
**Please list/link to all research performed for or referenced in this design work. This can include research you've done in the past. Include research relevant to insights from team members as well. Don't be afraid to ask for references or documents! This section should also incorporate data collected from user testing.**

- https://emploisfp-psjobs.cfp-psc.gc.ca/psrs-srfp/applicant/page2440?fromMenu=true&toggleLanguage=en
- https://ca.indeed.com/jobs?q=&l=Ottawa%2C+ON (competitor, browse jobs)
- https://www.monster.ca/jobs/l-ottawa-on (competitor, browse jobs)
- Both Indeed and Monster really struggle with information density and whitespace usage - there's no real focal point on their browse pages, and this makes skimming very, very difficult.
- https://www.amazon.ca/s?k=teapot&ref=nb_sb_noss_1 (comprehensive filters)
- Ambient discussion about government jobs has indicated that clicking on a job, only to discover you don't meet the classification requirements/language profile creates a lot of frustration to users.

### GC Employee Feedback (Version 2)
- Being able to save filters for later is great.
- Recommended jobs are nice (if they work), but could potentially be more visually distinct.

### Feedback from Discussion w/ @JasmitaChawla (Version 2)
- A way to filter by skills might be helpful.
- It might be beneficial to separate classification from level, to help shorten the filter lists.
- ~There's a feeling that classification might be a more important filter than department, because it's more likely to be consistent or similar across an applicant's history.~
- ~We can definitely remove max salary.~
- ~We should add a "search" or "filter" button to make the filtering a decisive action instead of automatic.~

![IMG_20190923_094159](https://user-images.githubusercontent.com/6960386/65437666-2f7c2500-ddf2-11e9-9b2c-3379706acd8c.jpg)

### Feedback from Discussion w/ @vid (Version 2)
- Load More / Infinite Scrolling has disadvantages, perhaps use pagination instead?
  - Referencing: https://uxplanet.org/ux-infinite-scrolling-vs-pagination-1030d29376f1
  - Referencing: https://medium.com/@dalpattapaniya/infinite-scrolling-vs-pagination-f237592f339a
  - Referencing: https://www.orbitmedia.com/blog/why-we-choose-the-view-more-button-instead-of-pagination/
- ~Showing number of results would be super helpful.~

### Existing Job Summary:
![image](https://user-images.githubusercontent.com/6960386/65259512-c2574f80-dad2-11e9-8d24-e3f3ead9d0aa.png)

## Assumptions
**Please list all assumptions made during your design work. This should include behavioural assumptions made by the team that have no direct research references.**

- Jobs should be easy to skim
- Users will benefit from having jobs recommended to them based on their existing skills
- Users want to save a default set of filters so that they can browse quickly
- Filters should be below recommendations - going off my gut here - show me hyper local job matches first, that I can collapse or dismiss, then show me all jobs
- Users will benefit from choosing to show recommended jobs on the homepage instead of "latest jobs"
- No one will ever want to filter their list of jobs by a maximum dollar amount.

# Important Notes / Copy
**This is a space to include important notes for other team members, including things like key copy, questions that need to be asked at a later date, etc.**

- Do we need more than 3 recommendations? If yes, how many?
- Is keyword search actually useful?

# Wireframes / Images

Working Prototype: https://joshbeveridge.ca/tc-browse/

### Version 1
![image](https://user-images.githubusercontent.com/6960386/65066063-abd5ba80-d951-11e9-9f77-fefc3e720114.png)

### Version 2 
- Filters were moved to the left on desktop, because it was a waste of space to keep them on the top.
- Personalized filters were condensed into the filter bar, because why replicate things.
- Recommendation explanations were generalized, because it didn't make much sense to clutter the UI with repeated info (it's now a single sentence above the recommended jobs).
- Minor changes to the layout of condensed job cards do adapt them for more info.
- Added a keyword search.

![browse_proposal_04](https://user-images.githubusercontent.com/6960386/65354978-dd06f280-dbbe-11e9-9688-e7b2b0947257.png)

### Version 3
- Functional search button has been added, and save filters have been moved below with some accompanying text.
  - A modal was added to confirm the deletion of saved filters.
- Number of search results is now displayed.
- A bug was fixed where filters hidden on mobile wouldn't show up on desktop if you stretched the viewport (thanks @nicolsonaitken)
- Classifications were moved above departments.
- Max salary was removed.
- A (flexible) number was added to the load more button.

![browse_proposal_05](https://user-images.githubusercontent.com/6960386/65616393-f629ed80-df88-11e9-8864-09e392ebc859.png)

# Final Data Story
**Use this section to summarize where we started, and how and why we got to the approved design. This section must be complete before the issue can be handed off to development.**

TBD

**Comment by nicolsonaitken** [comment]
I would like the ability to show/hide this entire filter. If I can save it, I don't really think I need something that will take up almost 1/3 of my screen.

**Comment by joshdrink** [comment]
@nic - I'll fix that bug, thanks for pointing it out.

In terms of hiding the filters on desktop - what's the inherent benefit? Content in the right shouldn't be much wider than it already is (the wider the content, the harder it is to skim), so by hiding the filters you'd just be centring what's already there.

**Comment by nicolsonaitken** [comment]
@joshdrink Maybe it's just a matter of preference or how people take in information differently. In the image below, I simply find it much easier to read the version on the right versus the version on the left. 

![image](https://user-images.githubusercontent.com/5738959/65766135-17f5b280-e0f8-11e9-9d52-7bb544ed59b8.png)

**Comment by gobyrne** [comment]
Josh, I'd like a filter to enable "old" or "Closed" jobs to be shown as well. In the short to medium term, I see that as the main place we will actually be using these filter: to search old jobs.

**Comment by joshdrink** [comment]
Moved to Trello
