### ISSUE TITLE
[Design] - HR: Homepage

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1476]
# Status
- [x] Being Researched
- [ ] Prototyping and Testing
- [ ] Data Story
- [ ] Ready For Dev

# Design Goal
**Please explain the primary goals of this design work.**

The HR portal will need its own unique homepage with content dedicated to their specific user group.

# Research
**Please list/link to all research performed for or referenced in this design work. This can include research you've done in the past. Include research relevant to insights from team members as well. Don't be afraid to ask for references or documents! This section should also incorporate data collected from user testing.**

- Research Link 01
- etc.

## Assumptions
**Please list all assumptions made during your design work. This should include behavioural assumptions made by the team that have no direct research references.**

- HR Managers can act as advocates for Talent Cloud.
- HR Managers want resources they can share with other employees.

# Important Notes / Copy
**This is a space to include important notes for other team members, including things like key copy, questions that need to be asked at a later date, etc.**

# Wireframes / Images

Prototype Link: https://joshbeveridge.ca/tc-hr-home/

## Version 01 (Funnel Proposal)
- What is Talent Cloud (to an HR Manager)?
  - research based / user centred
  - policy compliant
  - distinction between partners and non partners
- Why does Talent Cloud benefit the HR process?
  - Testimonials?
  - skill taxonomies/database?
  - assessment tools highlight
- Request Events
  - Manager Engagement
  - HR How-to
- Resources
  - How to engage managers.
  - How to troubleshoot with managers.
  - Assessment Tools package?
  - Hiring 101 package?
    - who does what (matt's flow chart, simplified)

### Wireframe

![IMG_20191002_095921](https://user-images.githubusercontent.com/6960386/66050744-c5ebcd00-e4fb-11e9-9b9e-1aa1887b2414.jpg)

## Version 02
- Adds some clarity to how information will be laid out
- Adds basic colour suggestions
- Discussed with @rositak and Matt regarding content proposals for version 3
- Added the basic proposal for the UX CTA (see issue #1675 )

![hr-home-01](https://user-images.githubusercontent.com/6960386/66509105-5ac46c80-eaa0-11e9-9758-53f7f8f334ad.png)

# Final Data Story
**Use this section to summarize where we started, and how and why we got to the approved design. This section must be complete before the issue can be handed off to development.**

**Comment by gobyrne** [comment]
That unicorn wearing a tie... is brilliant.

**Comment by joshdrink** [comment]
from Matt, from Lindsay:

Because we tend to get more pushback from HR than managers, I think it would be great to proactively put info up that will address their concerns before they even air them. So, a few things we may want to either write about or link to on the HR portal's homepage are:

    What is TC doing that's different from how government has traditionally worked?
    Any information we can provide about how we're compliant with everything we should be compliant with
    Where are we going with TC - are there any features that will be added in the future that aren't yet, and what are they?

This is more so we don't get a bunch of messages saying "you should do this..." if we're already planning on it

**Comment by gobyrne** [comment]
This is our current text for "compliance". It would make me so happy if it came under a heading that said "Talent Cloud is very compliant!" but I would understand if we decide to stick with the one given:

**Tailored for GC Policy Requirements**
- All content bilingual and accessible
- All jobs classified by HR advisors
- All jobs also posted to GCjobs
- Integrated priority screening
- Privacy Impact Assessment in place
- IT Security protocols in place
- Authority to Operate
- TBS-approved online content
- PCO-approved social media

**Comment by joshdrink** [comment]
Closing this as it has been moved to Trello for design purposes.
