### ISSUE TITLE
[Design] -  Indigenous Talent Portal UI Concerns

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#1487]
# Indigenous Talent Portal UI
The Indigenous Talent Portal is a platform is being developed FOR the Indigenous community - BY the Indigenous community - to reclaim our stories and to reset the way Indigenous talent is valued. This sounds fairly significant but, it doesn't _feel_ right after walking through it. 

![Rollover](https://user-images.githubusercontent.com/5738959/65252125-6981ba00-dac6-11e9-905d-7a28c1873585.jpg)

The rollover for the Indigenous Talent Portal seems odd and out of place to me. It’s the only navigational element that has this type of rollover and although I understand why it is there, I don’t think it gets the results we are looking for. 

It initially doesn’t come across as special to me; it simply appears the other links are maybe broken? My initial reaction when I rolling over the Indigenous Talent Portal link was '_Crap, something’s broken somewhere._'

I think this issue is heightened by the fact that the next page doesn’t appear to have anything special on it, other than the content itself. At first glance, it just looks like every other page (with a fancy link).

**Comment by joshdrink** [comment]
@nicolsonaitken Can you also tack on the initial user feedback for this? I want to make sure we're recording all the context. Originally the _different_ link was to create a moment of "this is different", but I agree it could be improved upon.

**Comment by jurgenschaub** [comment]
For what it's worth, I thought the same thing: Not "this is a special link", but "the rollover on the other links is broken". Maybe Indigenous in colour and the others in B/W? Although that might be misinterpreted as a wayfinding hint.
