### ISSUE TITLE
Copy - Job poster builder skills page

### ISSUE THREAD

**Issue by mattejackson** [GCTC-NTGC/TalentCloud#1522]
# Description
There is still "Lorem ipsum" under each of the three types of skills.

# Changes
These instances can be removed (unless @nicolsonaitken disagrees) @yonikid15 

| English  | French |
| ------- | ------- |
| Content | Content |

- [ ] Copy provided in English and French.

**Comment by yonikid15** [comment]
Rosita already made an issue for this :)
