### ISSUE TITLE
Bug - Job Poster Builder not working in IE

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#1524]
# Description
A user reported that the Job Builder wasn't loading in IE, but that switching to Chrome fixed the issue.

**Comment by tristan-orourke** [comment]
@rositak Do you have any more details that the user may have reported?

**Comment by rositak** [comment]
Manager 1 (Sep 26): 
13:40 - I went in and created the poster but then realized I went too far and the app was hanging a lot.  I deleted the poster to start over, and now when I click create a poster, nothing happens.  I get the Intro screen but nothing else shows up to fill in.
14:27 - I couldn’t get it to work in Internet Explorer, I switched to Chrome with success.

Manager 2 (Sep 25)
I was using IE11 version 11.950.17134.0 on my Win10 PSPC laptop while dialed in from home over our department’s VPN.  I did the data entry for the posters throughout the day yesterday and the lags were consistent throughout the day.  I just tried again now (6:20pm ET, 25 Sept) and it seemed to load faster.  There was a momentary lag with a blank screen but soon say a loading message and then the content appeared. This manager offered to ping some IP addresses if that's helpful.

Note
I tried using the tool on both Chrome and IE on my Surface (both over the office network and VPN) when the managers reported the error. Though I noticed the builder took a bit longer to load on IE, I didn't experience the same issue as the two managers.

**Comment by rositak** [comment]
I tried to login again this morning.  I clicked into the My Job Posters area, then immediately clicked the Edit Job Poster link for the .Net poster and again got the blank page.  This was at 09:44am Atlantic Time (08:44 your time).  I’ve included a screen capture here.  Remaining on this screen, the loading message never appeared and the content never loaded.  Refreshing the screen had no result.
  
![image](https://user-images.githubusercontent.com/44560341/65884446-df0f4500-e366-11e9-8504-fc40199e147b.png)

Two minutes later (at 09:46am Atlantic Time), I then clicked the My Job Posters link to return to the list of posters, then again tried the Edit Job Poster link for the .Net poster and had the same result.  

Then at 09:47am AT I used the back button and tried again.  Same result.  

Right around that time my Outlook crashed, and we had an interruption to my network connection as my Instant Messenger app crashed as well.

Sometime around 09:55am AT when I tried the Edit Job Poster link again, it loaded as per normal.  However when I tried again at 10:01am AT, I got the blank result. 

A refresh of the page at 10:04am AT had the same results.  At 10:05am I tried the Edit Job Results of the Drupal Specialist and it was again blank.

In case you’re able to use my connection details to comb your logs here is my ipconfig results:

![image](https://user-images.githubusercontent.com/44560341/65884559-10881080-e367-11e9-99df-240ebb8f593a.png)

And if you’d like me to do any specific testing today to help you trouble shoot this, just let me know.  For our department, when you work from home the network architecture is an inefficient mess.  My laptop connects to my home wifi, then we create a CISCO AnyConnect VPN tunnel back to our VPN gates in HQ (note that I’m in Halifax).  Then my connection is routed from the PSPC departmental internet through our security perimeter (again in HQ) and out to the internet (or in this case, likely to the GC network layer between OGDs), then it would go in through TBS’s security perimeter (gate+proxy etc) and to your hosted GC Talent Cloud service.  Then the connect would reverse again to get back to me in Halifax.  So we’d be clearing multiple proxy servers, content scanners, encryption end-points, and lots of little additions of lag all along the way.

By contrast, I just tried to access the platform from my personal computer (on a Chrome browser), this was at 10:16am AT.  I logged in with no issues, went into the My Job Posters area and I had barely released the mouse from the Edit Job Poster link of the .Net poster when then content was already loaded.

At 10:18am AT, I successfully loaded the .Net poster on my work computer.  The pattern I saw was there was about a 3-4 second delay while the page itself was still loading (I could see the little spinning wheel in the browser tab next to the Job Builder: Review page title) and as soon as the spinning wheel icon switched to the Cloud with the lightning bolt, the loading note appeared and about 1 second later the content started to fill in.

But then at 10:21am when I tried to load the FA poster, the page was blank again.  I still saw the 3-4 second spinning wheel in the browser tab before the thunder cloud icon appeared next to the page name, but then the loading message and content never appeared. 

NOTE: Switching to a Chrome browser on my work computer had things loading more quickly (and consistently) this morning.  I tried several different times around 10:24am and they all loaded quickly.  0.5s to get the thunder cloud icon in the browser tab and again a fraction of a second for the loading message and content to appear.  I’ll continue to use Chrome from this point onwards, but again if you need me to help you test in IE11 (or Edge, which we also have) then I can.  You may want to add a note that IE11 is not a recommended browser for use with this site.
