### ISSUE TITLE
Bug - JPB and job poster Work Style option doesn't match

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#1527]
# Description
Telework:
"Almost never" on JPB becomes "Never" on job poster

Flexible hours:
"Almost never" on JPB becomes "Never" on job poster
"Sometimes" on JPB becomes "Occasionally" on job poster
"Occasionally" on JPB becomes "Sometimes" on job poster

Order of the options is different between Telework and Flexible hours

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Go to "Job Details" on JPB
2. Click on 'Occasionally' under Flexible hours
3. Click 'Save and preview'
4. Compare it with the job poster preview link (applicant version)

# Images
Place image attachments here.
![image](https://user-images.githubusercontent.com/44560341/65723346-37e79080-e07c-11e9-8736-8e4a9afd59f0.png)

![image](https://user-images.githubusercontent.com/44560341/65723399-5057ab00-e07c-11e9-84ce-50f9af3afaba.png)

![image](https://user-images.githubusercontent.com/44560341/65723425-606f8a80-e07c-11e9-9c74-1ab484a282a2.png)

- [ ] Regression test written.

**Comment by rositak** [comment]
@tristan-orourke i wanted to flag this issue as time sensitive, as it affects a poster we'd like to post tomorrow (Sep 26).

**Comment by tristan-orourke** [comment]
The frequency labels used in multiple places (twig and react) should come out of the database to be consistent.

**Comment by gobyrne** [comment]
Quick fix please
