### ISSUE TITLE
Copy - JPB French Remote work

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#1528]
# Description
Error in the remote work options

![image](https://user-images.githubusercontent.com/44560341/65723783-1a66f680-e07d-11e9-9bc6-3938d83c75a3.png)

# Changes
Enter the approved copy here:

| English  | French |
| ------- | ------- |
| Content | Content |

- [ ] Copy provided in English and French.

**Comment by tristan-orourke** [comment]
@gobyrne We need proper copy.

**Comment by gobyrne** [comment]
English is:
Yes, I'm willing to supervise employees anywhere in the world.
Yes, I'm willing to supervise employees in any province or territory in Canada.
No, I require the employee in this position to be in the same geographic location as the office.

French should be:
Oui, je suis prêt à superviser des employés partout dans le monde.
Oui, je suis prêt à superviser des employés dans n'importe quelle province ou territoire au Canada.
Non, j’exige que l’employé qui occupe ce poste soit dans le même lieu géographique que le bureau.
