### ISSUE TITLE
[Design] - HR Advisor Portal / Commenting

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#1532]
# Status
- [x] Being Researched
- [ ] Prototyping and Testing
- [ ] Data Story
- [ ] Ready For Dev

# Design Goal
**Please explain the primary goals of this design work.**

The purpose of this feature is to allow HR Advisors to intervene with Hiring Managers on the creation of Job Posters, Screening Plans and Screening Applicants in/out.

# Research
**Please list/link to all research performed for or referenced in this design work. This can include research you've done in the past. Include research relevant to insights from team members as well. Don't be afraid to ask for references or documents! This section should also incorporate data collected from user testing.**

- Feedback from Hiring Managers, HR Advisors and HR Users regarding the inability to comment within the process of building a job poster, building an assessment plan and screening candidates in and out.
- Direct feedback from both @rositak and @gobyrne that an HR Advisor should have the ability to intervene when needed.
- Conversation with an HR Advisor who shared a story that a poster had gone live with misinformation on it. The end result being that the job that was offered had to be rescinded because of the error.  
- This feature was reaffirmed within both HR Superuser Workshops held on September 25th. 

## Discussion w/ @laurenoncoffee @gobyrne @nicolsonaitken @Jerryescandon @JasmitaChawla @joshdrink 

- we discussed moving the comment history to the new job summary page (#1763)
- comments that relate to applicants in the job action should have distinction (both visually and accessibility wise)
- comments in this job summary UI should be filterable (e.g. hide all applicant comments) 

## Assumptions
**Please list all assumptions made during your design work. This should include behavioural assumptions made by the team that have no direct research references.**

- Hiring Managers and HR Advisors need some type of notification when a comment is made. 
- Comments made within the Portal must be saved and archived for a minimum of 5 years based on rules/regulations.
- Users will have the ability to Show/Hide comments
- HR Advisors can tag a comment as **Question**, **Recommendation** or **Required Action**
- Actions that will trigger comments include **creating a job poster**, **claiming a job poster**,  **closing a job poster**, **changing the status of an applicant**

# Important Notes / Copy
**This is a space to include important notes for other team members, including things like key copy, questions that need to be asked at a later date, etc.**

Later versions of commenting should (or could) include: 
- the ability to dismiss Questions and Recommendations,
- a _Mark as Resolved_ option for Required comments made by HR Advisors,
- email notifications. 

# Wireframes / Images

**Adding a Comment**
- HR Advisors can add a comment and then select whether it's a question, a recommendation or if it is required.

![image](https://user-images.githubusercontent.com/5738959/65767855-1e3a5d80-e0fd-11e9-9860-768224c1814e.png)

**A Saved Comment within the HR Advisor Portal**
- The comment is then saved and includes the date (and HR Advisors Name.
- Should time be added?

![image](https://user-images.githubusercontent.com/5738959/65767864-25616b80-e0fd-11e9-845b-a3b2d27d717e.png)

**Wireframes**
- [HR Advisor leaving a comment](https://xd.adobe.com/view/8700b83b-36dc-4fea-4d88-55e4936aa6ae-f131/?fullscreen)
- [Show/Hide Comments](https://xd.adobe.com/view/02f7ec3c-a2c3-40b4-518b-d8e79759f346-74c6/?fullscreen)

- [Interactions per page](https://xd.adobe.com/view/01f030c4-e497-40ec-4214-4255eb4965b9-77c1/)
- [Leaving a comment](https://xd.adobe.com/view/055b10c1-4a81-431b-6f8f-0722164aa005-736a/)

# Final Data Story
**Use this section to summarize where we started, and how and why we got to the approved design. This section must be complete before the issue can be handed off to development.**

**Comment by joshdrink** [comment]
Closing this as it has been moved to Trello for design purposes.
