### ISSUE TITLE
[Design] - HR: Job Index

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#1533]
Design Goal
**Please explain the primary goals of this design work.**

The purpose of this feature is to allow HR Advisors to quickly and easily get to the information that they are looking for and to respond quickly to issues that require their review, input or approval.

# Research
**Please list/link to all research performed for or referenced in this design work. This can include research you've done in the past. Include research relevant to insights from team members as well. Don't be afraid to ask for references or documents! This section should also incorporate data collected from user testing.**

- See HR Advisor Portal / Commenting #1532 

## Discussion w/ @laurenoncoffee, @gobyrne, @nicolsonaitken , @joshdrink , and @JasmitaChawla 
- it would be beneficial to include dynamic filters for:
  - manager
  - classification
  - has vs. does not have PSC process # 
- jobs should be classified into 2 main groups: active vs. complete
  - Lauren suggested this based on previous discussions with HR and her knowledge of of the archive structure
- jobs should display whether they have a PSC job process number, priority clearance number, and a letter of offer date issuance (entered via concierge)
- jobs should display both the time it has been with a manager and the time it has been with HR
- jobs should only be able to be punted back to managers if the adviser has either:
  - commented
  - submitted it for approval
    - can this be taken back?

@nicolsonaitken **Prototype Deliverable: an HR view of all jobs assigned to them, each with a chronological history of comments associated to that job action, as well as the "send back to manager" and "final approval" buttons.**

## Discussion w/ @laurenoncoffee @gobyrne @nicolsonaitken @Jerryescandon @JasmitaChawla @joshdrink 
- HR advisers will be able to claim a specific job through the job summary page (see issue #1763 ) 
  - this should put claimed jobs into a defined section at the top of the dashboard
- HR advisers need something new and polished to interact with, so we should focus on making this UI slightly more visual

## Assumptions
**Please list all assumptions made during your design work. This should include behavioural assumptions made by the team that have no direct research references.**

- HR Advisors will want to get to the relevant information as quickly as possible as noted within the HR Super User Workshops held on September 25th.
- per discussion with @nicolsonaitken we're assuming that HR Advisers have enough information on the card to know whether they should claim the job

# Important Notes / Copy
**This is a space to include important notes for other team members, including things like key copy, questions that need to be asked at a later date, etc.**

Job Index Status States include:
- Draft
- In Review
- In Translation
- In Approval
- Approved
- Ready to Post
- Published
- Closed
- Complete

## Chess Clock Feature Estimate
@tristan-orourke and I discussed the back'n'forth feature and he feels it'll be 3 days worth of pure development time, assuming the following:
- the commenting feature is already built, and built with this in mind
- we're not accounting for dev deployment/testing/bugfixing

# Wireframes / Images

Prototype Link: https://joshbeveridge.ca/tc-manager-dash/hr-adviser/

## Version 1

**Dashboard at a Glance**
- Posters Needing Your Attention
- New Posters Not Yet Completed

![image](https://user-images.githubusercontent.com/5738959/65769674-22b54500-e102-11e9-98ab-8bc79d569eb3.png)

**Wireframes**
- [Dashboard V1](https://xd.adobe.com/view/e5416bde-30e3-49bc-5790-5e77d8a4d22c-9370/?fullscreen)

## Version 2
- adds context
- breaks page up by claimed vs unclaimed
- brings back card format for unclaimed
- matches claimed jobs to the manager view

![manager-dashboard-sketch](https://user-images.githubusercontent.com/6960386/67315214-1e4b3480-f4d4-11e9-8135-3c3792bc7921.jpg)

## Version 3
- [Dashboard V3](https://xd.adobe.com/view/6d438863-6505-4807-5996-ddab663b1349-1b72/?fullscreen)

## Version 4

Link: https://joshbeveridge.ca/tc-manager-dash/hr-adviser

- added activity link and volume
  - this will work based on login timestamp - if there has been new activity since the last time you logged in, add it to the count
- hid the filters until they're needed

## Version 5

- added hiring manager (this is obvious needed info, it was just forgotten)
- add Talent Cloud specific timer
  - this was added as a result of @gobyrne and @nicolsonaitken because eventually the job action hits translation/concierge, and we should have a timer for this

![image](https://user-images.githubusercontent.com/6960386/68783775-825fa500-0609-11ea-8957-73cbf89bcaca.png)

### Future Features
- manager timer
- hr timer
- filters for the department section
- load more/pagination for the department section
- eventually we'll likely need filters for completed jobs too

**Additional Feature Requested**
During the last design review @laurenoncoffee requested the addition of a clock icon next to the Time with you, Time with Manager, Time with Talent Cloud as an addition visual cue or nudge to be added to the next version.

## Version 6

Prototype link: https://joshbeveridge.ca/tc-manager-dash/hr-adviser

### Changes
- updated the timer to reflect the new requests found in #2122 

### Screenshot
![image](https://user-images.githubusercontent.com/6960386/69761041-2f6f0d00-1134-11ea-99f9-4d1df2a89410.png)

**Comment by joshdrink** [comment]
@nicolsonaitken Looks like the prototype link for this is broken, can you refresh the link in XD and pop a new one in? Thank you!

**Comment by joshdrink** [comment]
Closing this as it has been moved to Trello for design purposes.
