### ISSUE TITLE
[Design] - New Site Navigation

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1551]
# Status
- [x] Being Researched
- [x] Prototyping and Testing
- [ ] Data Story
- [ ] Ready For Dev

# Design Goal
**Please explain the primary goals of this design work.**

The existing site's navigation isn't responsive on mobile, needs to be [migrated to Clone](https://designwithclone.ca/components/menu/), requires a bit of consolidation, and needs a more effective, obvious way of changing user roles.

# Research
**Please list/link to all research performed for or referenced in this design work. This can include research you've done in the past. Include research relevant to insights from team members as well. Don't be afraid to ask for references or documents! This section should also incorporate data collected from user testing.**

- A lot of basic menu research has been done on [Clone's generic menu](https://designwithclone.ca/components/menu/).
- See issue #1487 

## Assumptions
**Please list all assumptions made during your design work. This should include behavioural assumptions made by the team that have no direct research references.**

- Assumption 01
- etc.

# Important Notes / Copy
**This is a space to include important notes for other team members, including things like key copy, questions that need to be asked at a later date, etc.**

- We should probably edit the registration UI so that it asks managers and HR advisors to travel to and register on their respective portals.

# Wireframes / Images

Treetest Link:  https://ows.io/tj/f2y614lz 

## Version 01
- Left aligns the menu.
- Consolidates Profile, Logout under user menu option.
- Provides portal access through the user menu.

![IMG_20190930_133947](https://user-images.githubusercontent.com/6960386/65903027-ab91e200-e389-11e9-94c8-58e22cb21a70.jpg)

### Version 01 Ideas

Design Notes:
- Higher fidelity mockup of version 1.
- Assigns icons to each user group to make it easier to understand which portal you're on at a glance.

![image](https://user-images.githubusercontent.com/6960386/65909442-a7b88c80-e396-11e9-86a4-fdfdebff93c7.png)

Design Notes:
- Moves profile information away from portal selection.
- Makes current portal and the ability to switch portals very obvious.

![image](https://user-images.githubusercontent.com/6960386/65908319-35df4380-e394-11e9-9859-10f08be8d0db.png)

## Version 02
- Concept 01: breaks out profile from account info, as discussed with @Jerryescandon. This is because the account information is central, whereas profile information is specific to the portal, and is confusing if the account info appears with the portal information.
- Concept 02: moves the profile dropdown to the left to remove ambiguity from navigation options, and also breaks profile out from account based on the feedback above.

![image](https://user-images.githubusercontent.com/6960386/66320000-07112200-e8ec-11e9-98b1-6a65107cc4d9.png)

## Version 3
- updates the first option to reflect discussion and potential profile enhancements
  - puts portal into its own dropdown
  - puts individual profile "pieces" into their own dropdown for ease of access
    - this will remove the need for the subnav on the profile proper
  - renames account to settings

### 3A
![image](https://user-images.githubusercontent.com/6960386/67426900-05608300-f5a9-11e9-9bd4-f55df3a650c3.png)

### 3B
![image](https://user-images.githubusercontent.com/6960386/67427311-e0b8db00-f5a9-11e9-8e9a-f23dd5307129.png)

# Final Data Story
**Use this section to summarize where we started, and how and why we got to the approved design. This section must be complete before the issue can be handed off to development.**

**Comment by Jerryescandon** [comment]
I prefern Version 2 Concept 1. Would even change the name "My Account" for "Settings" sounds less related to personal info, and more to platform login stuff. Would need to debate what truly goes in there other than password stuff.

**Comment by joshdrink** [comment]
@Jerryescandon that's the one I'm leaning towards as well. I'm not opposed to changing it to Settings, however "My Account" is the standard for universal account information, particularly because it relates to email and name.

**Comment by gobyrne** [comment]
I like where this is going. "Settings" really stands out as something different from the list of "My ..." items. I like that it stands out, but agree that Account is what I'm used to seeing on websites. Maybe just "Account" instead of "My Account"? I don't feel too strongly about it though.

For 3B @joshdrink, I would consider expanding the left menu for the portal by including the portal name text in the menu bar. I would then get rid of the "home" button since the portal text could link to the homepage of any given portal.

Should the indigenous talent link be in the list of portals? @Jerryescandon

**Comment by joshdrink** [comment]
Closing this as it has been moved to Trello for design purposes.
