### ISSUE TITLE
Bug - Examples modal still not working in IE

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#1574]
# Description
In IE, clicking "Need help? See example" brings up the dark translucent overlay, but the modal doesn't appear and it can't be escaped. May be related to a clone exception, according to a console error.

It works fine in Chrome.

This was observed on Step 3 of the application.

**Comment by yonikid15** [comment]
Josh has fixed this issue in clone-framework.
