### ISSUE TITLE
Bug - Manager portal click here links 

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#1581]
# Description
The "Click here" link in the demo account banner goes to the top of the FAQ page and isn't very helpful for users to find out how to publish a job on Talent Cloud. Same thing with the "click here" link in the modal that pops up when users try to send a job poster for review. 

The "Click here" links should go to "Who can post jobs to Talent Cloud?" in the "Key Information" section, under "For Managers" on the FAQ page. 

# Steps to Reproduce
For banner:
1. Log on to the manager portal as a demo account user.
2. Click on "My Job Posters", "My Profile", or "FAQ"

For modal after clicking on "Send for Review"
1. Log on to the manager portal as a demo account user.
2. Go to "My Job Posters" page
3. Click on "Send for Review" on a draft job poster 

# Images

Banner:

![Capture7](https://user-images.githubusercontent.com/38079220/66055050-f2571780-e502-11e9-87ec-33ff05870f28.png)

Send for Review:

![Capture9](https://user-images.githubusercontent.com/38079220/66054957-cb98e100-e502-11e9-84a4-2869f7ae7114.png)

![Capture8](https://user-images.githubusercontent.com/38079220/66055014-e23f3800-e502-11e9-9255-485c1490f8ff.png)

- [ ] Regression test written.

**Comment by tristan-orourke** [comment]
Change the anchor text - instead of click here... anchor the whole sentence
