### ISSUE TITLE
Bug - Switch Language link is positioned incorrectly in IE

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#1585]
# Description
The Switch Language link is supposed to be located at the top-right of the page. In IE, it's positioned too far left.

![image](https://user-images.githubusercontent.com/4313717/66064812-27b83100-e514-11e9-9272-65fdf7a65433.png)

**Comment by yonikid15** [comment]
This is fixed already https://github.com/GCTC-NTGC/TalentCloud/pull/1573/commits/024c9e43ea022ac253bea614ef55c382757d52e5
