### ISSUE TITLE
Bug - JPB Culture section Copy to clipboard button

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#1588]
# Description
(Note: could be related to the JPB issue with IE, as this is the same manager who reported this issue. I tried and couldn't reproduce this error)

I made my choices but wanted to tweak the paragraph that was generated so I clicked the “Copy to Clipboard” button located after the Culture Summary section.  This jumped me to the end of the page...  When I scrolled back up to the Customize your culture summary text box it was still blank.  I clicked into it and used hot-keys to Paste the clipboard contents there but it was not what was in the compiled culture paragraph above. 

As I workaround, I just manually selected the paragraph and used hot-keys to copy it to clipboard myself.

UPDATE on this item… when I finished the rest of this section and reached the end of the page, I finally realized that some text fields had appeared there with the culture summary contained in them… I’m not clear if this was intentional, or an error… But I’d clicked the “Copy to Clipboard” button twice and I have two copies of the field there:

# Images
![Culture](https://user-images.githubusercontent.com/44560341/66068488-b11f3180-e51b-11e9-8755-323bf5e275fd.jpg)

- [ ] Regression test written.

**Comment by gggrant** [comment]
See issue #1681
