### ISSUE TITLE
Bug - JPB Work environment section checkbox

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#1589]
# Description
The selections that I made in the Our Physical Env, Technology, etc sections are not being reflected in my Preview of that section.

# Images
As enter
![Work environment 1](https://user-images.githubusercontent.com/44560341/66068799-415d7680-e51c-11e9-86c0-2f6b97054918.jpg)
Preview
![Work environment 2](https://user-images.githubusercontent.com/44560341/66068801-415d7680-e51c-11e9-8851-c9320cd04500.jpg)

- [ ] Regression test written.

**Comment by yonikid15** [comment]
I could not reproduce this error.

**Comment by rositak** [comment]
it's possible that it was a connection / explorer issue, as the manager was having trouble with the JPB in general when she reported the error

**Comment by gobyrne** [comment]
Ok, I will close for now. Please Open a new issue if it comes up again (or re-open this).
