### ISSUE TITLE
Bug - Manager - Padding on manager profile page (IE11)

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#1595]
# Description
Padding on the manager profile page needs a touch-up. The spacing is too big around the page heading and in a few other places.

This was observed in IE11.

**Comment by joshdrink** [comment]
This area isn't serving a purpose beyond name right now, so I'm going to hide it for the time being. Originally this area showcased social accounts and title, but that's all very clearly labelled below in the form.
