### ISSUE TITLE
Bug - List of departments for Demo Account does not have "Other Department" option

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#1599]
# Description
The list of departments on the demo account "First Visit" does not provide an option for government workers that are not in one of the listed departments.

We should add a "Other Government Department" or "Government Department not listed below" to the list.

**Comment by tristan-orourke** [comment]
After discussing with @gobyrne, we can simplify this fix by simply changing the text of the "Not in Government" option to something like "Other department or Not government"/"Autre ministère ou non gouvernement".

**Comment by gggrant** [comment]
Added via admin panel on staging server.

User is prompted for a government email when selecting 'Other Department'.

@gobyrne can you review?
