### ISSUE TITLE
All Browsers - Mobile Menu Tab Order

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#160]
Please name the task using the following information: **Browser - Name**. Give this issue the "**Bug**" label.

# Description
Tabbing through the mobile menu doesn't currently loop properly - you can tab through the menu and continue down the page when you should be able to cycle through the menu items and the close menu button.

# Steps to Reproduce
1. Tabbing on mobile views.

# Additional Context
N/A

**Comment by gobyrne** [comment]
Looks good. For some reason my tabbing is going into the search history when I get to the address bar. But I'm going to assume that's a browser thing.
