### ISSUE TITLE
Applicant - Job Poster Icons

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#162]
Please name the task using the following information: **Applicant/Manager/Admin/Sitewide - Name**. Assign this task to the appropriate person and give it the "**Task**" label.

# Description
Update the job objects on the job poster index to include iconography that matches the mockup below.

![image-2018-05-16-11-16-33-915](https://user-images.githubusercontent.com/6960386/41001373-b196b6c0-68de-11e8-8960-8775450cf6e6.png)

# Required for Completion
Add/remove others as necessary for this specific task.
- [x] Accessibility Check
- [x] Browser Compatibility Check

**Comment by gobyrne** [comment]
Looks good though the 2 icons are taking up different widths right now, so the text is a little offset. I think it would look better if the text aligned like in the design above.
