### ISSUE TITLE
Task - Ability to disable two factor auth

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#1665]
## Description:

Need to add an option inside the Applicant/Manager profile to remove the two factor authentication from their account. Should be as simple as a link that deletes the `google2fa_secret` key from the database, as well as providing a disclaimer that they need to remove the entry from their authenticator application of choice.

**Comment by tristan-orourke** [comment]
You should be able to reset your 2fa secret as well.
