### ISSUE TITLE
Spike - Device recognition

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#1671]
Research method of detecting user devices for 2FA.

**Comment by Khristophor** [comment]
So it looks like common solutions are:

1. A cookie

2. Various levels of effort around [browser fingerprinting](https://panopticlick.eff.org/). Basically setting a threshold of certainty around how close a fingerprint has to be to the last fingerprinted value and triggering the OTP entry when the new fingerprint is below the threshold.

Example of my fingerprinting results from the site linked above:
<img width="621" alt="Screen Shot 2019-11-04 at 11 03 16 AM" src="https://user-images.githubusercontent.com/6796588/68131235-125b6b80-fef3-11e9-8831-cf542b2f2396.png">

Fingerprinting is more resilient, but obviously would take considerable more effort to implement and have it work correctly. There are also privacy considerations around uniquely identifying people based on their device/location.

**Comment by tristan-orourke** [comment]
Cookies sound great.
