### ISSUE TITLE
[Design] - Design Research Recruitment Call-to-action

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1675]
# Status
- [x] Being Researched
- [x] Prototyping and Testing
- [ ] Data Story
- [ ] Ready For Dev

# Design Goal
**Please explain the primary goals of this design work.**

I'd like to propose a call-to-action section at the bottom of each homepage that actively seeks out users who are willing to test the platform. This section will link to a Google Form where they can submit their basic contact information and interest.

# Research
**Please list/link to all research performed for or referenced in this design work. This can include research you've done in the past. Include research relevant to insights from team members as well. Don't be afraid to ask for references or documents! This section should also incorporate data collected from user testing.**

- Research Link 01
- etc.

## Assumptions
**Please list all assumptions made during your design work. This should include behavioural assumptions made by the team that have no direct research references.**

- Users will willingly submit contact information to be testers.

# Important Notes / Copy
**This is a space to include important notes for other team members, including things like key copy, questions that need to be asked at a later date, etc.**

# Wireframes / Images

### Interface

![image](https://user-images.githubusercontent.com/6960386/66506428-4fbb0d80-ea9b-11e9-8948-88573ba7d83c.png)

### Form

![image](https://user-images.githubusercontent.com/6960386/66506383-3fa32e00-ea9b-11e9-953c-57c49af92446.png)

# Final Data Story
**Use this section to summarize where we started, and how and why we got to the approved design. This section must be complete before the issue can be handed off to development.**

**Comment by gobyrne** [comment]
I think this is a great idea. Let's do it. (also the unicorn is great)
