### ISSUE TITLE
Task - Admin - Job Completion

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1678]
# Description
During conversations regarding the HR portal, it was mentioned that admin users will need to set the status of a job action from active to complete (whether it is successful or not) which will, in turn, affect the way that job displays to HR advisers down the road.

- This should stop the clock on the "review applicants" page.
- This should also move the job to the "My archived posters" on https://talent.canada.ca/en/manager/jobs

**Comment by tristan-orourke** [comment]
We'll need to store the time of archiving.

**Comment by tristan-orourke** [comment]
This can be accessible only via Admin Portal right now.

**Comment by tristan-orourke** [comment]
Rolled into #2189.
