### ISSUE TITLE
[Dev] - User Account Page

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1680]
# Status
- [x] Being Researched
- [x] Prototyping and Testing
- [x] Data Story
- [x] Ready For Dev

** @laurenoncoffee approved this for Dev on 2019-10-24**

- [ ] make sure this migration happens on both portals
- [ ] use the platforms existing 2FA interim steps instead of those presented in the wireframe
- [ ] add UI to further explain applicant profile information is optional (request from @laurenoncoffee)
- [ ] update 2FA UI to match Matt's copy
- [ ] GoC info (the second section on the page) should only show if you've visited the manager portal at least once
- [ ] make sure tests are updated to reflect these new UIs

# Design Goal
**Please explain the primary goals of this design work.**

There has been repeated expressed interest in breaking the account information out of the user's profile page and into it's own home. This has become more important recently due to the fluctuating nature of how account information is handled vs. how profiles display portal-specific information. 

We want to avoid confusion for users by display overarching account information alongside information that changes as they navigate from portal to portal to ensure that they understand they are separate and have different underlying effects when changed.

Related: Issue #1551 

# Research
**Please list/link to all research performed for or referenced in this design work. This can include research you've done in the past. Include research relevant to insights from team members as well. Don't be afraid to ask for references or documents! This section should also incorporate data collected from user testing.**

- generally we performed minimal research and testing on this page because it is simply a migration of existing information to a more centralized location
- we observed other websites' use of account settings pages to host similar information

## Assumptions
**Please list all assumptions made during your design work. This should include behavioural assumptions made by the team that have no direct research references.**

- Users find it confusing that their account information is displayed alongside their profile.

# Important Notes / Copy
**This is a space to include important notes for other team members, including things like key copy, questions that need to be asked at a later date, etc.**

It's probably best if we only show department (or lack thereof) and government email on this page if the user HAS visited the manager/HR adviser portals. If the user is simply an applicant, there's no need to burden their account page with this information.
- it should also be clear that this information is specific to the manager/HR adviser portals when it is shown

For Matt:
We need copy outlining the whole flow (see the prototype link below), as well as copy explaining why 2factor is a good idea and generally how it works. This should include a list of apps and will be located in the area where there is currently lorem ipsum in the prototype. We also need content for an error page that will explain why the user can't access the specific page/feature without turning 2fa on, as well as how to do so.

# Wireframes / Images

Prototype link: https://joshbeveridge.ca/tc-account/

## Version 01

![account-sketch](https://user-images.githubusercontent.com/6960386/66512346-b42f9a00-eaa6-11e9-8a67-b04e943a2cbf.jpg)

## Version 02
- added GoC information and department contact alert
- included flow for turning 2-factor on and off

![account_01](https://user-images.githubusercontent.com/6960386/66601705-8580f480-eb76-11e9-961b-8e9d49b85d71.png)

# Final Data Story
**Use this section to summarize where we started, and how and why we got to the approved design. This section must be complete before the issue can be handed off to development.**

After researching how other websites handle account information, we felt it was necessary to separate account data from portal specific profile information.

**Comment by mattejackson** [comment]
from Lindsay:

Because we tend to get more pushback from HR than managers, I think it would be great to proactively put info up that will address their concerns before they even air them. So, a few things we may want to either write about or link to on the HR portal's homepage are:

1. What is TC doing that's different from how government has traditionally worked?
2. Any information we can provide about how we're compliant with everything we should be compliant with
3. Where are we going with TC - are there any features that will be added in the future that aren't yet, and what are they? 

This is more so we don't get a bunch of messages saying "you should do this..." if we're already planning on it

**Comment by joshdrink** [comment]
@mattejackson moving this to issue #1476
