### ISSUE TITLE
Sitewide - Form Input Templates

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#169]
# Description
Form inputs on the site should maintain a consistent and accessible design that leverages HTML5 validation on the client side to enable a fast and sufficient amount of feedback to the user.

Google Floating Labels: https://material.io/design/components/text-fields.html#usage

All forms on the site should be converted to match this new convention, including those on the hiring manager.

# Images
![img_20180607_144606](https://user-images.githubusercontent.com/6960386/41175094-fbb1ea66-6b29-11e8-81e5-95763c3608c0.jpg)

# Required for Completion
Add/remove others as necessary for this specific task.
- [x] Run Lighthouse (Chrome Dev Tools)
- [x] Run WAVE Evaluation
- [x] Browser Compatibility Check
- [x] Consider/Perform Peer Review
- [x] Push to `master`

**Comment by joshdrink** [comment]
Lighthouse & WAVE both highlighted the label/input relationship, but because this is a sample form, these errors are irrelevant.

**Comment by joshdrink** [comment]
"Error Text" requires some advice for appending content. @gggrant I'd love your input on this.

**Comment by gggrant** [comment]
Applicant side could still use an accessibility review (mainly the repeating elements)
