### ISSUE TITLE
Bug - Word Counter on Applicant Profile Skills in Chrome

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1702]
# Description

@gobyrne reported that the word counter on profile skills wasn't responding to typing. He wasn't sure if this was also occurring on the job application, but if it's isolated, it could be the result of the partial being imported without a dependency or ID, etc.

**Comment by yonikid15** [comment]
Everything seems to be working on the dev branch. It might be because the progress ring's movement is subtle since the min and max range is set pretty high (200 words - 350 words). Can you please double check and let me know :)

**Comment by yonikid15** [comment]
Correction. Word counter isn't working when user adds a NEW skill.
