### ISSUE TITLE
[Design] - Modify Job Poster Previews

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1722]
# Design Goal
**Please describe the ask.**

We need to make a few changes to manager-facing job poster previews to make it more clear that they are viewing an instanced preview of what their job poster will look like to applicants.

**Related Features:** 
- Job Poster Builder
- Manager Dashboard

# Wireframes

Prototype Link: https://joshbeveridge.ca/tc-job-preview/

## Version 01
- adds a clearer title and set of breadcrumbs
- adds an alert to indicate the nature of the preview and the available options below (this is to help make the options at the bottom more visible)
- contains the preview in a pseudo-window (I might make this a fixed height to force them to scroll through it, and to bring the buttons closer to the top of the page)
- adds actions to the bottom of the page that resemble the job poster builder to indicate that the preview is a pseudo step in the process

**Comment by gobyrne** [comment]
The design works for me @joshdrink . Would you like feedback on the copy now?
