### ISSUE TITLE
Copy - Move the departmental info content in the FAQ

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/TalentCloud#1724]
# Description
This only requires to move information from one place to another on the same page. No copy or translations necessary.

# Changes
Move "Talent Cloud Partner Departments" from "For Applicants" to "For Managers":
![image](https://user-images.githubusercontent.com/16977254/66856738-da948000-ef53-11e9-9594-19080af097dd.png)

**Comment by tristan-orourke** [comment]
Already done
