### ISSUE TITLE
[Design] - Redesign Manager Dashboard

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1731]
# Design Goal
**Please describe the ask.**

In order to better accommodate the new job poster builder, we want to modify the flow in which a job poster is submitted once complete. Alongside this, we want to enhance the manager dashboard to better indicate the priority action for the job poster based on its current state.

**Related Features:** 
- Job Poster Builder

**Related Issues:**
- Issue #1722 

# Notes
**Elements of the job action on the dashboard:**
- job status
  - draft
  - in review
  - approved
  - published
  - closed
  - complete
- action required indicator
- job title
- classification
- timer
- number of applicants (specific to published, closed, and complete statuses)
- primary action button
  - edit job poster (specific to draft)
  - preview and submit poster (specific to in review)
  - edit screening plan (specific to approved, published)
  - view applicants (specific to closed)
  - *complete jobs have no primary action
- secondary action buttons
  - edit job poster (active for draft, in review)
  - view preview / poster (active for draft, in review, approved, published, closed, complete)
  - edit screening plan (active for draft, in review, approved, published)
  - view applicants (active for closed)
  - delete poster (active for draft, in review, approved)

# Wireframes

Prototype Link: https://joshbeveridge.ca/tc-manager-dash/

**Comment by Jerryescandon** [comment]
Please also take into consideration a long term plan for a complete overview of a process and its sections. For consideration, take a look at prototype for some ideas: https://xd.adobe.com/view/3d2cfadf-d5ed-46f8-4f5f-94a6df0b7e14-4b1d/?fullscreen

**Comment by joshdrink** [comment]
Yes, but also no, because this is something we're building long before any of that other stuff. It will 100% need to be modified afterwards, but as long as some of that is wishy washy, I don't want it to dictate things too too much. I'll take a peek and see if anything directly impacts the existing information.

**Comment by gobyrne** [comment]
I mentioned to Josh that "in review" and "draft" are kinda meshed together right now, and he seems to have a plan for it. The question is whether the primary action is "edit" or "preview and submit". We prefer "edit" but will need to test to see if real managers can find the publish button at the bottom of the "review" page on the job poster builder.

And I'm with Josh, I think the work you put forward Jerbo is too far in the future to plan towards right now.
