### ISSUE TITLE
Copy - Missing copy on Review applicants page

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/TalentCloud#1735]
# Description
Missing copy for three of the buckets. 
[ ] Veterans and Canadian citizens 
[ ] Non-Canadian Citizens 
[ ] Unqualified 

![image](https://user-images.githubusercontent.com/22059495/66952234-37fb0080-f02a-11e9-9273-ce208c15892e.png)

File to change: **ReviewCategory.tsx**

# Changes
Enter the approved copy here: **Needs copy**

- [ ] Copy provided in English and French.

**Comment by gggrant** [comment]
Duplicate. Fixed by #2138

**Comment by yonikid15** [comment]
This issue is to get copy for the buckets.

**Comment by yonikid15** [comment]
duplicate of #2156
