### ISSUE TITLE
[Design] - Manager/HR: Applicant Summary

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1745]
# Status
- [x] Being Researched
- [x] Prototyping and Testing
- [ ] Data Story
- [ ] Ready For Dev

# Design Goal
**Please explain the primary goals of this design work.**

When screening/assessing candidates, managers need a summary view of a single applicant so that they can understand that applicant's state in the process, as well as how they're doing in terms of evaluation. This view needs to include a glance-able overview of their assessment record, as well as individual specifics on each criteria, including records, notes, exams, files, etc.

# Research
**Please list/link to all research performed for or referenced in this design work. This can include research you've done in the past. Include research relevant to insights from team members as well. Don't be afraid to ask for references or documents! This section should also incorporate data collected from user testing.**

- Research Link 01
- etc.

## Assumptions
**Please list all assumptions made during your design work. This should include behavioural assumptions made by the team that have no direct research references.**

- Assumption 01
- etc.

# Important Notes / Copy
**This is a space to include important notes for other team members, including things like key copy, questions that need to be asked at a later date, etc.**

This issue is a part of the manager flow:
My Jobs -> Job Summary -> (Applicant Overview) *OR* (Applicant Summary -> ROD)

Assessment should determine the strength of the candidate, so the results on this page help indicate on the Job Summary page which applicants are the strongest of the bunch.

# Wireframes / Images

## Version 2ish
- provides applicant metadata like name, contact, application link, profile link, etc.
  - this includes priority, vet status, etc.
- summarizes the current state of the applicant's screening/assessment process (labelled as stages in the wireframe)
- assessment results show an overview first, where it is obvious which skills are failed/good/strong or not applicable
  - each skill name in these tables should link to the respective accordion found below
- overview is followed by individual skill accordion which includes:
  - detailed assessment result for that skill (what methods, how they did)
  - notes
  - files
  - exams
  - etc.

![manager-applicant-summary-sketch](https://user-images.githubusercontent.com/6960386/67045764-ecfded80-f0fc-11e9-8b79-45ff31dd9162.jpg)

## Version 3

A higher fidelity wireframe of the previous version: 

![Candidate Snapshot](https://user-images.githubusercontent.com/38079220/67897405-ad8bc400-fb34-11e9-8d89-7da6863c5a78.png)

The skill assessment details accordion is organized by assessment type, not sure if we want to keep it like this, it has a lot of info. 

# Final Data Story
**Use this section to summarize where we started, and how and why we got to the approved design. This section must be complete before the issue can be handed off to development.**

**Comment by gobyrne** [comment]
@JasmitaChawla Lauren had some feedback on this when we last discussed. I think it was a reflection on how much screen-space to track different parts of the screening. Anyway, you also had a much more advanced prototype.
