### ISSUE TITLE
Feature - Make HTTP error pages more funner

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#1746]
Low priority.

# Description
According to Wikipedia: "Many organizations use 404 error pages as an opportunity to inject humor into what may otherwise be a serious website."
https://en.wikipedia.org/wiki/HTTP_404

**Is your feature request related to a problem? Please describe.**
We are missing an opportunity to inject humour into our otherwise serious website.

**Describe the solution you'd like**
Something better, funner and more awesome.

**Describe alternatives you've considered**
Leaving it the way it is.

# Images
![ART-dabbing-unicorn_color-powder-blue_1024x1024](https://user-images.githubusercontent.com/31678168/67049399-238b3680-f104-11e9-80be-b230a63f0520.jpg)

# Acceptance criteria
- [ ] Unicorns

**Comment by Khristophor** [comment]
Honourable mentions:

https://www.amazon.com/sadfws

https://www.magnt.com/asdfasd

**Comment by nicolsonaitken** [comment]
My honourable mention:

[http://madgeeklove.com/sdf](http://madgeeklove.com/sdf)
