### ISSUE TITLE
Spike - Classification vs. Level Recommendations

### ISSUE THREAD

**Issue by JoshBeveridge** [GCTC-NTGC/TalentCloud#1761]
# Description
Enter the spike description here. What will we be researching?

Lauren would like to know the gist of how complicated it would be to provide a manager with recommendations or alerts based on the classification level they have selected and the level of the skills they're asking for. The idea here is to nudge managers away from behaviour such as hiring a CS1 and yet asking for a couple essential skills at the intermediate/advanced level.

There would need to be a UI that displays this nudge, as well as an admin UI to manage how classification/level associate with them. I'm not entirely sure whether we can blanket label all levels the same way regardless of a classification (e.g. CS1 and AS1 get the same nudge logic) or if the it needs to be independent. Chat with @laurenoncoffee for specifics on this.

**Comment by gobyrne** [comment]
If we have a lookup table to say which "classification-level" should get notified for which "skill-level" then it's possible. If that's not available, this is probably not possible. The effort required will depend on the actual nudge that's being suggested.
