### ISSUE TITLE
Spike - Targeted Emails to Applicants

### ISSUE THREAD

**Issue by JoshBeveridge** [GCTC-NTGC/TalentCloud#1762]
# Description
Enter the spike description here. What will we be researching?

We'd like to know the complexities behind sending targeted emails to applicants that show them jobs that match skills in their profile. We'd need an opt-in/opt-out UI on both the registration and the profile.

**Comment by gobyrne** [comment]
As long as we have rule that tells us whether or not the skills "match" a person's profile, this can be done. We, for example, could run a script daily that looks for newly published job posters than checks all profiles for matches and emails ones that do match.

It's not too complex, but will need to be thought through. As you mention and opt-out would be needed.

**Comment by bitliege** [comment]
If we're being fancy and following common practice, we could also offer time intervals; e.g. email me jobs every day, email me jobs in bulk every week, email me jobs in bulk every month.
