### ISSUE TITLE
All Browsers - Open Ended Description Styles

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#177]
Please name the task using the following information: **Browser - FED/BED - Name**. Give this issue the "**Bug**" label.

# Description
Descriptions on open ended questions during the job application require paragraph styles (black, smaller, lower line height font).

# Steps to Reproduce
1. View open ended questions on a job application.

# Images
N/A

# Additional Context
N/A

**Comment by gobyrne** [comment]
Looks good
