### ISSUE TITLE
Bug - Manager FAQ Links Show Applicant Info

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#1831]
# Description

Right now, when you visit the FAQ from the manager portal, the applicant accordion in the sidebar is expanded, and you're taken to the top of the page, which shows applicant related information.

Ideally:
- the applicant accordion would be collapsed, and the manager accordion would be expanded
- it would automatically scroll you to the first manager section

**Comment by gggrant** [comment]
Already done.
