### ISSUE TITLE
Feature - JPB - Warn user if they attempt to follow a link and have unsaved data on the page 

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#1850]
# Description

Clicking on a link (at a minimum, links in the Progress Bar) should first warn user if they have unsaved data.

We currently do this in at least some parts of the Timeline application. This issue is about bringing them over to the JPB

**Comment by gobyrne** [comment]
This is being done in some places, but not consistently. JPB and Application are the most relevant.
