### ISSUE TITLE
Bug - Manager - Demo warning not showing up on JPB and SPB

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#1856]
# Description
The demo warning "this is a demo account..." is not showing up on my Job Poster Builder (JPB) pages or my Screening Plan Builder (SPB). It is, however, properly displaying on the "My Job Posters" page and "My Profile" page.

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Register on Manager Portal
2. Select TBS as department (don't know if this matters, but I did it)
3. Navigate to "My Job Posters" and click "Create a new poster"
4. See error (or don't see)

- [ ] Regression test written.

**Comment by Khristophor** [comment]
This would be a feature request, the original design didn't mention those areas
https://github.com/GCTC-NTGC/TalentCloud/issues/1221
