### ISSUE TITLE
[Design] - Managers are not completing their profiles

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#1857]
# Design Goal
With the new Job Poster Builder, the manager profile is less obvious. Rosita has mentioned that it's getting missed. Could you please propose a way to work it back into the flow? We want managers to encounter it, but probably don't want them doing it until after the JBP so that it doesn't slow them down. It can be a little intimidating in it's current form. Also, we need to redo the manager profile...

**Related Features:** 
- JBP
- Manager Profile

**Related Issues:**
- Issue #1
- etc.

**Comment by gggrant** [comment]
Let us know.
