### ISSUE TITLE
Applicant - My Applications Development

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#186]
Please name the task using the following information: **Applicant/Manager/Admin/Sitewide - Name**. Assign this task to the appropriate person, give it either a "FED" or "BED" label, and give it the "**Task**" label.

# Description
The applicant Dashboard (now My Applications) needs to be hooked up to the back end of the project. The UI exists on the `jb_my_apps` branch. This work includes setting up the ability to edit drafts and view application previews.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Consider/Perform Peer Review
- [ ] Push to `master`

**Comment by gobyrne** [comment]
Obsolete after refactor
