### ISSUE TITLE
Bug - Translation on Review Applicants page not working,

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/TalentCloud#1886]
# Description
French translation for Review Applicants page is broken.

# Images
![image.png](https://images.zenhubusercontent.com/5d9df0b9aba55400015a68fe/1d3cfffb-0771-46b2-bbdf-c275744c4786)

**Comment by Khristophor** [comment]
I don't think it's broken, per se, it just looks like we don't have translated copy
<img width="1439" alt="Screen Shot 2019-11-04 at 11 14 32 AM" src="https://user-images.githubusercontent.com/6796588/68132004-59962c00-fef4-11e9-8ceb-30f39a6370c8.png">

**Comment by yonikid15** [comment]
I'm pretty sure the translated copy was there. I could be wrong.
And yes sorry about that!

**Comment by gobyrne** [comment]
Looks like it's fixed now. Thanks.
