### ISSUE TITLE
All Browsers - Config Files in Git

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#190]
Please name the task using the following information: **Browser - Name**. Give this issue a "FED" or "BED" label, alongside the "**Bug**" label.

# Description
Config files and passwords are currently checked into Git. This was originally a result of the team not having admin access to the server (stated by Gregg). This bug includes externalizing all config files as necessary.

https://github.com/GCTC-NTGC/TalentCloud/tree/master/public_html/tc/config

# Steps to Reproduce
1. View files on Github.

**Comment by gobyrne** [comment]
Completed during refactor
