### ISSUE TITLE
Bug - Word collision on French register

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#1928]
# Description
Word collision on French "confirm password" on manager portal registration page.

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Go to Manager portal
2. Click on Register
3. Switch to french page if not already there.

# Images
![image](https://user-images.githubusercontent.com/2494551/68300621-27a7d580-006c-11ea-9118-153b84fb79a8.png)

**Comment by joshdrink** [comment]
I'm going to fix this in Clone proper - though I think it might be worth still stacking these fields, because even with the fix, the label is going to be 3 lines long.
