### ISSUE TITLE
Applicant - Improve "Edit OpenID" Link

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#193]
Please name the task using the following information: **Applicant/Manager/Admin/Sitewide - Name**. Assign this task to the appropriate person, give it either a "FED" or "BED" label, and give it the "**Task**" label.

# Description
As it stands, the link to edit your OpenID information is embedded on the profile modal and is extremely small. Investigate whether there are GCTools standards we can follow to make this link more useful.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Consider/Perform Peer Review
- [ ] Push to `master`

**Comment by gobyrne** [comment]
Obsolete after refactor
