### ISSUE TITLE
Task -  2FA - Add proper copy and translations for 2FA views

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#1932]
# Description
Add properly informative copy, including translations, to all 2FA views.

# Existing views
### Profile, pre-activation
![Profile, pre-activation](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/ef2bcb4b-c11e-4c98-99e1-11d7653172f0)
### Profile, post-activation
![profile, post-activation](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/adc1214c-8cbf-41b6-a9ac-a7bc397c1f5d)
### 2FA Activation
![2fa activation](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/4e189e6e-f5a3-417b-9659-483e5d16310e)
### Viewing Recovery Codes
![viewing recovery codes](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/08c0952c-138b-4358-93e4-6a387af0681b)
### OTP Entry
![otp entry](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/5d9ce8f2-2dac-49b8-a3fd-bf5c619da611)
### Recovery Code Entry
![recovery code entry](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/c46eba63-374a-416e-9bf3-0f343ed58020)
### Action requires 2FA activation
![action requires 2fa activation](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/d8c0249a-a454-48f8-b4ad-fa58f60485da)

# Acceptance criteria
Translated copy is in all the following places:
- [ ] Profile (pre activation)
- [ ] Profile (post activation)
- [ ] recovery code entry 
- [ ] view recovery codes
- [ ] 2fa activation
- [ ] one time password entry
- [ ] 2fa activation required error

**Comment by mattejackson** [comment]
copy looks good but I was inconsistent with some nomenclature. Can we use "Two-factor" (as opposed to two factor and 2 factor) throughout? Specifically on 2FA Activation and Error pages

on OPT and recovery code entry it should be "One-Time"

**Comment by gggrant** [comment]
Fixed consistency. English text with Matt (in translation).

**Comment by mattejackson** [comment]
French Text

'two_factor_description' => 'Two-factor blurb.'

Même un mot de passe fort ne suffit pas pour protéger votre compte. Si vous utilisez le même mot de passe pour différents sites Web, si vous cliquez sur des hyperliens dans des messages électroniques ou faites des téléchargements sur Internet, vous risquez de vous faire voler votre mot de passe. Et si quelqu’un d’autre accède à votre compte, il peut s’en servir pour faire toutes sortes de mauvaises choses.

L’utilisation de l’authentification à deux facteurs (A2F) ajoute une couche de sécurité supplémentaire lorsque vous ouvrez une session dans le Nuage de talents. Pour utiliser l’A2F, vous devrez installer une application compatible avec Google Authenticator sur un appareil distinct, par exemple votre téléphone cellulaire. Voici quelques applications compatibles :
•	1Password pour iOS, Android, OS X, Windows
•	Authy pour iOS, Android, Chrome, OS X
•	FreeOTP pour iOS, Android et Pebble
•	Google Authenticator pour iOS
•	Google Authenticator pour Android
•	Google Authenticator (port) sur Windows Store
•	LastPass Authenticator pour iOS, Android, OS X
•	Microsoft Authenticator de Windows pour Windows Phone

Pour activer l’A2F, vous devez lier votre téléphone (ou un autre appareil) à votre compte de Nuage de talents en balayant un code QR. Ainsi, vous serez en mesure de générer un mot de passe à usage unique sur demande lorsque vous ouvrez une session. Une fois que vous utilisez l’A2F, vous n’aurez plus à l’utiliser pendant 30 jours sur cet appareil. (Vous devrez quand même entrer votre nom d’utilisateur et votre mot de passe.)

# Profiles (applicant/manager)

'two_factor_legend' => 'Authentification à deux facteurs',
'two_factor_button_text' => 'Configuration de l’authentification à deux facteurs',
'two_factor_recovery_legend' => 'Codes de récupération',
'two_factor_recovery_text' => 'Vos codes de récupération d’urgence vous permettent d’accéder à votre compte si vous n’avez plus accès à votre téléphone. Pour des raisons de sécurité, nous vous les montrons une seule fois, mais vous pouvez générer de nouveaux codes.',
'view_recovery_codes' => 'Découvrez vos codes de récupération.',
'two_factor_description' => 'Texte sur l’authentification à deux facteurs',
'two_factor_active' => 'Vous recevez actuellement des codes de vérification au moyen d’une application d’authentification sur votre téléphone intelligent. ',
'two_factor_deactivate' => 'Désactivez l’authentification à deux facteurs. ',

# Two-factor auth

'title' => 'Activez l’authentification à deux facteurs'
'return' => 'Revenez au profil',
'header' => 'Activez l’authentification à deux facteurs',
'setup' => 'Configurez votre application d’authentification à deux facteurs en balayant le code QR dans une application mobile comme Google Authenticator ou Authy. Vous pouvez aussi utiliser le code ci-dessous.',
'qr_alt' => 'Image du code QR à utiliser avec l’application d’authentification.',
'warning' => 'Vous devez configurer votre application d’authentification avant de continuer. Autrement, vous ne pourrez pas ouvrir une session.',
'instructions' => ' Après avoir configuré votre application d’authentification, entrez le mot de passe à usage unique et continuez.',
'next_text' => 'Suivant',
'cancel_text' => 'Annuler',
'cancel_link_title' => 'Profil',
'activation_otp_error' => 'Il y a eu un problème avec votre mot de passe à usage unique. Nous avons généré une nouvelle clé secrète d’authentification à deux facteurs pour vous.'

# Recovery codes

'title' => 'Découvrez vos codes de récupération',
'return_title' => 'Revenez à la page d’accueil.',
'return' => 'Retour à la page d’accueil,
'header' => 'Découvrez vos codes de récupération.',
'instructions' => 'Gardez-les en lieu sûr. Vous pouvez les utiliser si vous ne pouvez plus accéder à votre téléphone. Chaque code de récupération ne peut être utilisé qu’une fois.',
'description' => 'Voici vos codes :',
'generate_label' => 'Vous pouvez générer un nouvel ensemble de codes de récupération. Cette action supprimera vos anciens codes.',
'generate_button' => 'Générez de nouveaux codes de récupération.',
'profile_link_title' => 'Profil',
'profile_link_text' => 'Retour au Profil'

# Errors

'title' => 'Erreur',
'refresh_page' => 'Veuillez actualiser la page.',
'two_factor_required' => 'Vous devez activer l’authentification à deux facteurs pour accéder à cette ressource.'

**Comment by gggrant** [comment]
```
# Use recovery codes

'title' => 'Use a Recovery Code',
'return_title' => 'One-time Password.',
'return' => 'Back to One-time Password',
'header' => 'Use a Recovery Code',
'instructions' => 'Enter a Recovery Code. Remember, each code can only be used once.',
'form_label' => 'Recovery Code',
'placeholder' =>  'e.g. 1234abcd-efgh5678',
'submit' => 'Login',
'incorrect_code' => 'Wrong code. Try again.',
'otp_link_title' => 'One-time Password',
'otp_link' => 'Log in with One-time Password.',

# One-time password

'title' => 'One-time Password',
'return_title' => 'Return to the home page.',
'return' => 'Return Home',
'header' => 'Enter One-time Password',
'login' => 'Login',
'next' => 'Next',
'otp_label' => 'One-time Password',
'otp_placeholder' => 'e.g. 123456',
'recover_link_title' => 'Use Recovery Code',
'recover_link' => 'Lost your authenticator device? Log in with a Recovery Code.',
'cancel' => 'Cancel'

# Success notifications

'title' => 'All good in the hood.',
'update_personal' => 'Change of personal information was successful.',
'update_password' => 'Change of password was successful.',
'update_government' => 'Change of government email address was successful.'

# Account settings

'title' => 'Account Settings',
'sidebar_title' => 'Settings',
'personal' => 'Personal Information',
'government' => 'Government of Canada Information',
'password' => 'Password',
'two_factor' => 'Two-factor Authentication',
'personal_copy' => 'This information is used to identify you on the platform.',
'required' => 'Required',
'error' => 'This input has an error.',
'first_name_label' => 'First Name',
'last_name_label' => 'Last Name',
'email_label' => 'Username/Email',
'personal_save' => 'Save Personal Information',
'government_copy' => 'This information is used to identify your role within the Government of Canada on the manager and HR advisor portals.',
'government_dept' => 'Current department:',
'no_department' => 'N/A (not in government)',
'one' => 'In order to change your department, you\'ll need to ',
'three' => 'contact Talent Cloud directly',
'five' => 'We require you to get in touch because your department determines how you interact with job posters, applicants, and HR advisers. In order to have this information changed, we need to verify your department independently of the platform.',
'gov_email_label' => 'Government Email',
'government_save' => 'Save Government Information',
'one' => 'You can use this section to change your password. Passwords must contain 1 character from each of the following criteria:',
'two' => 'Lower-case characters (a-z)',
'three' => 'Upper-case characters (A-Z)',
'four' => 'Digits (0-9)',
'five' => 'Non-alphanumeric symbols (%, $, !, etc.)',
'password_label' => 'Current Password',
'new_password_label' => 'New Password',
'confirm_password_label' => 'Confirm New Password',
'password_save' => 'Submit New Password',
```

**Comment by mattejackson** [comment]
2FA EN copy

Even a strong password isn’t enough to protect your account. If you use the same password on different websites, click on hyperlinks in email messages, or download anything on the internet, you are at risk of having your password stolen. And if someone else gets access to your account, they can do all kinds of bad things.

Using two-factor authentication (2FA) adds an extra layer of security when you sign into Talent Cloud. To use 2FA, you’ll have to install an authenticator app that uses the time-based one-time password algorithm standard on a separate device, like your cell phone. Compatible apps include:
- 1Password for iOS, Android, OS X, Windows
- Authy for iOS, Android, Chrome, OS X
- FreeOTP for iOS, Android and Pebble
- Google Authenticator for iOS
- Google Authenticator for Android
- Google Authenticator (port) on Windows Store
- LastPass Authenticator for iOS, Android, OS X
- WindowsMicrosoft Authenticator for Windows Phone

To turn on 2FA, you need to associate your phone (or some other device) with your Talent Cloud account by scanning a QR code. This will give you the ability to generate a one-time password on demand when you log in. Once you use 2FA, you won't have to use it again for another 30 days on that device. (You’ll still need to enter your user name and password.)

**Comment by mattejackson** [comment]
# Use recovery codes

'title' => 'Utiliser un code de récupération',
'return_title' => 'Mot de passe à usage unique.',
'return' => 'Retour au mot de passe à usage unique',
'header' => 'Utiliser un code de récupération ',
'instructions' => 'Entrer un code de récupération. Souvenez-vous, chaque code ne peut être utilisé qu’une fois.',
'form_label' => 'Code de récupération',
'placeholder' =>  'p. ex. 1234abcd-efgh5678',
'submit' => 'Ouverture de session',
'incorrect_code' => 'Mauvais code. Essayer de nouveau.',
'otp_link_title' => 'Mot de passe à usage unique ',
'otp_link' => 'Ouvrir une session avec un mot de passe à usage unique.',

# One-time password

'title' => 'Mot de passe à usage unique',
'return_title' => 'Retour à la page d’accueil.',
'return' => 'Retour à la page d’accueil.',
'header' => 'Entrer un mot de passe à usage unique',
'login' => 'Ouverture de session ',
'next' => 'Suivant',
'otp_label' => 'Mot de passe à usage unique',
'otp_placeholder' => 'p. ex. 123456',
'recover_link_title' => 'Utiliser un code de récupération',
'recover_link' => 'Vous avez perdu votre dispositif d’authentification? Ouvrir une session avec un code de récupération.',
'cancel' => 'Annuler'

# Success notifications

'title' => 'Tout va bien.',
'update_personal' => 'La modification des renseignements personnels a été faite avec succès.',
'update_password' => 'La modification du mot de passe a été faite avec succès.',
'update_government' => 'La modification de l’adresse électronique gouvernementale a été faite avec succès.'

# Account settings

'title' => 'Paramètres du compte',
'sidebar_title' => 'Paramètres',
'personal' => 'Renseignements personnels',
'government' => 'Information du gouvernement du Canada',
'password' => 'Mot de passe',
'two_factor' => 'Authentification à deux facteurs',
'personal_copy' => 'Cette information sert à vous identifier sur la plateforme.',
'required' => 'Renseignements obligatoires',
'error' => 'Cette entrée comporte une erreur.',
'first_name_label' => 'Prénom',
'last_name_label' => 'Nom de famille',
'email_label' => 'Nom d’utilisateur/courriel',
'personal_save' => 'Enregistrer les renseignements personnels',
'government_copy' => 'Ces renseignements servent à déterminer votre rôle au sein du gouvernement du Canada sur les portails des gestionnaires et des conseillers en RH.',
'government_dept' => 'Ministère actuel :',
'no_department' => 'S.O. (non-fonctionnaire)',
'one' => 'Pour changer votre ministère, vous devrez',
'three' => 'communiquer directement avec le Nuage de talents.',
'five' => 'Nous vous demandons de communiquer avec nous parce que votre ministère détermine comment vous interagissez avec les offres d’emploi, les candidats et les conseillers en RH. Pour faire modifier cette information, nous devons vérifier si votre ministère est indépendant de la plateforme.',
'gov_email_label' => 'Courriel gouvernemental',
'government_save' => 'Sauvegarder l’information du gouvernement',
'one' => 'Vous pouvez utiliser cette section pour modifier votre mot de passe. Les mots de passe doivent contenir un caractère tiré de chacun des critères suivants :',
'two' => 'Lettres minuscules (a-z)',
'three' => 'Lettres majuscules (A-Z)',
'four' => 'Chiffres (0-9)',
'five' => 'Symboles non alphanumériques (%, $, !, etc.)',
'password_label' => 'Mot de passe actuel',
'new_password_label' => 'Nouveau mot de passe',
'confirm_password_label' => 'Confirmer le nouveau mot de passe',
'password_save' => 'Soumettre le nouveau mot de passe',

**Comment by mattejackson** [comment]
UPDATED COPY

French Text

'two_factor_description' => 'Two-factor blurb (second paragraph).'

L’utilisation de l’authentification à deux facteurs (A2F) ajoute une couche de sécurité supplémentaire lorsque vous ouvrez une session dans le Nuage de talents. Pour utiliser l’A2F, vous devrez installer une application d’authentification qui utilise l’algorithme de mot de passe à usage unique fondé sur le temps sur un appareil distinct, comme votre téléphone cellulaire.

**Comment by gggrant** [comment]
Added on `feature/add-2fa-support` and `feature/settings-2fa` branches.
