### ISSUE TITLE
Manager - Restrict Manager Account Creation

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#194]
Please name the task using the following information: **Applicant/Manager/Admin/Sitewide - Name**. Assign this task to the appropriate person, give it either a "FED" or "BED" label, and give it the "**Task**" label.

# Description
As it stands, anyone can create a manager account (as a temporary fix, we removed the login button). This should be changed so that the Talent Cloud admins can manage which GCAccounts have access to manager features, whether it's through a request/approval process or a manual flag based on email.

# Required for Completion
Add/remove others as necessary for this specific task.
- [x] Consider/Perform Peer Review
- [x] Push to `master`

**Comment by tristan-orourke** [comment]
Right now, any first-time user will be registered in our database as a jobseeker. This can be changed by modifying the database directly.
