### ISSUE TITLE
All Browsers - Ensure French OpenID Links Point to French GCAccount

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#195]
Please name the task using the following information: **Browser - Name**. Give this issue a "FED" or "BED" label, alongside the "**Bug**" label.

# Description
Ensure that all OpenID links are localized so that they link to the French version of GCAccount when leaving Talent Cloud to log in or edit profile information. 

See "Apply Now" login link on the Job Posters.

**Comment by gobyrne** [comment]
Obsolete after refactor
