### ISSUE TITLE
Bug - Manager portal - inability to delete certain posters

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#1951]
# Description
An error message appears when I tried to delete a job poster (and it happened to more than one job poster, but I was able to delete some). In my case, it happened to job posters id 80, 81, 120.

# Technical Info

**Device:** Surface tablet (TBS network)
**Operating System:** Windows
**Browser:** Chrome

**Device:** Laptop (unfiltered wifi)
**Operating System:** Windows
**Browser:** Chrome

# Steps to Reproduce
Steps to reproduce the behavior. 
1. Go to manager portal "My Job Posters"
2. Click on Delete
3. See error (but I can't tell what triggered it as I was able to delete some job posters, and I couldn't tell how the posters were different)

# Images
![image](https://user-images.githubusercontent.com/44560341/68404410-82b0f980-014c-11ea-9be2-0d406481a50d.png)

- [ ] Regression test written.

**Comment by gobyrne** [comment]
I can confirm that I have such a job on my account right now gray.obyrne@tbs-sct.gc.ca

**Comment by gobyrne** [comment]
@tristan-orourke or was this the one that got fixed?
