### ISSUE TITLE
Bug - LinkedinUrlRule regex needs improvement

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#1952]
# Description
I can't produce a URL that the input will accept. Both applicant/manager profiles.

# Technical Info

**Device:** Desktop
**Operating System:** MacOs
**Browser:** Chrome

Place image attachments here.

![Screen Shot 2019-11-07 at 12.23.27 PM.png](https://images.zenhubusercontent.com/5d9ce8bd5fc4fd0001589e3d/4d13ffcc-e64c-4dd5-8c01-aac6589a4359)

**Comment by Khristophor** [comment]
Looks like we're expecting HTTPS urls, but that could be changed:
`^https:\/\/[a-z]{2,3}\.linkedin\.com\/.*$`

**Comment by gggrant** [comment]
It requires `www` (or any 2-3 character prefix) and `.com` as well.
