### ISSUE TITLE
Spike - Could we ensure we check policy permissions every time CRUD operations happen on models?

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#1959]
# Description
Right now we use middleware to check the Policy on the primary model of a route. But once in a controller or view, we may load other models (explicitly, or through model relationships) or even create/update/delete other models. Is there a way to ensure, through events or relationships, that we only interact with models that Policies allow?

# Images
Place image attachments here.

**Comment by gobyrne** [comment]
The goal of this Spike is to see how hard it would be to set up the code in a way that implements the principle of least privileges. Essentially can we limit all access to specific data in way that requires explicit exceptions to circumvent. Circumventing is absolutely Ok when there's a reason to do so. We're not trying to limit what developers can do, but it could be helpful to them if access to data was clearly limited by roles in the code. It would mean we could worry less about accidentally serving data to users with the wrong role.

The default setup in Laravel (policies applied to routes) is sufficient, but this spike is to see if we can find a way to use it better (or do something slightly different).

**Comment by tristan-orourke** [comment]
@gobyrne I can't find any examples of people doing what we discussed, at least in Laravel. Laravel certainly isn't set up to enable it, and the workarounds I initially considered aren't sufficient. It would involve writing a substantial extension to Laravel ourselves.

I have to recommend sticking with the current approach of using permissions at the route or controller level, not on the data models themselves. 

There is room for us to unit test our permissions, or our routes, more rigorously.

**Comment by tristan-orourke** [comment]
So it turns out to be fairly easy to authorize against a policy for doing any Creates, Updates, or Deletes. Every laravel model emits events before doing one of these actions, and you can listen for them, check the policy, and prevent the operation.
https://laracasts.com/discuss/channels/eloquent/listen-to-any-saveupdatecreate-event-for-any-model

I've started a branch with some experimenting on this: 
https://github.com/GCTC-NTGC/TalentCloud/tree/task/direct-model-permissions

However, I haven't got this method to work for Getting of models. There is a Retrieved event, to match the other ones, but checking the policy in that listenter is causing an error for some reason.

Other concerns:
- If we do get the Retreive check working, we need to figure out a way skip the check the User model is initially loaded as part of Login.
- This method can't distinguish between different kinds of Updates. For example: claiming a job, editing a job, and publishing a job. All these actions update the same model, but require separate permissions. The only solution I can think of right now is to create several different abstracted Models, that all represent data from the same table.

**Comment by Khristophor** [comment]
Part of the reason this happens at the route/controller level is because information required to assess the permission is passed in with the request. The model itself can't know what area of the application the user is attempting to make the action from without somehow handing that information down, which as Tristan mentioned, would require some heavy rewrites.

Tightly coupling the model to the policy/permission feels like the wrong path to go down for me, just because of how Laravel is architected in the first place. Event subscription _might_ be a good alternative but I feel like there will be performance implications having listeners subscribed to every single CRUD event emitted by our main models.
