### ISSUE TITLE
Applicant - Evidence UI

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#198]
Please name the task using the following information: **Applicant/Manager/Admin/Sitewide - Name**. Assign this task to the appropriate person, give it either a "FED" or "BED" label, and give it the "**Task**" label.

# Description
After numerous bouts of user feedback on the evidence UI, we've decided to simplify the process by stacking the skills and providing a fixed contextual menu. The UI should mimic the mockup found below.

# Images

![empty v02](https://user-images.githubusercontent.com/6960386/41546295-47b1d246-72eb-11e8-8204-eebd4e38efd4.png)

# Required for Completion
Add/remove others as necessary for this specific task.
- [x] Run Lighthouse (Chrome Dev Tools)
- [x] Run WAVE Evaluation
- [x] Browser Compatibility Check
- [x] Update Translation Spreadsheet
- [x] Consider/Perform Peer Review
- [x] Push to `master`

**Comment by tristan-orourke** [comment]
Evidence items should be savable individually
When saved, button switches from "Save" to "Saved" (inactive?) and button-green
When content changes, button changes back to "Save"
If content changes and form is no longer complete, remove "complete" classes
When saved, accordion trigger gets "complete" class, sidebar item gets "complete" class
Continue button disabled until all all skill declarations complete
Besides skill declarations, everything can be saved half-complete
Continue button still saves everything

**Comment by gobyrne** [comment]
Someone please click the checkboxes.

**Comment by gggrant** [comment]
Checkboxes clicked

**Comment by gobyrne** [comment]
Obsolete after refactor
