### ISSUE TITLE
Task - Add test database to docker compose

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#2008]
# Description
It would be great to have a test DB to allow running the unit tests that affect application state and not have to reseed afterwards. Alternatively, rewrite the E2E tests so I don't have to reseed afterwards.

# Acceptance criteria
- [ ] Add a second Postgres instance to the docker-compose file
- [ ] Update the `.env.testing` file to use that database

**Comment by gggrant** [comment]
This was implemented via environment variable in phpunit.xml, and should work after creating the `testing` database.

@tristan-orourke ?
