### ISSUE TITLE
[Design] - What should our URLs be?

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2036]
# Design Goal
Our URL for managers ( /manager ) kinda sucks, and we haven't thought carefully about what it should be for the new HR advisor portal. We should make them better! Please suggest some new URLs!

**Comment by nicolsonaitken** [comment]
Ideally it would be nice if there were a single place to login regardless of who you are, no? I'm assuming that's not a thing given we currently have one URL for applicants and another for managers. That being said what I see most commonly used is: app.websiteaddress.com.

See PageCloud (app.pagecloud.com), Hubdoc (app.hubspot.com/login) and HubSpot (app.hubspot.com/login). These are just three tools I commonly use. 

Which would have us at: app.talent.canada.ca and in lieu of that possible managers.talent.canada.ca, advisors.talent.canada.ca and applicants.talent.canada.ca
