### ISSUE TITLE
Bug - Browse Job page - job card - duration info missing

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#2041]
# Description
Duration info is missing on job cards on the browse job page. The info is showing on individual posters.

# Images
Place image attachments here.
![image](https://user-images.githubusercontent.com/44560341/68809210-6f64c900-0639-11ea-8f16-89ffdf120184.png)

- [ ] Regression test written.

**Comment by rositak** [comment]
hi @joshdrink, just want to flag this to you

**Comment by joshdrink** [comment]
Hey Rosita,

I'm having Chris look at this. I'll let you know when things have been
fixed.

Thanks!

*Josh Beveridge*
Digital Product Designer | Concepteur de produits numériques

@joshdrink <https://twitter.com/joshdrink> | https://joshbeveridge.ca/

**Comment by gobyrne** [comment]
@Khristophor @joshdrink Any insights on this?

**Comment by Khristophor** [comment]
It's fixed, awaiting PR merge
