### ISSUE TITLE
Admin - Populate Live Site with Fake "Real" Content for Demo

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#205]
# Description
For the demo, it's important that we have content that looks as though it were real. This includes populating a Hiring Manager's profile, as well as creating 3 different job posters to help provide variety during the demo.

# Required for Completion
Add/remove others as necessary for this specific task.
- [x] Populate Hiring Manager Profile
- [x] Populate 3 Job Posters

**Comment by gggrant** [comment]
Only did 2 posters
