### ISSUE TITLE
All Browsers - Job Application Preview is Broken

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#207]
# Description
When applying to a job, users can reach the preview stage, but receive an error that states "The requested job application does not exist." at which point the preview does not populate with their application information (including profile photo - cat issue).

# Steps to Reproduce
1. Complete a Job Application
2. Submit the Application
3. See the Error

**Comment by gobyrne** [comment]
Obsolete after refactor
