### ISSUE TITLE
[Design] - Applicants, Managers, HR / Notifications

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#2120]
# Design Goal & User Groups
**Please explain the primary goals of this design work.**
Eventually, Talent Cloud will require a common form of notification system to allow for efficient and timely job action completion. This notification system will need to do different things for each user group, but will functionally use the same UI, preferably located in the navigation.

**Please select the users this UI will apply to.**
- [ ] Administrators
- [x] [Applicants](https://github.com/GCTC-NTGC/TalentCloud/issues/1548)
- [x] [Hiring Managers](https://github.com/GCTC-NTGC/TalentCloud/issues/1549)
- [x] [HR Advisers](https://github.com/GCTC-NTGC/TalentCloud/issues/1550)

# Initial Research & Notes
**Please list/link all research performed before this design work began. Include research relevant to insights from team members as well. Don't be afraid to ask for references or documents!**

Related to the navigation redesign: #1551 

The notification system **could** do the following for each group...

Applicants:
- notify them of updates on their applications
- notify them of why they weren't selected for a position in a timely fashion
- notify them of jobs that match their existing skills
- notify them that they've received a new verified credential
- notify them of new features

Managers:
- notify them of new applications
- notify them of new activity and/or comments on a job action from HR
- notify them of a job action's status changing (e.g. from approved to published)
- notify them of new manager features

HR:
- notify them of new activity on their claimed job actions
- notify them of new HR features

## Assumptions
**Please list all assumptions made during your design work. This should include behavioural assumptions made by the team that have no direct research references.**

- we'll want to ensure that each type of notification can be toggled on/off
  - no immediate gut reaction on where this should live, but likely the new account page?
- we might need to also build out an email service for these notifications that can be toggled on and off per notification type, per user

# Design Versions
Each version should contain the following:
- the version number
- a link to the prototype
- a list of all changes made since the last version and why those changes were made
- a screenshot of the new UI
- any research performed on this version, as well as outcomes for the next version

## Version 1

Prototype Link:

### Changes
**Please list all changes made to this version from the last, and indicate why that change was made when appropriate.**

- we added a bulleted list
  - this was done as a result of...
- etc.

### Research/Feedback & Outcomes
**Please include notes, links, images, etc. that are associated with any research performed on this version only. Outline any outcomes required in the next version.**

## Version 2
**Repeat versions as necessary.**

**Comment by Khristophor** [comment]
Turns out Laravel has native notification support: https://laravel.com/docs/6.x/notifications.
This will help out quite a bit with the implementation of this feature, although there's still some complexity around pushing notifications between the server and the frontend. I think the most important thing at this stage is figuring out a "data architecture" for what constitutes a notification, and how notifications are different between user roles.

**Comment by tristan-orourke** [comment]
I don't have much to say that @Khristophor didn't already cover. We need to figure out all the types of notifications we need, and what information each of them needs to capture.

**Comment by tristan-orourke** [comment]
I just realized that I've been conflating Comments (#1532) and Notifications in my head. We _could_ also present each comment as a separate notification, but we wouldn't have to. New comments could create a single "You have new comments" notification. How are comments and notifications intended to interact?

**Comment by Khristophor** [comment]
After doing a bit of reading I sort of assumed a comment would be a separate model (in terms of Laravel architecture), but passed in to a Laravel notification. The example given is:
```php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
}
```
and then sending it
```php
use App\Notifications\InvoicePaid;

$user->notify(new InvoicePaid($invoice));
```
where we could call `new NewActivity($comment, $location);` (terrible naming, I know) or something.

**Comment by joshdrink** [comment]
This is all great! To clarify how I was seeing it in my head:

Comments (generically), and activity on a job poster (e.g. the job was published on Mar 21st 2019) are both TYPES of notifications, but there are other types (as outlined above). On their own, they are their own models.

With this approach, we can make the activity feed outlined in #1763 a filtered list of notifications that contains only comments and activity. Compare that to the eventual notification feed every user will have, which will have an aggregate of ALL notification types, comments and activities included. :)
