### ISSUE TITLE
Feature - All Users / Registration / Captcha

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#2129]
# Description

**Is your feature request related to a problem? Please describe.**

We're starting to see bots crawl our registration and submit fake account information, as well as attempt to inject ads into the site.

**Describe the solution you'd like**

We'd like to add a captcha to the registration form.

# Acceptance criteria
- [ ] Add a captcha
- [ ] Check with @joshdrink to make sure the UI is a-okay
- [ ] Write a test that ensures you can't submit a registration without completing the captcha

**Comment by Khristophor** [comment]
I did a bit of reading and I think I might want to try our own implementation of something like this instead: https://github.com/spatie/laravel-honeypot

Basically the idea is we have some hidden fields included with our form, and if they are filled out and returned to the server, we know it's a spam submission and can disregard it. It seems to be fairly effective against the majority of bots and is unintrusive to users. We can also log "spam" attempts for review in the event they are legitimate somehow.

It's probably more complex than just throwing a captcha on the form, but I think it's a better solution overall. Only questions are around hiding the fields from screen readers and other accessibility tools.

**Comment by joshdrink** [comment]
@Khristophor I'm good with this solution. Hiding things from accessibility tools is pretty straight forward using a combination of CSS and aria.

**Comment by gggrant** [comment]
Confirmed.
