### ISSUE TITLE
Sitewide - Accessibility on Page Load

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#213]
# Description
Ensure that navigating to the top of the page always and automatically occurs when you follow a link to a new page & Accessibility when link is "clicked". Also, nothing is read to the screen reader when link is clicked. Possible fix is setting focus on page load using accessibility API. 

### Grant Note
This is difficult to do with a single page application. I have removed the focus on skip nav link and set the focus to "top of page" element, but it doesn't actually work unless you reload the browser.

Suggest putting a pin in this until we look at moving to multiple pages. Refreshing the browser automatically resets the focus.

# Required for Completion
Add/remove others as necessary for this specific task.
- [x] Browser Compatibility Check
- [x] Consider/Perform Peer Review
- [x] Push to `master`

**Comment by gobyrne** [comment]
It's working pretty well. I think it's fine to leave it like this until breaking apart site into multi-page app.
