### ISSUE TITLE
Feature - All Users / Partner Department Data & Display

### ISSUE THREAD

**Issue by bitliege** [GCTC-NTGC/TalentCloud#2133]
# Description

**Is your feature request related to a problem? Please describe.**

Right now, the list of partner departments on the site has to be updated by a dev in the database, and while this updates the list in most places on the site, it doesn't update it on the FAQ, which results in multiple updates being made by (sometimes) multiple devs to ensure everything is in sync.

**Describe the solution you'd like**

We have an existing admin UI for departments, but it lacks the ability to add them.
Ideally, we'd upgrade this UI to do the following:
- add/edit/delete departments
  - this means the ability to add both english and french names
- check off, per department, whether that department is a Talent Cloud partner
- add both english and french impact statements

Once this work is done, we'd be able to populate the FAQ with this list in both languages, removing the extra step of updating the content manually.

**Describe alternatives you've considered**

@laurenoncoffee mentioned that if it's too complicated to have the partner checkbox described above, the entire list can be partners, and it would be okay to be able to simply delete them from the list.

**Comment by gobyrne** [comment]
Currently there is an admin portal for adding Departments including EN & FR and impact. But this does not update on the FAQ.

**Comment by Khristophor** [comment]
@mnigh some notes from our chat:

- [ ] Add a migration for the departments table to add a boolean column for `partner` (or similar)
- [ ] Update the Department model doc block and `fillable` array
- [ ] Expose the new field in `app/Http/Controllers/Admin/DepartmentCrudController` to the [list](https://backpackforlaravel.com/docs/4.1/crud-operation-list-entries) and [create/update](https://backpackforlaravel.com/docs/4.1/crud-operation-create) views
- [ ] Query the partner departments in `app/Http/Controllers/FaqController` and pass them along to the view (more info about [single action controllers](https://laravel.com/docs/7.x/controllers#single-action-controllers) if you're curious)
- [ ] Replace the Langfile partner departments in the FAQ view with the passed-in list from the controller
