### ISSUE TITLE
Task - Make users aware that cookies are required

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#2165]
# Description
Submitting any form with cookies disabled leads to a 419 error, because a cookie is used to track the session, and session data is used to verify CSRF tokens.

We should an explanation to the 419 error page that they may need to enable cookies. Also, if the TokenMismatchException occurs on the Login, Registration, or Reset Password forms, we can catch the exception and return a form error message explaining the need for cookies.

**Comment by Khristophor** [comment]
Would be nice to flash an error to the form _before_ the user submits the form, notifying them that cookies are required. In addition to adding more information to the 419 error page.

**Comment by gobyrne** [comment]
This ended up being a more specific technology problem. IE on our TBS surface tablets failed, but chrome on the same device works. @yonikid15 could you investigate a little more?

**Comment by yonikid15** [comment]
> This ended up being a more specific technology problem. IE on our TBS surface tablets failed, but chrome on the same device works. @yonikid15 could you investigate a little more?

Will do!
