### ISSUE TITLE
Task - Job Poster - Merge the job_poster_translations table into the job_poster table

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/TalentCloud#2190]
# Description
In #2177 PR there is a requirement for the Admin Portal in the Job Section that has a blocker. The goal is to be able to ONLY search the French or English 'title' in the Job Posters list. However, the `job_poster_translations` are held within it's own table, and (from what I understand) CRUD cannot access it within the [searchLogic](https://backpackforlaravel.com/docs/4.0/crud-columns#custom-search-logic-for-columns) function. 

So, what do you need to do:

- Mimic the setup used in the `skills` table, storing the locale values in JSON format (Using the [spatie/laravel-translatable](https://github.com/spatie/laravel-translatable) package.)
- Must refactor the all places using the job_poster_translations table and replace to use new setup. 

- [ ] This task requires a unit test and refactoring old ones.

# Acceptance criteria
- [ ] Requirement one
- [ ] Requirement two
- [ ] Requirement three

**Comment by gggrant** [comment]
#2273
