### ISSUE TITLE
Task - Admin - Status filter and search by title 

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/TalentCloud#2192]
# Description
Depends on #2190 and #2189

Now that we're starting to have lots of job posters AND demo accounts are creating many more all the time, we need some new ways to sort/filter job posters.

Please make these changes to the table display of job posters:

Page: `JobPosterCrudController.php`
- [ ] Allow filter by Status. 
  - Add a `dropdown` or `select2_multiple` filter.
- [x] change search to ONLY search English and French job poster "Title".
  - Add function to 'searchLogic` attibute to title column.

**Comment by gggrant** [comment]
#2273 will resolve the sort/search.

**Comment by tristan-orourke** [comment]
"Allow filter by Status" is resolved by #2189
