### ISSUE TITLE
Manager - Enhance Workplace Photo Upload

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#224]
# Description
Manages should be able to use Croppie to modify their work environment photos in a similar way to how they crop their profile photos. This task might also include enhancing the Applicant Job Poster to include a lightbox so that photos can be clicked and viewed in full (see Gray about this part).

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Consider/Perform Peer Review
- [ ] Push to `master`

**Comment by tristan-orourke** [comment]
We need to rebuild photo upload from scratch, and there's another story for that.
