### ISSUE TITLE
Task - HR - Comment Feed

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#2261]
# Description
Build a Comment Feed react component. It should be based on the "Job Activity Feed" section the Hr Job Summary template.

It currently only needs to contain the "Submit Comment" piece, and the "Previous Activity". There doesn't need to be the ability to "Mark as Read" yet, or even determine if its new.

Note: "Type of comment" select box should not be visible to Managers, but should be REQUIRED by HR advisers.

Base frontend comment model on Backend model #2238.

# Images
https://joshbeveridge.ca/tc-job-summary/#activity

# Acceptance criteria
- [ ] Storybook story where
   - [ ] Can enter new comment
   - [ ] Can view old comments
   - [ ] submitted comments added to list

**Comment by yonikid15** [comment]
"Type of comment" select box should not be visible to Managers, but should be REQUIRED by HR advisers.

**Comment by tristan-orourke** [comment]
@joshdrink @nicolsonaitken What format would you like the date/timestamp shown on comments to use?

**Comment by tristan-orourke** [comment]
Completed by PR #2495
