### ISSUE TITLE
Spike - How to add Captcha/Honeypot without sacrificing accessibility?

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#2266]
Discussion of captcha and honeypot methods here #2263.

**Comment by gggrant** [comment]
Captcha is not accessible. Recommending this approach for both client/server side honeypot:

## Front-end:

[W3C - Captcha Alternatives and thoughts](https://www.w3.org/WAI/GL/wiki/Captcha_Alternatives_and_thoughts)

 The honeypot alternative described above will satisfy accessibility requirements. Keep in mind:
- If there is proper labeling it can warn screen reader users not to fill it out	
- If there is no warning using aria-label etc.. then it could trap a screen reader user who fills it out not knowing it is a trap. It is likely that spam bots could figure out any warning text for screen reader users.

[Examples of HTML, CSS, JS linked by W3C](https://www.thryv.com/blog/honeypot-technique/) (I doubt that jQuery is necessary)

## Back-end

https://github.com/spatie/laravel-honeypot

**Comment by gggrant** [comment]
> Captcha is not accessible. Recommending this approach for both client/server side honeypot:
> 
> ## Front-end:
> [W3C - Captcha Alternatives and thoughts](https://www.w3.org/WAI/GL/wiki/Captcha_Alternatives_and_thoughts)
> 
> The honeypot alternative described above will satisfy accessibility requirements. Keep in mind:
> 
> * If there is proper labeling it can warn screen reader users not to fill it out
> * If there is no warning using aria-label etc.. then it could trap a screen reader user who fills it out not knowing it is a trap. It is likely that spam bots could figure out any warning text for screen reader users.
> 
> [Examples of HTML, CSS, JS linked by W3C](https://www.thryv.com/blog/honeypot-technique/) (I doubt that jQuery is necessary)
> 
> ## Back-end
> https://github.com/spatie/laravel-honeypot

**Comment by shawnthompson** [comment]
Here's some information we've been working on at ESDC and are almost ready to published.

[Are CAPTCHAs accessible?](https://bati-itao.github.io/example/captcha-accessible-en.html)

**Comment by gobyrne** [comment]
We implemented honeypot and it does seem to be working.
