### ISSUE TITLE
Bug - Errors during application

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2292]
We got a few different errors over the weekend from people who were attempting to build/submit their applications.

**Person 1:**
"In the middle of my application process I was presented with an error.  Not sure how to proceed as the deadline is in 4 1/2 hours!  Please advise."
We know this person did eventually submit their application because we can see them in the list of people who applied, but we don't have any more information. This job is now closed.

**Person 2:**
First was trying to access **talent.canada.ca/en/jobs/118/application/step-01** and was getting 403 Forbidden | nginx.

Afterwards can access talent.canada.ca and log in. Can see the job, but if they click Apply it "will go broken". This person tried 3 different browsers. Eventually this person submitted their application, though we're not sure how (we are following up to try and find out). Job is now closed.

**Person 3:**
Tried to use the "Cloud Platform website" but received several errors then contacted the manager directly. This was the link that was shared: **https://talent.canada.ca/en/jobs/121**. We are following up to see if we can get more details. Job poster is not yet closed.

**Comment by tristan-orourke** [comment]
First discovery: 403 errors are leading to a blank `403 Forbidden | nginx` instead of a more expressive (or at least prettier) custom Talent Cloud error page. Not the root cause, but we should fix that.

Second discovery: Most jobs cause a 403 error if you try to view them after they've closed. That's definitely unintended. Mysteriously, [job #2](https://talent.canada.ca/en/jobs/2) doesn't suffer this issue.

**Comment by gobyrne** [comment]
@tristan More info from Person #3:
- Was able to create account and log in
- Completed fist page (I assume of Application) and clicked "Next"
- They were returned to the same page with no error displayed and there were no missing fields.
- They were not able to advance further

**Comment by gggrant** [comment]
@tristan-orourke how long did you spend on this?

**Comment by tristan-orourke** [comment]
> @tristan-orourke how long did you spend on this?

About 2 days, I think.

**Comment by gggrant** [comment]
Investigated but no clear bugs to discern.
