### ISSUE TITLE
Convert GCTC-NTGC to a GitHub organization

### ISSUE THREAD

**Issue by nschonni** [GCTC-NTGC/TalentCloud#23]
Instructions can be found here https://help.github.com/articles/converting-a-user-into-an-organization/
After that is done, it can be included on https://government.github.com/

**Comment by gobyrne** [comment]
Thanks @nschonni I will do so shortly.

**Comment by gobyrne** [comment]
Converted to Org. Not quite sure how to include on government.github.com
