### ISSUE TITLE
Task - HR - View of Job Poster Builder review page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2303]
# Description
Create a view of the Job Poster Builder review page for HR.

### The following should be different from the Manager View
- (if easy to do) Different steps should not be shown at the top of page. This is not critical though.
- HR commenting should be available on each section (instead of manager commenting)
- The only button that should be shown on the bottom is the "Return to Summary"
- The "Edit Poster" for managers (or "Review Poster" as it should probably be called for HR advisers) button on the Summary page should link here.

### Tests
- [x] This task requires a unit test.

**Comment by gggrant** [comment]
For reference:
The Review page is the last page of the Job Poster Builder
The Preview page is the /job/# page that will eventually become the "live" job poster page
The Summary page is the new summary page for a single job poster that we're building as part of the HR portal epic
The Job List is the page where all of a manager's or HR advisers jobs are listed. This was previously referred to as the dashboard.

**Comment by nicolsonaitken** [comment]
Regarding: _HR commenting should be available on each section (instead of manager commenting)_
See: #2306 as we've created an option where only one commenting widget is being used.
