### ISSUE TITLE
Task - Manager - Add Preview Page to JPB flow

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2305]
# Description

### For reference:
- The **Review** page is the last page of the Job Poster Builder
- The **Preview** page is the /job/# page that will eventually become the "live" job poster page
- The **Summary** page is the new summary page for a single job poster that we're building as part of the HR portal epic
- The **Job List** is the page where all of a manager's or HR advisers jobs are listed. This was previously referred to as the dashboard.

## Task
We want managers to be viewing their job posters with as much context as possible before submitting to HR. For this we want them to submit from the Preview page instead of the Review or Job List page. We're essentially forcing an extra step for before they submit.

- On the Preview page, display a button with the exact same text and functionality as the "Send to HR for review" on the Review page at the bottom of the page. This will be the new place where managers have to go to "send to HR"
- On the Review page replace the "Send to HR for review" with a button that says "Preview and Send to HR" (Voir l'aperçu et trasmettre aux RH). It should now simply link to the Preview page.
- Same thing for the Job List, the "Send to HR" button should go to the Preview page. (eventually this will also be on the summary page, but that part is maybe not built yet)

**Comment by tristan-orourke** [comment]
I'm guessing we'll want a link on the Preview that goes back to the Job Builder. Where would that go?

**Comment by joshdrink** [comment]
@tristan-orourke Gray can correct me if I'm wrong, but it would be ideal if it took them to the last step they were working on. So for example, if they quit the JPB at step 3, and go to the Preview manually, and click that new button, it should take them to step 3. If they finish the JPB and it takes them to the Preview that way (as described above) it should take them back to the Review page.

**Comment by tristan-orourke** [comment]
Two possible approaches:

1. Rebuild the Preview page in react. That will make the back-and-forth between the Review and Preview nice and fast, and will allow us to reuse the current validation logic. However, we'll have to either use the react page everywhere people view jobs, or else maintain two versions of the page (twig and react).

2. Recreate the "valid for review" logic on the backend. Simply link between the react Review page and twig Preview page.

**Comment by gobyrne** [comment]
This is more work then I think it's worth at this time. Might look at just always changing statuses from the Summary page instead.

It's a consistent experience that way at least, but more mistakes might slip through.

**Comment by gobyrne** [comment]
Yes, going with Summary page to change statuses
