### ISSUE TITLE
Feature - Manager/HR - Add comment components to "Review" page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2306]
# Description

**Is your feature request related to a problem? Please describe.**
Managers and HR need the ability to leave comments on various sections of the Job Poster. We want to add this functionality all on the Review page (last step of JPB).

**Please select the users this UI will apply to.**
- [ ] Administrators
- [ ] [Applicants](https://github.com/GCTC-NTGC/TalentCloud/issues/1548)
- [x] [Hiring Managers](https://github.com/GCTC-NTGC/TalentCloud/issues/1549)
- [x] [HR Advisers](https://github.com/GCTC-NTGC/TalentCloud/issues/1550)

**Describe alternatives you've considered**
Adding comment section on each page of the JPB was decided against for now. Those pages are "busy" already and we could need the sections on the Review page anyway because HR doesn't have access to the rest.

## Assumptions
- HRs and Managers will have the option to choose which section of the Job Poster they want to comment on using a pre-populated drop-down list.
- HRs and Managers will be required to Leave a comment.
- HRs will have the option to Select a comment type whereas Managers do not have this option.
- Once comments are made, users will have the ability to show/hide comments making it more usable. 

**Select a section options include:**
- Generic
- Job Page Heading
- Basic Information 
- Impact
- Tasks
- Criteria
- Language Requirements
- Environment & Culture

**Select a comment type options include:**
- Question
- Recommended Action 
- Required Action

## Prototype
[XD Wireframe](https://xd.adobe.com/view/0a305716-fa34-4cf7-5a66-7133eccfc755-7c01/)

- [ ] This task is complex and needs acceptance criteria.

**Comment by nicolsonaitken** [comment]
The purpose of this feature is to allow HR Advisors to comment on the Review Poster page without significant changes to the interface. 

Once comments are made, users will have the ability to show/hide comments making it more the display more manageable.

![2306 - Add comments component.jpg](https://images.zenhubusercontent.com/5612862d638e718c995d8ae9/054de67a-88df-4caa-88a7-025955950a60)
