### ISSUE TITLE
Task - HR - Add view of Screening plan builder for HR advisers

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2307]
# Description
Give HR advisers View AND Edit access to the screening plan builders for all posters they have access to. This should be linked to from the Summary page.

See [prototype](https://xd.adobe.com/view/49be05bb-5fd3-458b-69cf-fc44a3c09c3d-3f8f/)

- [ ] This task requires a unit test.
- [ ] This task is complex and needs acceptance criteria.

**Comment by nicolsonaitken** [comment]
See [wireframe](https://xd.adobe.com/view/49be05bb-5fd3-458b-69cf-fc44a3c09c3d-3f8f/)
