### ISSUE TITLE
Task - Manager/HR - Add one comment component to screening plan builder page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2309]
# Description
Managers and HR need the ability to leave comments on various sections of the Screening Plan Builder. 

**Please select the users this UI will apply to.**
- [ ] Administrators
- [ ] [Applicants](https://github.com/GCTC-NTGC/TalentCloud/issues/1548)
- [x] [Hiring Managers](https://github.com/GCTC-NTGC/TalentCloud/issues/1549)
- [x] [HR Advisers](https://github.com/GCTC-NTGC/TalentCloud/issues/1550)

## Assumptions
- HRs and Managers will have the option to choose which section of the Screening Plan Builder they want to comment on using a pre-populated drop-down list.
- HRs and Managers will be required to Leave a comment.
- HRs will have the option to Select a comment type whereas Managers do not have this option.
- Once comments are made, users will have the ability to show/hide comments making it more usable. 

**Select a section options include:**
- Generic
- Assessment Plan Builder
- Assessment Plan Summary
- Ratings Guide Builder

**Select a comment type options include:**
- Question
- Recommended Action 
- Required Action

## Prototype
[XD Wireframe](https://xd.adobe.com/view/49be05bb-5fd3-458b-69cf-fc44a3c09c3d-3f8f/)

**Comment by nicolsonaitken** [comment]
The purpose of this feature is to allow HR Advisors to comment on the Screening Plan without significant changes to the interface as much of this will be changed shortly. With that in mind this version keeps everything relatively simple and easy to use.

Once comments are made, users will have the ability to show/hide comments making it more the display more manageable.

![2309 - Add one comment component 2.jpg](https://images.zenhubusercontent.com/5612862d638e718c995d8ae9/2b9df75e-b632-4504-bcce-a48124d84573)
