### ISSUE TITLE
Task - HR - Give HR access to list of applicants

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2312]
# Description

- Give HR access to view the list of candidates (currently **/manager/jobs/#/applications**).
- HR should not be able to change any of the fields (the select inputs)
- This should be linked to from the Summary page

**Comment by tristan-orourke** [comment]
HR managers need to be able to see which category managers have given to applicants (screened in, screened out, etc) but don't need to see the Note.

**Comment by tristan-orourke** [comment]
We've already given HR access to applicants & applications, this must be a duplicate.
