### ISSUE TITLE
Copy - Applicant - Application Submission does not explain that submission is final

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#2317]
# Description
Once an application has been submitted, its impossible to edit. (It may be possible to delete it and restart.) This should perhaps be better communicated to users.

# Changes
Enter the approved copy here:

| English  | French |
| ------- | ------- |
| Content | Content |

- [ ] Copy provided in English and French.

**Comment by gobyrne** [comment]
Josh is working on a design for this

**Comment by nicolsonaitken** [comment]
Closing as Duplicate to: [Design] - Applicants / Teaser page / Applicant Timeline#2806

**Comment by nicolsonaitken** [comment]
**Duplicate:** Task - Applicant - Post-application Experience#2651
