### ISSUE TITLE
Task - HR - Translation for HR portal

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2323]
# Description
Extract new copy, send to translation, input translated text back in.

**Comment by gggrant** [comment]
# Job Summary
```
'menu_title' => 'On This Page:',
'summary_title' => 'Job Summary',
'tools_title' => 'Poster & Screening Tools',
'activity_title' => 'Activity',
'status_label' => 'Current Status:',
'under_review' => 'This job action is currently in the review process. This means that the poster is being edited and discussed by the manager and HR advisors to get it to a point where it can be published. When it\'s ready, the next step is translation.',
'manager_label' => 'Hiring Manager:',
'applicants_label' => 'Applicants:',
'not_applicable' => 'N/A',
'other_title' => 'Other Details',
'other_text' => 'View information like Priority Clearance #, HR Advisors, etc.',
'expand_hidden' => 'Click to view.',
'managers_label' => 'HR Managers:',
'process_label' => 'PSC Process #:',
'priority_label' => 'Priority Clearance #:',
'created_label' => 'Date Created:',
'published_label' => 'Date Published:',
'closed_label' => 'Date Closed:',
'send_manager_button' => 'Send to Manager',
'send_translation_button' => 'Send for Translation',
'approve_button' => 'Approve for Publishing',
'relinquish_button' => 'Relinquish',
'edit_poster_button' => 'Edit Poster',
'view_poster_button' => 'View Live Poster',
'screening_plan_button' => 'View Screening Plan',
'view_applicants_button' => 'View Applicants',
'edit_poster_icon' => 'An icon depicting a paper form with a pencil, indicating that it is being edited.',
'view_poster_icon' => 'An icon depicting a completed document, representing viewing a completed job poster.',
'screening_plan_icon' => 'An icon depicting a hand making a selection from four different options, representing a manager screening through applicants.',
'view_applicants_icon' => 'An icon depicting four users placed in a pie chart, representing the ability to view the applicants who have applied to this job process.',
'flat_icons' => 'Icon supplied by Flat Icons.'
```

**Comment by gggrant** [comment]
## Job Index
```
"hrJobIndex.departmentPlaceholder": "[Department loading]",
"hrJobIndex.jobTitleMissing": "Title Missing",
"hrJobIndex.managerLoading": "Loading...",
"hrJobIndex.preview": "Preview Poster",
"hrJobIndex.reviewDraft": "Review Draft",
"hrJobIndex.viewActivity": "View Activity",
"hrJobIndex.viewScreeningPlan": "View Assessment Plan",
"hrJobIndex.viewSummary": "View Summary",
"hrPortal.jobPageIndex.clickToView": "Click to view...",
"hrPortal.jobPageIndex.completedJobsHeader": "My Completed Job Actions",
"hrPortal.jobPageIndex.hideAccordion": "Hide",
"hrPortal.jobPageIndex.jobActionsEmpty": "Claim a job below!",
"hrPortal.jobPageIndex.jobActionsHeader": "My Job Actions",
"hrPortal.jobPageIndex.jobActionsMessage": "This is a list of all job actions you are currently participating in. Looking for an older job? Check the 'My Completed Job Actions'  section below your active jobs.",
"hrPortal.jobPageIndex.noJobsCompleted": "No jobs completed yet!",
"hrPortal.jobPageIndex.preDepartmentName": "All Jobs in",
"hrPortal.jobPageIndex.showAccordion": "Show",
"hrPortal.jobPageIndex.unclaimedJobsEmpty": "There are currently no active jobs available.",
"hrPortal.jobPageIndex.unclaimedJobsMessage": "This is the list of all active job actions in your department. From  here you can 'claim' a job, which will move it into your jobs list  above and allow you to begin working with the hiring manager on  finding the best talent possible. If you claim a job by accident, no fear, for you can click into the job summary and remove yourself  using the 'Remove Myself From This Job' button.",
"jobStatus.approved": "Approved",
"jobStatus.closed": "Closed",
"jobStatus.complete": "Complete",
"jobStatus.draft": "Draft",
"jobStatus.open": "Open",
"jobStatus.review": "In Review",
"openJobCard.claimJob": "Claim This Job",
"openJobCard.createdAt": "Created: ",
"openJobCard.hiringManager": "Hiring Managers: ",
"openJobCard.hrAdvisors": "HR Advisors: ",
"openJobCard.unclaimed": "Unclaimed",
```

**Comment by mattejackson** [comment]
'menu_title' => 'Sur cette page :',
'summary_title' => 'Résumé de l’emploi ',
'tools_title' => 'Avis d’offre d’emploi et outils de présélection ',
'activity_title' => 'Activité ',
'status_label' => 'Statut actuel :',
'under_review' => 'La présente mesure d’emploi en est au stade du processus d’examen. L’avis d’emploi est donc en cours de révision et fait l’objet de discussions entre le gestionnaire et les conseillers en RH pour faire en sorte que l’avis puisse être publié. Une fois prêt, l’avis passe à l’étape suivante, soit la traduction.',
'manager_label' => 'Gestionnaire d’embauche :',
'applicants_label' => 'Candidats :',
'not_applicable' => 'S.O.',
'other_title' => 'Autres détails',
'other_text' => 'Afficher les autres renseignements comme le numéro d’autorisation en matière de priorité, les conseillers en RH et autres.',
'expand_hidden' => 'Cliquez pour afficher.',
'managers_label' => 'Gestionnaires des RH :',
'process_label' => 'Numéro du processus de la CFP :',
'priority_label' => 'Numéro d’autorisation en matière de priorité :',
'created_label' => 'Date de création :',
'published_label' => 'Date de publication :',
'closed_label' => 'Date de clôture :',
'send_manager_button' => 'Envoyer au gestionnaire',
'send_translation_button' => 'Envoyer aux fins de traduction',
'approve_button' => 'Approuver aux fins de publication',
'relinquish_button' => 'Renoncer',
'edit_poster_button' => 'Modifier l’avis d’emploi',
'view_poster_button' => 'Afficher l’avis d’emploi en ligne ',
'screening_plan_button' => 'Afficher le plan de présélection ',
'view_applicants_button' => 'Afficher les candidats ',
'edit_poster_icon' => 'Une icône représentant un formulaire papier avec un crayon indique que le document est en cours de révision.',
'view_poster_icon' => 'Une icône représentant un document terminé indique que l’affichage d’un avis d’emploi achevé est en cours.',
'screening_plan_icon' => 'Une icône représentant une main en train de faire un choix parmi quatre options indique que la présélection des candidats par un gestionnaire est en cours.',
'view_applicants_icon' => 'Une icône représentant quatre utilisateurs dans un diagramme circulaire indique la capacité d’afficher les candidats qui participent au processus d’emploi.',
'flat_icons' => 'Icône fournie par Flat Icons'


"hrJobIndex.departmentPlaceholder": " [Chargement du ministère]",
"hrJobIndex.jobTitleMissing": "Titre manquant ",
"hrJobIndex.managerLoading": "Chargement...",
"hrJobIndex.preview": "Prévisualiser l’avis d’emploi ",
"hrJobIndex.reviewDraft": "Réviser l’ébauche ",
"hrJobIndex.viewActivity": "Afficher l’activité ",
"hrJobIndex.viewScreeningPlan": "Afficher le plan d’évaluation ",
"hrJobIndex.viewSummary": "Afficher le résumé ",
"hrPortal.jobPageIndex.clickToView": "Cliquer pour afficher...",
"hrPortal.jobPageIndex.completedJobsHeader": " Mes mesures d’emploi achevées ",
"hrPortal.jobPageIndex.hideAccordion": " Masquer ",
"hrPortal.jobPageIndex.jobActionsEmpty": "Réclamer un emploi ci-dessous!",
"hrPortal.jobPageIndex.jobActionsHeader": "Mes mesures d’emploi achevée",
"hrPortal.jobPageIndex.jobActionsMessage": "Voici une liste de toutes les mesures d’emploi auxquelles vous participez actuellement. Vous cherchez une ancienne offre d’emploi? Cochez la section « Mes mesures d’emploi achevées » sous vos offres d’emploi actives.",
"hrPortal.jobPageIndex.noJobsCompleted": "Aucune offre d’emploi achevée à l’heure actuelle!",
"hrPortal.jobPageIndex.preDepartmentName": "Toutes les offres d’emploi dans",
"hrPortal.jobPageIndex.showAccordion": "Afficher ",
"hrPortal.jobPageIndex.unclaimedJobsEmpty": "Il n’y a actuellement aucune offre d’emploi active disponible.",
"hrPortal.jobPageIndex.unclaimedJobsMessage": "Voici la liste de toutes les mesures actives dans votre ministère. À partir de ce point, vous pouvez « réclamer » un emploi qui sera transféré dans votre liste d’emploi ci-dessus, ce qui vous permettra de commencer à collaborer avec le gestionnaire d’embauche pour trouver le meilleur talent possible. Si vous réclamez un emploi par erreur, ne craignez rien, car vous pouvez cliquer sur le résumé de l’emploi et retirer votre nom au moyen du bouton « Me retirer de l’offre d’emploi ».",
"jobStatus.approved": "Approuvé",
"jobStatus.closed": "Fermé ",
"jobStatus.complete": "Achevé ",
"jobStatus.draft": "Ébauche",
"jobStatus.open": "Ouvert ",
"jobStatus.review": "En cours de révision",
"openJobCard.claimJob": "Réclamer cet emploi",
"openJobCard.createdAt": "Date de création :",
"openJobCard.hiringManager": "Gestionnaires d’embauche :",
"openJobCard.hrAdvisors": "Conseillers en RH :",
"openJobCard.unclaimed": "Non réclamé",
