### ISSUE TITLE
Manager - Profile Field Updates

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#233]
# Description
The attached document has a list of update fields required on the manager profiles. These fields should then be reflected on the applicant facing manager profiles as well.

# Files
[manager profile form - TC May 2018.docx](https://github.com/GCTC-NTGC/TalentCloud/files/2141657/manager.profile.form.-.TC.May.2018.docx)

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Consider/Perform Peer Review
- [ ] Push to `master`

**Comment by gobyrne** [comment]
My leadership style and management values
--
What I expect from my employees
My approach to employee learning and development

**Comment by gobyrne** [comment]
My leadership style and management values
What I expect from my employees
My approach to employee learning and development


My career journey so far
My learning path
A bit about me outside work

**Comment by gobyrne** [comment]
Completed in refactor
