### ISSUE TITLE
Feature - Manager/HR - Activity Feed

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2333]
# Description

**Is your feature request related to a problem? Please describe.**
We want managers and HR to have a clear record of all the things that happen as part of the staffing process. We also want them to be able to see what's changed

**Describe the solution you'd like**
Various actions should create "activity" items that get displayed along-side comments on the comment/activity feed for HR and Managers.

Here is an incomplete list of all the "activities" that should show up on the feed. Each one should probably be prioritized separately in the backlog.
https://docs.google.com/spreadsheets/d/1uo0DieU-JJo9_0cwxcSsKq-xu1Qyku-2vYntFLnakB0/edit?usp=sharing

# Images
[XD Wireframe (WIP)](https://xd.adobe.com/view/615dc331-0ab5-48bd-6c69-c7b9ae6a1ae2-176c/)

- [x] This task requires a unit test.

**Comment by gobyrne** [comment]
Nic to flush this out with designs and more info in the spreadsheet.

**Comment by nicolsonaitken** [comment]
How are we going to handle a situation where a user is making on-going changes and is saving regularly. For example, if a user is "word-smithing" and Impact statement and saves the same page 10 times in 20 minutes. We don't want that activity to show up each and every time within the Activity Feed. 

Is there a way to include a time threshold to make sure this doesn't occur or any other alternative?
