### ISSUE TITLE
Bug - After the manager has "screened-in" a candidate that was originally under "optional consideration" should be moved into "under consideration"

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#2345]
# Description
Managers have mentioned that when a "screen-in" candidates remain under "optional consideration", they could miss them for further assessment.

More information to follow...

# Steps to Reproduce
Steps to reproduce the behavior. Example:

# Images
Place image attachments here.

- [ ] Regression test written.

**Comment by tristan-orourke** [comment]
@gobyrne Can you weigh in on this? "Optional Consideration" is for non-citizens and those who don't meet the criteria. Our original business logic doesn't allow for these candidates to be moved to "Under consideration". Do you want this to change?

**Comment by gobyrne** [comment]
Yes, @tristan-orourke that's precisely what we want.
