### ISSUE TITLE
[Design] - Managers, HR / Disabled View Profile Link

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#2362]
# Design Goal & User Groups
**Please explain the primary goals of this design work.**
Managers currently open the profile of each and every applicant but since most applicants don't actually fill out the profile the waste time opening and then closing the the links over-and-over again. Disabling the View Profile link for applicants who do not fill one out will allow managers to get through this section quicker and with less frustration. 

**Please select the users this UI will apply to.**

- [ ] Administrators
- [ ] [Applicants](https://github.com/GCTC-NTGC/TalentCloud/issues/1548)
- [x] [Hiring Managers](https://github.com/GCTC-NTGC/TalentCloud/issues/1549)
- [x] [HR Advisers](https://github.com/GCTC-NTGC/TalentCloud/issues/1550)

## Assumptions
**Please list all assumptions made during your design work. This should include behavioural assumptions made by the team that have no direct research references.**

- We assumed that the UI can correctly determine when a user hasn't filled out the profile. Currently, there are instances in which the UI reads _The applicant hasn't answered any questions_ for the entire page and other instances in which the UI lists all of the questions and then includes a note reading _The applicant has not answered this profile question_.

### Screenshot
![image](https://user-images.githubusercontent.com/5738959/70912128-4ab99380-1fe1-11ea-90db-105a4eb3e066.png)

### Research/Feedback & Outcomes
Version 1 reads *No profile provided* and Version 2 is simply blank. Since technically managers cannot use it to assess the candidates we've selected Version 3 as it is the most subtle indicator that a profile is not available while achieving the intended goal. 

## Version 3 FINAL VERSION
![image](https://user-images.githubusercontent.com/5738959/70912636-58bbe400-1fe2-11ea-8ba9-cf4c71bfc842.png)

**Comment by gobyrne** [comment]
Which one is Version 3? Is the heading of the last section mislabeled @nicolsonaitken ?

**Comment by nicolsonaitken** [comment]
This is Version 3
![image](https://user-images.githubusercontent.com/5738959/71817495-06f00200-3054-11ea-90a7-f74b1573f12d.png)
