### ISSUE TITLE
Bug - Word counter language

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#2368]
# Description
Before entering any information within a text area there is a note that reads: _Start typing your answer above_. I am currently 87 words and 502 characters into my description and the note still reads _Start typing your answer above_ and nothing has changed on the circle icon. 

# Technical Info

**Device:** Laptop
**Operating System:** MacOs
**Browser:** Chrome Version 79.0.3945.79 (Official Build) (64-bit)

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Go to My Skills
2. Click on How I acquired this skill 
3. See error

# Images
Place image attachments here.
![image](https://user-images.githubusercontent.com/5738959/70918836-c02b6100-1fed-11ea-8a46-035ab6eaf8e5.png)

- [ ] Regression test written.

**Comment by tristan-orourke** [comment]
Already fixed.
