### ISSUE TITLE
Laravel - API - Reorganize API to to be REST compliant 

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#243]
# Description
Decide on new API calls. Set up routes on backend, and change ajax urls on frontend to match.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] User testing on site
- [ ] Test all calls in insomnia
- [ ] Consider/Perform Peer Review
- [ ] Push to `master`

**Comment by tristan-orourke** [comment]
We don't have an API anymore. If we do, we'll build it to be RESTful from the ground up.
