### ISSUE TITLE
Bug - Create a New Poster not working

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#2450]
# Description
Currently when logged in as a Manager (Gray.OByrne@tbs-sct.gc.ca) and when logged into the demo account (nic@madgeeklove.com) the Create a new Job Poster link opens up a new page with only the header and the footer displayed. 

There are no contents within the page. 

# Technical Info

**Device:** Laptop
**Operating System:** MacOs, etc.
**Browser:** Chrome

# Steps to Reproduce
Steps to reproduce the behaviour. Example:
1. Login to manager or demo account
2. Click on My Job Posters
3. Click Create a New Poster

# Images
![image](https://user-images.githubusercontent.com/5738959/71367903-61796080-2574-11ea-8abb-ed24b099820e.png)

@gggrant 
![image](https://user-images.githubusercontent.com/22059495/71369711-9e942180-2579-11ea-809a-f47cabeade12.png)

- [ ] Regression test written.

**Comment by gggrant** [comment]
Weird deployment, fixed.
