### ISSUE TITLE
Bug - Admin Portal / Create poster for other managers - 404 Error

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#2492]
# Description
From the admin portal, managers page, I receive a 404 error when I click "Create Job Poster" for a manager. 

# Technical Info

**Device:** Surface
**Operating System:** Windows
**Browser:** Chrome

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Go to Admin Portal - Managers
2. Click on 'Create Job Poster' for any manager
3. See error

# Images
I couldn't upload the screenshot... But here's the hyperlink that gave the 404 Error: https://talent.canada.ca/admin/jobs/create/as-manager/4477

- [ ] Regression test written.

**Comment by gobyrne** [comment]
Does not happen for all managers. Might be related to ones who haven't filled in their "government email" and department.

**Comment by gobyrne** [comment]
Ok, confirmed bug for some managers but not all. Rosita or Gray can give some examples.

**Comment by gobyrne** [comment]
This bug could be as old as the JPB and it's not entirely blocking at this point, since managers can now use JPB to create their own job poster.

**Comment by gobyrne** [comment]
And there's an additional problem. For the managers that you don't get an error page 4, the job poster seems to get created under the wrong manager. This causes particular problems if the profile info gets edited in step 0 of the JPB
