### ISSUE TITLE
Admin - Security AC-05 - Separation of Duties

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#255]
# Description
(A)	The organization:
(a)	Separates [Assignment: organization-defined duties of individuals];
(b)	Documents separation of duties of individuals; and 
(c)	Defines information system access authorizations to support separation of duties.

# Required for Completion
- [ ] Documentation of completeness

**Comment by gobyrne** [comment]
@tristan-orourke , can you please point to the place(s) in the code where this is handled?
