### ISSUE TITLE
Admin - Security AC-06 - Least Privilege

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#256]
# Description
(A)        The organization employs the principle of least privilege, allowing only authorized accesses for users (or processes acting on behalf of users) which are necessary to accomplish assigned tasks in accordance with organizational missions and business functions.

# Required for Completion
- [ ] Documentation

**Comment by gobyrne** [comment]
Tristan, can you please point to the place(s) in the code where this is handled?

**Comment by gggrant** [comment]
Our understanding is this task involves setting up Laravel gates, and the still outstanding AC-06(10) is for testing and documenting.
