### ISSUE TITLE
Admin - Security AU-03 - Content of Audit Records

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#259]
# Description
(A)	The information system generates audit records containing information that establishes what type of event occurred, when the event occurred, where the event occurred, the source of the event, the outcome of the event, and the identity of any individuals or subjects associated with the event.

# Required for Completion
- [ ] Documentation

**Comment by gobyrne** [comment]
For now we do not think any events in Talent Cloud need special handling for audit records.
