### ISSUE TITLE
Admin - Security CP-02 - Contingency Plan

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#263]
# Description
Document what to do in case it hits the fan

(A)        The organization develops a contingency plan for the information system that:
(a)        Identifies essential missions and business functions and associated contingency requirements;
(b)        Provides recovery objectives, restoration priorities, and metrics;
(c)        Addresses contingency roles, responsibilities, and assigned individuals with contact information;
(d)        Addresses maintaining essential missions and business functions despite an information system disruption, compromise, or failure; 
(e)        Addresses eventual, full information system restoration without deterioration of the security safeguards originally planned and implemented; and
(f)        Is reviewed and approved by [Assignment: organization-defined personnel or roles].
(B)        The organization distributes copies of the contingency plan to [Assignment: organization-defined key contingency personnel (identified by name and/or by role) and organizational elements].
(C)        The organization coordinates contingency planning activities with incident handling activities.
(D)        The organization reviews the contingency plan for the information system [Assignment: organization-defined frequency].
(E)        The organization updates the contingency plan to address changes to the organization, information system, or environment of operation and problems encountered during contingency plan implementation, execution, or testing.
(F)        The organization communicates contingency plan changes to [Assignment: organization-defined key contingency personnel (identified by name and/or by role) and organizational elements].
(G)        The organization protects the contingency plan from unauthorized disclosure and modification.

# Required for Completion
- [ ] Documentation

**Comment by gobyrne** [comment]
How will the business continue without the IT.
