### ISSUE TITLE
Admin - Security IA-02/8 - Identification/Authentication

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#264]
# Description
(A)        The information system uniquely identifies and authenticates organizational users (or processes acting on behalf of organizational users).

# Required for Completion
- [ ] Documentation

**Comment by gobyrne** [comment]
This feature is inherited through GCaccoutn (OpenID). Tristan, please document here (or link to the code) where this is implemented.

**Comment by gobyrne** [comment]
Add tests to ensure it's operating as expected.
