### ISSUE TITLE
Admin - Security PL-04 - Rules of Behaviour

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#265]
# Description
update GCcollab terms/conditions - assign to Jerbo

(A)	The organization establishes and makes readily available to individuals requiring access to the information system the rules that describe their responsibilities and expected behaviour with regard to information and information system usage.
(B)	The organization receives a signed acknowledgment from such individuals, indicating that they have read, understood, and agreed to abide by the rules of behaviour, before authorizing access to information and the information system.
(C)	The organization reviews and updates the rules of behaviour [Assignment: organization-defined frequency].
(D)	The organization requires individuals who have signed a previous version of the rules of behaviour to read and resign when the rules of behaviour are revised/updated.

# Required for Completion
- [ ] Documentation

**Comment by gobyrne** [comment]
The terms and conditions for creating a GCaccount are outlined here: https://gccollab.ca/terms

@Jerryescandon please work with Digital Collaboration Division (GCtools) to update the terms and conditions to reflect Talent Cloud and the broader digital workspace.

**Comment by gobyrne** [comment]
Ok, now that we've moved away from GCcollab log in. @Jerryescandon please talk to me about this.

**Comment by gobyrne** [comment]
How not to be a tool on this platform @laurenoncoffee
