### ISSUE TITLE
Admin - Security RA-05 - Vulnerability Scanning

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#266]
# Description
look at implementing Snyk - Grant

(A)	The organization scans for vulnerabilities in the information system and hosted applications [Assignment: organization-defined frequency and/or randomly in accordance with organization-defined process] and when new vulnerabilities potentially affecting the system/applications are identified and reported.
(B)	The organization employs vulnerability scanning tools and techniques that facilitate interoperability among tools and automate parts of the vulnerability management process by using standards for:
(a)	Enumerating platforms, software flaws, and improper configurations;
(b)	Formatting checklists and test procedures; and
(c)	Measuring vulnerability impact.
(C)	The organization analyzes vulnerability scan reports and results from security control assessments.
(D)	The organization remediates legitimate vulnerabilities [Assignment: organization-defined response times] in accordance with an organizational assessment of risk.
(E)	The organization shares information obtained from the vulnerability scanning process and security control assessments with [Assignment: organization-defined personnel or roles] to help eliminate similar vulnerabilities in other information systems (i.e., systemic weaknesses or deficiencies).

# Required for Completion
- [ ] Documentation

**Comment by ptd-tbs** [comment]
Recommend the use of OWASP Zap as well - https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project.

**Comment by gobyrne** [comment]
GitHub also does this by default.
