### ISSUE TITLE
Admin - Security SA-11 - Developer Security Testing/Evaluation

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#267]
# Description
testing

(A)        The organization requires the developer of the information system, system component, or information system service to create and implement a security assessment plan.
(B)        The organization requires the developer of the information system, system component, or information system service to perform [Selection (one or more): unit; integration; system; regression] testing/evaluation at [Assignment: organization-defined depth and coverage].
(C)        The organization requires the developer of the information system, system component, or information system service to produce evidence of the execution of the security assessment plan and the results of the security testing/evaluation.
(D)        The organization requires the developer of the information system, system component, or information system service to implement a verifiable flaw remediation process.
(E)        The organization requires the developer of the information system, system component, or information system service to correct flaws identified during security testing/evaluation.

# Required for Completion
- [ ] Documentation

**Comment by gobyrne** [comment]
This is a bigger task around implementing automated testing. @gggrant can you please document anything that we are currently doing here? In addition, we will need to discuss our plans for the future.
