### ISSUE TITLE
Bug - Registration - You Lose Work on Error

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#2688]
# Description
When submitting a registration form, if the form errors for any reason, the first & name fields, and the gov department fields are reset.

# Technical Info

**Device:** Desktop
**Operating System:** Government Windows
**Browser:** IE11

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Click on register
2. Fill out the fields
3. Submit the registration with an invalid password
4. See problem

## It would also be nice if we could add padding to the bottom of the errors when they pop up :)

- [ ] Regression test written.

**Comment by yonikid15** [comment]
This was resolved. Except for the padding :p, but I'll just add it to another branch I fixed a bug on.
