### ISSUE TITLE
Admin - Security SA-11(4) - Manual Code Review

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#269]
# Description
enforce peer review of code

# Required for Completion
- [x] Enforce code review on GitHub
- [ ] Documentation

**Comment by gobyrne** [comment]
This has been implemented for the master branch. As we create branches for production environments, this will need to be added to those as well.

**Comment by gobyrne** [comment]
A good way to verify this is to go and try to change the "readme" file directly from the web interface.
https://github.com/GCTC-NTGC/TalentCloud/edit/master/README.md

![image](https://user-images.githubusercontent.com/2494551/44097884-cb537d82-9fac-11e8-9b82-599f0b0c25f1.png)

**Comment by gobyrne** [comment]
Also implemented for Dev branch
