### ISSUE TITLE
Admin - Security SI-02 - Flaw Remediation

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#270]
# Description
process for issue creation, tracking and resolution

(A)	The organization identifies, reports, and corrects information system flaws.
(B)	The organization tests software and firmware updates related to flaw remediation for effectiveness and potential side effects before installation.
(C)	The organization installs security-relevant software and firmware updates within [Assignment: organization-defined time period] of the release of the updates.
(D)	The organization incorporates flaw remediation into the organizational configuration management process.

# Required for Completion
- [ ] Documentation

**Comment by gobyrne** [comment]
Develop procedures for this.
