### ISSUE TITLE
Feature - HR/Manager - Improving department for HR and Manager

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#2712]
# Description

The current flow for HR where they can enter their department after being upgraded doesn't really guard Privacy properly. We can handle this on the admin side for now, but we will need a different flow at some point.

I think the best flow would simply be to require the department to be in place before the account gets upgraded.

I think this might also be tied to us duplicating the department property across manager and HR. More basically though, we need a better way for Admins to set the department. Ideally in the same place that admins upgrade their User account. But that again would require the department field be on the user and not manager or HR

**Comment by gobyrne** [comment]
@tristan-orourke and @nicolsonaitken I'm looking for your input here.

**Comment by tristan-orourke** [comment]
I think you nailed the right solution already. Tying department to the user model, and making it editable in the same way admins change users roles.

**Comment by gggrant** [comment]
Resolved by #2846
