### ISSUE TITLE
HR & Managers / Resources Template

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#2740]
# Design Goal & User Groups
There are instances in which Talent Cloud needs to supply notes and/or documentation to Hiring Managers and HR Advisors. Currently HR Concierge will email that content directly. Given that this information is quite valuable to the process and can be reused, we'd like to add a new page for downloadable Resources and Tools. 

Documentation such as PDF, Word Docs, Excel spreed sheets can be added to this page and made available for download to all Hiring Managers and HR Advisors. 

**Prototype Link:**
https://xd.adobe.com/view/08e309ba-31b1-430e-748d-931544afc6fa-7ed2/

**Please select the users this UI will apply to.**
- [x] Administrators
- [ ] [Applicants](https://github.com/GCTC-NTGC/TalentCloud/issues/1548)
- [x] [Hiring Managers](https://github.com/GCTC-NTGC/TalentCloud/issues/1549)
- [x] [HR Advisers](https://github.com/GCTC-NTGC/TalentCloud/issues/1550)

**Comment by joshdrink** [comment]
I've created a branch at `feature/resources` with this UI in the temporary routes area.
