### ISSUE TITLE
Manager / Prompt manager to screen candidates

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#2743]
# Design Goal & User Groups
We have observed that top candidates tend to drop out within 2 weeks of poster closing, we'd like to get managers start screening their candidates as soon as possible.

Rosita currently emails them to prompt them, but moving forward would like to automate this. prompt them directly within the app. 

So dev item for this issue:

1.  Send automated email to managers when a job poster closes. @nicolsonaitken please provide copy (translated ideally). Talent cloud should be CC'ed. Also CC any HR advisors that have claimed the job.

**Please select the users this UI will apply to.**
- [ ] Administrators
- [ ] [Applicants](https://github.com/GCTC-NTGC/TalentCloud/issues/1548)
- [x] [Hiring Managers](https://github.com/GCTC-NTGC/TalentCloud/issues/1549)
- [ ] [HR Advisers](https://github.com/GCTC-NTGC/TalentCloud/issues/1550)

**Comment by gobyrne** [comment]
@tristan-orourke @gggrant do you want to create a dev issue for this, or just re purpose this one?

**Comment by gggrant** [comment]
I thought repurposing / adding dev deliverables them was fine.
