### ISSUE TITLE
[Design] - Applicants / Prompt / Confirmation of next steps upon completion of applications

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#2744]
# Design Goal & User Groups
Upon completion of an application, candidates are looking for more information on what to expect next. This is an opportunity for us to let them know that their applications will be reviewed after the job poster closes and that they will hear from us whether they are hired or not.

**Please select the users this UI will apply to.**
- [ ] Administrators
- [x] [Applicants](https://github.com/GCTC-NTGC/TalentCloud/issues/1548)
- [ ] [Hiring Managers](https://github.com/GCTC-NTGC/TalentCloud/issues/1549)
- [ ] [HR Advisers](https://github.com/GCTC-NTGC/TalentCloud/issues/1550)

# Initial Research & Notes

- This is issue comes directly from Talent Cloud applicants.

## Assumptions
**Please list all assumptions made during your design work. This should include behavioural assumptions made by the team that have no direct research references.**

- we assumed that...
- etc.

# Design Versions
Each version should contain the following:
- the version number
- a link to the prototype
- a list of all changes made since the last version and why those changes were made
- a screenshot of the new UI
- any research performed on this version, as well as outcomes for the next version

## Version 1

Prototype Link:

### Changes
**Please list all changes made to this version from the last, and indicate why that change was made when appropriate.**

- we added a bulleted list
  - this was done as a result of...
- etc.

### Research/Feedback & Outcomes
**Please include notes, links, images, etc. that are associated with any research performed on this version only. Outline any outcomes required in the next version.**

## Version 2
**Repeat versions as necessary.**

**Comment by gobyrne** [comment]
@nicolsonaitken , Josh has just some work on improving what is presented when applicants complete the job application. Could you please compare notes with him?

**Comment by gobyrne** [comment]
Done in new timeline application
