### ISSUE TITLE
Feature - Applicant - Endpoint to request applicant skills 

### ISSUE THREAD

**Issue by vid** [GCTC-NTGC/TalentCloud#2784]
# Description

Add an endpoint that allows downloading an applicant's complete skill data in JSON format. This endpoint must support complete skill records as they evolve. The purpose is to enable creating parallel Verifiable Credential versions of these skills to enable aligning with other platforms.

This end point could be available only for synthetic/testing data in a development environment, as long as it's fully representative of production data. It should be usable without using the front end, eg from a `curl` request.

- [x] This task requires a unit test.
- [ ] This task is complex and needs acceptance criteria.

**Comment by gobyrne** [comment]
@vid Unfortunately this is going to have to be on hold for a bit. The next major release we do will completely re-build how applicants attach evidence to their skills. We are scheduled to start working on that re-build on Feb 12. I'll add this to the Epic so it's included in the planning.

**Comment by gobyrne** [comment]
David said maybe don't do this. I'll chat with him about it.
