### ISSUE TITLE
Bug - Applicant Profile - LinkedIn URL

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#2807]
# Description
An applicant user reported not being able to add their LinkedIn Profile. 

Testing on my own account, I was able to save this link "https://www.linkedin.com/in/rosita-kwok-759696150/" but unable to do so if I remove "https://". However, the error message didn't specify what was wrong with the link. 

So this may require a new error message instead of bug fix.

# Technical Info

**Device:** Surface
**Operating System:** Windows
**Browser:** Chrome

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Copy and paste the full LinkedIn profile URL on 'My Profile'
2. Click 'save changes'
3. Remove "https://"
4. Click 'save changes'
5. See error

# Images
![image](https://user-images.githubusercontent.com/44560341/73669908-4838f900-4676-11ea-9f71-02fd552de05e.png)

- [ ] Regression test written.

**Comment by gobyrne** [comment]
This section is getting archive with new timeline application. So closing this issue.
