### ISSUE TITLE
Create Models and Tables for new Applicant Experiences

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#2835]
There are several models for different kinds of experience that need to be created.

Like our existing Degree and Course models, these experience models must have a polymorphic one-to-many relationship with Applicants or Applications.

We should create an experience_type table at the same time, to store id and localized names of each experience type.

Here are the designs for the forms that show all the data being collected for the experience items.

WORK EXPERIENCE
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/e3866535-cf4a-4b65-97a5-6f5e99743366)

PERSONAL
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/723e88c9-3448-4ad6-8014-224efd2872f9)

EDUCATION
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/4e6deb67-fc80-41f6-9691-97b4ee023035)

AWARDS
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/83a8f547-bc3c-4ceb-9d57-277224167173)

COMMUNITY
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/03b80650-c56a-4080-a289-4883e8f70215)

**EDUCATION DROPDOWN**
*Type of education*
Diploma
Bachelors Degree
Masters Degree
Phd
Post Doctoral Fellowship
Online Course
Certification
Other

*Status*
Successful Completion (Credential Awarded)
Successful Completion (No Credential Awarded)
In Progress
Audited
Did not complete

**AWARDS DROPDOWN**
*Awarded to*
Me
My Team
My Project
My Organization

*Award Scope*
International
National
Provincial
Local
Community
Organizational
Sub-Organizational (Branch or Division)

**Comment by gobyrne** [comment]
Ok, added the finalized forms that show all the data collected for these experience types. As far as I know this should be ready to Dev, let me know if anything is missing.

**Comment by gggrant** [comment]
```
'en' => 'Complete (credential awarded)',
'fr' => ''

'en' => 'Complete (no credential awarded)',
'fr' => ''

'en' => 'Post-doctoral Fellowship',
'fr' => ''

'en' => 'My team',
'fr' => ''

'en' => 'My project',
'fr' => ''

'en' => 'My organization',
'fr' => ''

'en' => 'Myself',
'fr' => ''

'en' => 'Local',
'fr' => ''

'en' => 'Organizational',
'fr' => ''

'en' => 'Sub-organizational (branch or division)',
'fr' => ''
```
