### ISSUE TITLE
Add "yes I meet Education" checkbox to basic info

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#2840]
~The application (but not the profile) needs to include a reference to Education Justification type.~
The basic info page of the application needs a new checkbox that says "Yes, I meet the education requirements" without any explanation of how.

[Wireframe](https://xd.adobe.com/view/4ac43ee7-a919-4397-6888-ce98019603f7-3cf5/)

**Comment by yonikid15** [comment]
Closing this since it's included in #2857
