### ISSUE TITLE
Applicant - Make "How do managers review your application?" step fully functional

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#2863]
# Description
This step has no interaction with the application itself, so this only entails navigation to other pages (SAVE AND EXIT or CONTINUE).

# Images
https://xd.adobe.com/view/a678f763-f7b7-43ca-740a-89359cbe42f1-d049/screen/82e0f4c8-16e9-40c1-901c-b2e9a2a2551d/

**Comment by tristan-orourke** [comment]
I think we removed this page from the design.
