### ISSUE TITLE
Bug - HR / Manager portal - GC email requirement

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#2873]
# Description
When an HR advisor who already has a manager account tries to log-in to the HR advisor account for the first time, they are asked to provide a government email. Because they have already provide that information for the manager account, however, they would receive an error message when trying to enter their email again. We currently work around it but asking the HR advisor to add a "+" to their email address.

- [ ] Regression test written.

**Comment by gobyrne** [comment]
Jerbo and Jasmita also encountered this during a user testing session.

**Comment by gobyrne** [comment]
Jasmita, could you please try and write out steps for reproducibility?
