### ISSUE TITLE
Sitewide - Improve work environment photo database structure

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#292]
# Description
The current database structure is confusing and fragile. Make it better, and get uploads + viewing working.

# Required for Completion
- [ ] update database/db/dumps with modified database
- [ ] Test uploading on Manager edit profile, test viewing a job poster
- [ ] Consider/Perform Peer Review
- [ ] Push to `dev`

**Comment by gobyrne** [comment]
When work environment photos are added, this will be reviewed. No need for this to have it's own issue.
