### ISSUE TITLE
Bug - HR - Settings page missing the user's Department title

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#2930]
# Description
An HR Advisor viewing their settings page is not shown what department they belong to

# Technical Info

**Device:** Desktop
**Operating System:** Windows
**Browser:** Chrome

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Log in to HR advisor portal
2. Click on Settings in the nav menu

# Images
![image.png](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/848c6513-3cc8-4046-b89e-1892ddae1ede)

**Comment by gggrant** [comment]
Will be fixed by #2764.
