### ISSUE TITLE
Bug - 500 Error being show within the Admin Portal / Screening Questions

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#2958]
# Description
A 500 Error is being displayed within the Admin Portal when users are clicking on questions. This bug is High Priority given we are looking to post a job this Friday that might need to add screening questions. 

_There are questions in the screening plan but need to confirm with manager._

# Steps to Reproduce
Steps to reproduce the behaviour. Example:

1. Sign in to Admin Portal
2. Click on Questions on any Job Poster
3. See 500 Error

- [ ] Regression test written.

**Comment by gggrant** [comment]
Resolved by #2883

**Comment by nicolsonaitken** [comment]
There are still some issues with this, issue. 

1. The admin question isn't being saved.
2. The description field has been made required but, it is not a required field. 
3. The question cannot be deleted. 
4. Any new questions are not appearing. 

In addition, no error message was shown when the required field was left blank. Granted this may not be an issue if there's no required field but it might be an issue elsewhere so I thought, I'd mention it.

**Comment by gggrant** [comment]
Resolved.
