### ISSUE TITLE
Bug - Manager Activity Bad Gateway and Names missing

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/TalentCloud#2972]
# Description

Names dont load in activity feed on a job summary after comments have been left by either myself(manager) or my hr advisor. Also sometimes get a 502 error, which I believe it's related to this.

I dont know how to reproduce, but happens very often and it rarely doesnt happen.

# Technical Info

**Device:** Mobile, Desktop, Laptop
**Operating System:** iOS, Android, Windows, MacOs, etc.
**Browser:** Chrome, Firefox, IE11, etc.

# Steps to Reproduce
Steps to reproduce the behavior. Example:

# Images
![image](https://user-images.githubusercontent.com/16977254/75074335-6fdaee80-54c9-11ea-8946-76d26c467653.png)

![image](https://user-images.githubusercontent.com/16977254/75074611-07404180-54ca-11ea-8587-9a7c58e352a5.png)

- [ ] Regression test written.

**Comment by tristan-orourke** [comment]
This seems to be caused by the request timing out, due to checking permissions on thousands of users individually.

**Comment by gggrant** [comment]
Whoopsie.
