### ISSUE TITLE
Emergency Response Landing Page with Jobs

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3150]
# Description
A separate landing page that explains the purpose and process of the emergency response talent search, *and* displays our Emergency Response job cards.

Jobs will be separated into streams, with potentially many jobs within a stream representing different specialties and/or skill levels. Some kind of filtering will be necessary when presenting so many job cards on one page. This likely means building this page in React, instead of reusing the twig-based ui of our existing job index page.

**Comment by gobyrne** [comment]
@joshdrink thinks he might be able to do the required Javascript himself inside twig templates. So might not require React rebuild.

**Comment by joshdrink** [comment]
@gobyrne @tristan-orourke I didn't say quite that, just that I could do some of the filtering with custom JavaScript to save the devs time. The page will still need to be Reactified so that jobs are populated, etc.

**Comment by tristan-orourke** [comment]
I would only reccomend using react if we need it for interactivity (ie filtering). Populating job info with twig is easy.

**Comment by gobyrne** [comment]
Making this dependent on the "hide" story. It doesn't really make sense, but I really want to make sure this doesn't go live without the correct hidding.
