### ISSUE TITLE
Emergency Response - remove requirement that job must be closed before reviewing applicants

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3151]
# Description
Conceptually, our emergency response job posters have no specific close date. Therefore it must be possible to review and sort applicants right away, while still accepting further applications.

If it is easy to allow this only for the new Emergency Response department, we should do so. However, it would be acceptable to turn off this requirement for all jobs temporarily, in which case we should create another git Issue reminding us to turn it back on.

**Comment by gobyrne** [comment]
We just need to keep in mind the currently live job poster. I think Rosita is looking to into closing that one ealier.
