### ISSUE TITLE
Emergency Response - Create a special Emergency Response department

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3153]
# Description
Departments can be created in the Admin portal, but for now there is still some language that must be added by devs (do a search for classificationId in react code; I know an entry needs to be added for Education Requirements at least).

We will use this department to filter jobs on the Emergency Response landing page, hide certain pieces of the job poster, and possibly add certain fields to the application.

**Comment by gobyrne** [comment]
Thanks Tristan, good catch.

**Comment by gobyrne** [comment]
I think i've done this?

**Comment by gobyrne** [comment]
Classification is separate and Managers can override the education language in the JPB, so as long as having it blank doesn't crash anything, it should be ok.

**Comment by tristan-orourke** [comment]
For the record, we've gone with "Strategic Talent Response"

**Comment by tristan-orourke** [comment]
I think I got Departments and Classifications mixed up. Looks like adding the new Dept in the admin portal is all that's required!
