### ISSUE TITLE
Emergency Response - confirm current public service status, classification and level, and DG-level approval on Application

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3156]
# Description
Applicants must be able to indicate DG-level approval (even if we confirm this later through HR) and confirm current public service status, classification and level on the application.

We can collect this information through Manager-specified questions, which requires no additional dev work but will make it difficult to sort by this info when assessing applicants. Alternatively, we can add new fields to the Basic Info page of the application (optionally only appearing for jobs in the Emergency Response dept) to make this info easily accessible on the sorting page.

This decision still needs to be made, based on how useful we think it will be to have this info easily accessible during sorting.

**Comment by tristan-orourke** [comment]
@gobyrne This issue still needs some decisions made before we can start.

**Comment by tristan-orourke** [comment]
@gobyrne It sounds like we're okay with using long-form questions for this?

**Comment by gobyrne** [comment]
Yes! Only thing I think we need is for HR advisors to be able to indicate if they have contacted and gotten approval from a DG that their employee can be moved.

**Comment by gobyrne** [comment]
I don't think the applicant can indicated by themselves that "approval" has been given. I think the HR advisors will want in by direct email from the DG.

**Comment by tristan-orourke** [comment]
Is that something HR can track in the Note associated with each applicant?

**Comment by tristan-orourke** [comment]
Replaced with #3165
