### ISSUE TITLE
Emergency Response - Applicant sorting

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3157]
#Description
We need more options for sorting applicants from the Manager/HR view. Currently there are "Still In, Still Thinking, and Screened Out". We want to add "Ready to Allocate, Allocated, and Not Currently Available". We also want to add a new "Departments" Select Input to the applicant card. This will be used for sub-sorting within categories.

In future builds we may add new categories (instead of "Under consideration", "no longer under consideration" also add "Ready to Allocate"and "Allocated") to this page.

Acceptance Criteria:
- Change copy: "Screened Out" to "Not Qualified". (flag French so we don't forget to translated it)
- Add "Ready to Allocate" to the "Decision" select input. Selecting this should move people to the "Under consideration" category if they are not already there.
- Add "Allocated" to the "Decision" select input. Selecting this should move people to the "No longer under consideration" category FOR ALL JOB POSTERS in the "Response" department. Essentially this is a global change for the applicant so their status should also be changed to "Allocated" in the other job posters (streams). This need to be confirmed with a modal: Mark as "Not Currently Available"<u><i><strong><span class="extra strong"> FOR ALL STREAMS </u></i></strong></span></dragon>. Previously, we were putting these in "Allocated" for all streams, but that doesn't work well because we will end up double counting the persons when we try to measure "how many people have been sent to each department". I think that marking them as "Not currently available" instead solves theissue.
- Add "Not Currently Available" to the "Decision" select input. Selecting this should move people to the "No longer under consideration" category FOR ALL JOB POSTERS in the "Response" department. Essentially this is a global change for the applicant so their status should also be changed to "Not Currently Available" in the other job posters (streams). This need to be confirmed with a modal: "Mark as Not Currently Available<u><i><strong><span class="extra strong"> FOR ALL STREAMS </u></i></strong></span></dragon>. In the future we will create a new category for "Not Currently Available".
- Add a new Select input to the the applicant card. The select options should be the list of departments in our database. This select input should be used to sub-sort all groups of applicants. For example, applicants that are marked as "Allocated" should be grouped together by department. The goal of this feature is so we can quickly count how many people have been allocated to each department if required. Not super necessary, but might be nice to confirm this with a modal as well.

**Comment by gobyrne** [comment]
@tristan-orourke A separate not system that's always visible might be better than re-purposing the existing one if it's a similar amount of work. Would mean that we would have to change the existing one to say "additional notes".

**Comment by tristan-orourke** [comment]
@gobyrne What would you want to see in a new system that's different from just using notes?

**Comment by gobyrne** [comment]
@tristan-orourke we've just been talking about using notes so much, it might make sense to have more capacity for it. One smaller space that is visible and we can use for sorting (as discussed). Then a bigger place we can throw whatever info in.

2 separate note locations is low priority though, so only if it's relatively easy.

**Comment by gobyrne** [comment]
We also need to display the "No longer available" status for individuals and it needs to be Editable by manager/HR.

**Comment by tristan-orourke** [comment]
I've got a separate issue for "No longer available".

> One smaller space that is visible and we can use for sorting (as discussed). Then a bigger place we can throw whatever info in.
For this, I honestly just recommend putting the the stuff you need visible in the first line of the note. Then add an empty line before whatever else you want to store.

**Comment by gobyrne** [comment]
@tristan-orourke Ok, I've done a re-work of the requirements for this. Could you take a look at it and break it up into the other issue you created as you see fit? All the stuff listed here (unless otherwise specified) would need to be there before the sorting tool is viable for the response.

**Comment by tristan-orourke** [comment]
@gobyrne You did a good job of detailing all the acceptance criteria here, so I'm deleting the other issue and leaving it all grouped together here. I'll up the points appropriately.

**Comment by gobyrne** [comment]
@Khristophor, just changed the reqs for setting someone to "Allocated".

**Comment by tristan-orourke** [comment]
This was closed with #3315
