### ISSUE TITLE
Emergency Response - Changes to Job Posters in the Emergency Response dept

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3159]
# Description
We should build a new twig template for the Job Poster that's only used for our new department.

We want to hide certain pieces of the job poster if they're in our new Emergency Response department.

This includes:
- Poster close date
- job start date
- duration
- language level
- security requirement
- classification
- more?

Additionally, there will some extra text we need to add (eg "You must be a current government employee"), and the various field values (department, duration, security, language, classification) should be overridden and replaced with "Various".

See the prototype for details:
https://xd.adobe.com/view/e966ee5a-d99c-44ef-6df5-51548178b473-9f57/screen/dafc479a-33bc-487c-aeb3-418012c7bd83/Talent-Cloud-Job-Poster-1?fullscreen

**Comment by tristan-orourke** [comment]
@gobyrne I'll need your help confirming everything we want  to hide.

**Comment by gobyrne** [comment]
Looking at the job poster now and it looks like we should hide everything in the basic info section. Missing from your list above:

- Location
- Remote Work Allowed/Not Allowed
- Salary Range (for sure)
- Education section
- Language Requirements Section
- Maybe the whole Team Culture section... will depend on what we here about the "needs" of departments though.

**Comment by Jerryescandon** [comment]
Link to prototype:
https://xd.adobe.com/view/3f21a885-7176-4329-7b17-8142b1939365-4910/

Its still very rough, will refine over the next day

**Comment by tristan-orourke** [comment]
https://xd.adobe.com/view/e966ee5a-d99c-44ef-6df5-51548178b473-9f57/screen/dafc479a-33bc-487c-aeb3-418012c7bd83/Talent-Cloud-Job-Poster-1?fullscreen
