### ISSUE TITLE
Emergency Response - Dedicated FAQ page (low priority)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3162]
# Description
We will need another dedicated FAQ page, with details about the Talent Cloud talent coordination effort.

We can build this as a simple page of static content.

**Comment by tristan-orourke** [comment]
@gobyrne You're in charge of assembling copy for this.

**Comment by gobyrne** [comment]
@tristan-orourke noted. For now let's proceed without it though. I'm not sure how much we will actually build for it.

**Comment by tristan-orourke** [comment]
Already done
