### ISSUE TITLE
Emergency Response - New fields for Job Posters

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3163]
# Description
We've decided we need to add three new fields to the job poster, to enable useful filtering. Each of these fields will have a corresponding lookup table. The lookup tables must be editable in the Admin portal, and the new job fields must also be editable in the Admin portal.

These fields are:
- Stream
- Stream subcategory (we will avoid setting up a data hierarchy between streams and their subcategories)
- Skill level (eg Senior, Junior)

**Comment by tristan-orourke** [comment]
@gobyrne @joshdrink Lets get a list of these values (streams, subcategories, and levels) added to this issue ASAP. We'll make them editable in the admin portal, but initializing what we can will save time.

**Comment by gobyrne** [comment]
@tristan-orourke I think we might only need the high level stream for displaying the job posters. The others could potentially be handled just in the text of the Job Poster. However, streams are likely to get added (maybe renamed) over the course of time, so a flexible implementation might be best.

**Comment by gobyrne** [comment]
@Jerryescandon please add your updated wireframe that shows what the job poster should look like.

**Comment by Jerryescandon** [comment]
I have added a button upper right to switch between old poster with notes, and what the new poster should look like.

https://xd.adobe.com/view/3f21a885-7176-4329-7b17-8142b1939365-4910/
