### ISSUE TITLE
Emergency Response - Add new default questions

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#3165]
# Description
Add a new set of default questions (copy to come from Lauren) that only apply to the new Department. Can conditionally add alongside the existing default logic.

**Comment by Khristophor** [comment]
Here's the relevant code that adds existing defaults:
https://github.com/GCTC-NTGC/TalentCloud/blob/dev/app/Http/Controllers/JobController.php#L394-L427

**Comment by Khristophor** [comment]
We'll need some way to differentiate the existing defaults from the new Department defaults, and load them correctly.

**Comment by tristan-orourke** [comment]
The questions: https://docs.google.com/document/d/1eSULGm-yFmilAD1zk9g8KIWG9NBN6MRPdSD_A0-Fy60/edit#heading=h.i1s0gepi5rhx
