### ISSUE TITLE
Emergency Response - Hide unimportant parts of applicant profile (low priority)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3166]
# Description
To make the applicant experience as simple as possible, we'd like to hide unnecessary parts of the applicant profile. This aligns with our long term goal of replacing most of the current profile with the applicant timeline.

This requires further decisions on what exactly is unnecessary (definitely the Profile Questions).

**Comment by gobyrne** [comment]
Let's go with Just the applicant profile questions for now. Lauren suggested references and work samples as well, but let's worry about those seperately.

**Comment by gobyrne** [comment]
Josh has rebuilt the profile. We will put a new issue for that.
