### ISSUE TITLE
Bug - questions being repeated in application for /response

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#3368]
# Description
Some questions on step 1 of the application for the response site are being repeated. For example, the "What is your current director’s name and email? (We’ll need approval that you can be loaned to another team for a bit to help out.)" question is repeated twice. I found this for the following jobs:

- Administrative Support for Senior Management - Senior Level
- Application Development - Software Developer - Intermediate Level
- Application Development - Web Programming/Java - Intermediate Level

# Technical Info

**Device:** Mobile, Desktop, Laptop
**Operating System:** iOS, Android, Windows, MacOs, etc.
**Browser:** Chrome, Firefox, IE11, etc.

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Login on https://talent.canada.ca/en/response.
2. Click on any of the jobs mentioned above.
3. Click on "Apply Now

# Images
<img width="705" alt="Screen Shot 2020-04-02 at 9 50 43 AM" src="https://user-images.githubusercontent.com/38079220/78257119-6e88e280-74c7-11ea-9d20-19709cca6489.png">

<img width="731" alt="Screen Shot 2020-04-02 at 9 51 14 AM" src="https://user-images.githubusercontent.com/38079220/78257174-7fd1ef00-74c7-11ea-94ba-9e4ebc587646.png">

**Comment by gobyrne** [comment]
Gray discussed this with Tristan and created #3387 to fix it.
