### ISSUE TITLE
Developer - Move audit logs to separate log file

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#345]
# Description
Audit logs are currently saved to storage/logs/laravel.log which is the same file as regular laravel errors are logged (@tristan-orourke please confirm). Would be best if these were separate to make them easier to analyse.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by gggrant** [comment]
Deemed unnecessary.
