### ISSUE TITLE
Refactor - make password validation rule

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#346]
# Description
Password validation should all reference a common rule instead of copy-and-pasting a confusing regex.

**Comment by Djama613** [comment]
found these resources for the task, will use them on current confusing regexs and test.

https://stackoverflow.com/questions/15753279/password-validation-with-multiple-rules

https://stackoverflow.com/questions/31539727/laravel-password-validation-rule
