### ISSUE TITLE
Bug - Switching languages doesn't save information from the initial 

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#3655]
# Description
Within the manager portal, when creating a new job poster, If you start in English and switch to French, it doesn’t save information and starts a new poster. In addition, switching languages seems to take you to the first page regardless of what page you are actually on. 

# Technical Info
This is a byproduct of having part of the page using client side routing, and the header being server side rendered. The url for the language selection will be whatever the last server-side rendered page was (in this case, the first step of the builder).

# Steps to Reproduce
Steps to reproduce the behaviour. Example:
See attached video.

[Manager Bug.mov.zip](https://github.com/GCTC-NTGC/TalentCloud/files/4624374/Manager.Bug.mov.zip)

# Images
Place image attachments here.

- [ ] Regression test written.

**Comment by gobyrne** [comment]
This only happens before you save on the first step... so it's no a big deal.
