### ISSUE TITLE
Bug - Somehow, multiple copies of Skill Declarations are being saved

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3662]
# Description
I just attempted to complete a Talent Reserve application in my dev environment. By the time I got to the confirmation page, I had multiple skill declarations saved for all of the required skills. Attempting to submit the application now suggests checking your profile for duplicate skills, but this is particularly galling on a Talent Reserve application, where your profile is not shown in the nav menu.

**Comment by tristan-orourke** [comment]
I suspect this might happen when you try to save a skill when you're above the word limit.

**Comment by yonikid15** [comment]
@tristan-orourke Hey when get a chance today can you let me know if you still able to reproduce this error. Also #3696 and #3751
