### ISSUE TITLE
Bug - Admin unable to view Application and Applicant

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3696]
# Description
An admin is unable to view an application or application profile linked from the Applicant Sorting screen.

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Log in to admin portal.
2. Use the jobs panel to find the id of a Strategic Talent Response job.
3. Go to the job's summary page by directly entering the url: /manager/jobs/{id}
4. Click View Applications
5. Click View Applicant or View Profile for a single application.

# Images
Place image attachments here.

- [ ] Regression test written.

**Comment by gobyrne** [comment]
Let's ask if it's still a problem

**Comment by tristan-orourke** [comment]
I can't reproduce this, and I reported it.
