### ISSUE TITLE
Bug - Applicant Sorting page broken on IE

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3697]
# Description
The applicant sorting page of a Strategic Response job is empty when viewed on Internet Explorer. There is likely a polyfill missing used in the react code.

**Comment by yonikid15** [comment]
Moving this to Talent Reserve

**Comment by yonikid15** [comment]
Issue moved to [GCTC-NTGC/TalentReserve #13](https://github.com/GCTC-NTGC/TalentReserve/issues/13) via [**ZenHub**](https://www.zenhub.com/)
