### ISSUE TITLE
Bug - Manager - Length of Job Term appears incorrectly in Job Builder in IE

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3751]
# Description
The Length of Term appears inccorectly in the preview modal of the Details step of the Job Builder, when viewed in IE.

# Technical Info

**Device:** Desktop
**Operating System:** Windows 10
**Browser:** IE11

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Go to manager portal
2. Go to Jobs
3. Create new job
4. Continue in English
5. Fill in Details page
6. Click Save & Preview, see the error

# Images
![image.png](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/b77fbc1b-cb08-4e37-8c52-3110948fc7c1)

**Comment by yonikid15** [comment]
I wasn't able to reproduce this error either @tristan-orourke.

**Comment by yonikid15** [comment]
Still can't reproduce this error, so I'm going to close it.
