### ISSUE TITLE
Manager - Application view for submitted applications

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#378]
# Description
We need a way to view what job applications have been submitted to a job.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by gggrant** [comment]
Resolved by #773 (and several iterations before). This is very dated.
