### ISSUE TITLE
Applicant/Manager - Second input for "impact" on job posters

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#381]
# Description
Add a second field for impact on the job poster creator. (Add user story)

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by joshdrink** [comment]
@tristan-orourke Ready for you as well! Right under the original impact textarea.
