### ISSUE TITLE
Applicant - Application progress bar doesn't update

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#382]
# Description
The red Xs in the application do not change to check marks even when you have filled everything out on the application.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by gggrant** [comment]
Separate from the recent fix related to skills. Refers to the top bar Steps 1-5
