### ISSUE TITLE
Bug - Manager Portal - Direct to Applicant Portal after registration

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#3841]
# Description
After registering for a new account on the manager portal, users are being directed to the applicant portal, which confused some users. Can they be redirected to the manager homepage, their profile page, or the job poster page (may need to ask a few users to see what makes sense)?

- [ ] Regression test written.

**Comment by mnigh** [comment]
@tristan-orourke I was unable to reproduce the behaviour specified. The current behaviour is such that after registering for a new account on the manager portal, a user is re-directed to the manager portal. From what I can tell, this is handled in the RegisterController by the method [`redirectTo`](https://github.com/GCTC-NTGC/TalentCloud/blob/dev/app/Http/Controllers/Auth/RegisterController.php#L42) which is called in the method [`registered`](https://github.com/GCTC-NTGC/TalentCloud/blob/dev/app/Http/Controllers/Auth/RegisterController.php#L242-L245).
