### ISSUE TITLE
Task - Update Laravel to 8.x

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#3865]
# Description
Laravel 7 released March 3, 2020. According to the [upgrade guide](https://laravel.com/docs/7.x/upgrade) it shouldn't be too bad to migrate from 6.x

And now 8 is out!

**Comment by gggrant** [comment]
Iceboxing this for now. Intend to upgrade Laravel in tandem with the Azure pipeline because of the PHP 7.3 requirement and associated environment / server changes.
