### ISSUE TITLE
Manager - Remote work field in manager portal

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#389]
# Description
There is currently no input field for remote work on the job poster creator or manager profile. One should be added to the Job Poster. We used to have this on the Work Environment and not the job poster, but would like to change that.

**Comment by joshdrink** [comment]
@tristan-orourke Ready for your side of things! We'll want to collaborate on making sure when someone goes back to edit their job poster that the checkbox is populated accordingly (I just didn't know what variable to check for). Also, if you're looking for it, it's in the location section!
