### ISSUE TITLE
Bug - Application - Saving on skill pages causes error if Job has no criteria

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#391]
# Description
Trying to save on step 3 or 4 of the application causes an error if the Job has no accompanying criteria.

# Steps to Reproduce
1. Create a job with no criteria
2. Navigate to application
3. Get to step 3
4. Click Save and Continue
5. See error

# Images
Place image attachments (wireframes, etc.) here.
![image](https://user-images.githubusercontent.com/4313717/47116901-ef4f1280-d230-11e8-88bf-7dc714bd1075.png)

**Comment by gobyrne** [comment]
We should probably require at least 1 essential criteria for all jobs. (confirm with Lauren)
For asset criteria, zero is acceptable.
