### ISSUE TITLE
Task - Add new FI classification

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#3966]
Add FI classification to client-side constants. Ensure it is added to database via admin portal as well.

**Comment by rositak** [comment]
Please note that the FI classification has two different set of requirements based on the level. i think we should include both and let managers take-out the irrelevant one.

For FI-01 positions only:
Successful completion of two years of a post-secondary program with specialization in accounting, finance, business administration, commerce or economics; or
Possession of the Government of Canada Financial Management Certificate.

For FI-02 or above:
Successful completion of post-secondary degree with specialization in accounting, finance, business administration, commerce or economics AND experience related to positions in the Financial Management Group; or

Eligibility for a recognized professional accounting designation. The recognized professional accounting designations are Chartered Professional Accountant (CPA), Chartered Accountant (CA), Certified Management Accountant (CMA), Certified General Accountant (CGA)

**Comment by rositak** [comment]
Pour les postes classifiés au niveau FI-01 :

La réussite de deux années dans le cadre d’un programme d’études postsecondaires avec spécialisation en comptabilité, en finances, en administration des affaires, en commerce ou en économie; ou
être titulaire du Certificat de gestion des finances du gouvernement du Canada.

Pour les postes classifiés au niveau FI-2 et aux niveaux plus élevés :

Diplôme d’études postsecondaires avec spécialisation en comptabilité, en finances, en administration des affaires, en commerce ou en économie ET une expérience reliée aux postes du groupe Gestion financière; ou
l’admissibilité à un titre de comptable octroyé par une association professionnelle reconnue. Les titres professionnels reconnus en comptabilité sont ceux de comptable professionnel agréé (CPA), de comptable agréé (CA), de comptable en management accrédité (CMA) ou de comptable général accrédité (CGA).
