### ISSUE TITLE
Applicant - Chrome/Moz autofill doesn't trigger floating labels

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#402]
# Description
On the login, when you've saved your info into Chrome or Firefox, it auto-populates into the fields, but this does not trigger the floating labels, therefore resulting in the floating labels overlapping the auto-filled text.

https://github.com/mseemann/angular2-mdl/issues/1169

# Steps to Reproduce
1. Go to Login
2. Login and save your credentials to Chrome
3. Logout
4. Go to Login
5. See that your credentials are auto-filled

**Comment by gggrant** [comment]
Not happening on live site anyhmore in Chrome/Firefox.

Checked March 4, 2019.

**Comment by gggrant** [comment]
Just kidding.

**Comment by prakashtsi** [comment]
@gggrant  did you found any solution for this overlap issue?

**Comment by gggrant** [comment]
@prakashtsi we did, thanks!
