### ISSUE TITLE
Feature - Manager - The ability for managers to look at applications during the process as opposed to the end of it.

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#4021]
# The ability for managers to look at applications during the process as opposed to the end of it.

**Is your feature request related to a problem? Please describe.**
Currently, this can be done within the admin section but we need to give managers the same ability.

**Describe the solution you'd like**
The functionality has basically been created, it just needs to be further implemented to make it work for managers.

This request has come directly from @rositak and @laurenoncoffee within the HR FAM meetings.

**Comment by gobyrne** [comment]
@nicolsonaitken Do we need to change anything copy on the page or similar? *Applicants so far* or something like that?

Also, I noticed something when looking at my applicants (using admin portal):
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/7f7b0ce8-ddf0-4f88-8c98-7b3cd2cbb975)

**Comment by nicolsonaitken** [comment]
Shouldn't the other issue be logged as a bug or issue?

**Comment by tristan-orourke** [comment]
> Shouldn't the other issue be logged as a bug or issue?
Yep!

**Comment by gobyrne** [comment]
Ok, let's just use "until close" as the copy.

**Comment by gobyrne** [comment]
Applicants to date

should be the header until poster closes as well.

**Comment by gobyrne** [comment]
"Closes today" would be nice as well.
