### ISSUE TITLE
[Design] - Manager(s) / Additional fields in position type / Indeterminate, Term, Assignment and, Secondment

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#4040]
# Design Goal & User Groups
Adding indeterminate to the job poster and also adding assignment, secondment, and the option to choose multiple options for a job poster?

**Please select the users this UI will apply to.**
- [ ] Administrators
- [x] [Applicants](https://github.com/GCTC-NTGC/TalentCloud/issues/1548)
- [x] [Hiring Managers](https://github.com/GCTC-NTGC/TalentCloud/issues/1549)
- [x] [HR Advisers](https://github.com/GCTC-NTGC/TalentCloud/issues/1550)

# Initial Research & Notes
**Please list/link all research performed before this design work began. Include research relevant to insights from team members as well. Don't be afraid to ask for references or documents!**

- Help FINTRAC to start using Talent Cloud
- Assignment and Secondment have been added as we are hoping to hire an AS-03 for our team, and we want to open it up for assignment/secondment.

## Version 1

Prototype Link:
https://xd.adobe.com/view/a01fc387-739e-4bae-b6da-4f51b25c2d91-f54c/

![image](https://user-images.githubusercontent.com/5738959/87357949-dd4bf200-c532-11ea-9597-f7c7ad0ae426.png)
![image](https://user-images.githubusercontent.com/5738959/87357963-e341d300-c532-11ea-8ba6-cd679f324974.png)
![image](https://user-images.githubusercontent.com/5738959/87357970-e76df080-c532-11ea-8851-e3236838574c.png)

# Assumptions
- Job Type will have to be added to the Job Card and Poster as well. 

## Versions 2 and 3
https://xd.adobe.com/view/e23aa033-ba01-4433-a040-756d3d06c483-b769/

### Changes
**In the second version**, the user selects either Indeterminate or Term from a pull-down menu. If Indeterminate is selected nothing changes but, if Term is selected the user can add Assignment and/or Secondment and the term in months.

**In the third version**, the user can select either Indeterminate or Term* (definitions are included). If Indeterminate is selected nothing changes but, if Term is selected the user can add Term, Assignment, and/or Secondment and the term in months.  * A new word would have to be chosen for the first instance of Term. 

## Final Version
https://talent-cloud.slack.com/files/UGH3URM7Z/F017E4CJWTU/indeterminate_vs._term.mp4?origin_team=T5ZFRSQ3V&origin_channel=GKBPS12BB

**In the final version**, all options are displayed and the user will have the ability to select either Indeterminate or any or all of the options Term, Assignment, and/or Secondment. If Indeterminate is selected nothing changes but, if Term, Assignment, and/or Secondment is selected then the Term in months will be shown.

**Job Card:**
No changes will be made to the initial job card. 

The second job card will show the duration in months if Term, Assignment, and/or Secondment is selected and Indeterminate if Indeterminate is selected. 
![image](https://user-images.githubusercontent.com/5738959/88086056-bc982380-cb54-11ea-8427-fecf05c545d0.png)

**Job Poster**
The following change will be made within the basic information section of the job poster. If Indeterminate is selected then Indeterminate will be shown within the basic information section. And if Term, Assignment, and/or Secondment is selected then the term in months will be shown followed by each of the selected options in brackets.  

![image](https://user-images.githubusercontent.com/5738959/88091153-a9895180-cb5c-11ea-9c21-5ff4897b2135.png)

![image](https://user-images.githubusercontent.com/5738959/88090672-e99c0480-cb5b-11ea-90bc-bb52ccdc9204.png)

**Admin**
Admins will need to be able to designate which departments are PSEA and which departments are non-PSEA.

- Assignment and Secondment are available to everybody and
- Indeterminate is only available to departments that have been tagged as non-PSEA within the Admin portal.

**Comment by gobyrne** [comment]
Schema on job poster has an employmentType field that should be updated to reflect this value. Currently it is always set to "full-time, temporary"
