### ISSUE TITLE
Applicant - create UI for updated Profile page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#4073]
# Description
This is almost identical to the Experience step of the new application. It should reuse many of the components.

Changes from Application:
- The accordions now have an additional "Skills for this <experience>" section common to all of them, from where you can choose to edit those skills. (There is no need to add new skills here.)
- The experience-skill form now appears in a modal, instead of listed on a separate page as in the Application.

https://xd.adobe.com/view/ec68632f-aa2b-4fcb-b2b1-b5504eabb711-b93b/screen/a1a49572-b2ad-4d24-9b7b-573285b6cf73

**Comment by Jerryescandon** [comment]
Can we add a confirmation modal for "**Delete Experience**" ?
