### ISSUE TITLE
Bug - Wrong number of applicants listed on confirmation email to managers

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#4140]
# Description
We now email managers to tell them when their job has closed. The number of applicants listed in this email is not correct, it is probably counting incomplete applications.

**Comment by gobyrne** [comment]
@tristan-orourke I don't see your pull request. But please link to this (or close this bug if it's already merged in).

**Comment by tristan-orourke** [comment]
Looks like we made duplicate issues. A PR for the other one, #4141 has already been merged.
