### ISSUE TITLE
[Design] - Monitoring Telework/Remote Work Descriptions

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#417]
# Design Goal
**Please describe the ask.**

The terms "remote work" and "telework" are not broadly understood but appear prominently on our job posters. We need to convey the meaning of these better without cluttering up our interface.

-Telework means that you work from home some days and in the office on others.
-Remote work means that you don't need to live or work in the same city as the rest of the team... essentially you could work from anywhere (maybe even outside Canada... though not necessarily)

I feel like we could likely replace the two terms, each with their own short sentence.

**Related Features:** 
- Applicant Facing Job Poster

**Related Issues:**
- N/A

**Comment by gobyrne** [comment]
@Jerryescandon suggested we might be able to collapse the two checkboxes (for "remote work" and "telework") since it seems likely that if remote work is allowed, telework will always be allowed. This could clean up the interface a little.

@laurenoncoffee what do you think of this idea?

@JasmitaChawla Could you please ask a couple questions about this when doing your user testing?

**Comment by laurenoncoffee** [comment]
low priority - but product shop wants in. can we move this to 2 weeks from now?

**Comment by gobyrne** [comment]
Jasmita had some suggestions: in issue #552

**Comment by gobyrne** [comment]
@Jerryescandon has some suggestions: #374

**Comment by laurenoncoffee** [comment]
i don't think we can collapse these two terms. You're only thinking about it in the positive sense - if remote work is allowed, telework will be allowed. But what about in reverse? Some jobs allow telework but not remote work. 

I like Gray's initial reaction to define these better. Maybe something along the lines of 
Remote work: you can live anywhere and connect to your team online
Telework: you have a desk at the office, but you can work from home some days

**Comment by gobyrne** [comment]
Rather than the info bubbles that Jerbo suggests, I like the idea of just having:
"(checkmark) Work from home some days."

but I don't know how to explain "remote work" as succinctly.
