### ISSUE TITLE
Applicant - Can still apply to jobs after they close if you have the link.

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#418]
# Description
Applicants can still apply to jobs after they "close". Blocking this should be enforced.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by tristan-orourke** [comment]
> behavior

Attempting to apply brings you to an error page.
