### ISSUE TITLE
Manager - Preview Job Posters before saving

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#423]
# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by gobyrne** [comment]
This is fine for now because we have a big update planned for the manager portal. Just a flag for @Jerryescandon and @joshdrink that the "preview" button also saves the job poster and that should be made clearer.
