### ISSUE TITLE
Admin - Hidden Directory Detected

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#428]
The test tried to detect hidden directories on the server. The 403 Forbidden response
reveals the existence of the directory, even though access is not allowed.

Issue a "404 - Not Found" response status code for a forbidden resource, TOC or remove it completely

If the forbidden resource is not required, remove it from the site.

If possible, issue a "404 - Not Found" response status code instead of "403 - Forbidden". This change will obfuscate the presence of the directory in the site, and will prevent the site structure from being exposed.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by tristan-orourke** [comment]
Fixed on Prod with change to nginx conf.
