### ISSUE TITLE
Admin - Missing or insecure "Content-Security-Policy" header

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#429]
Configure your server to send the "Content-Security-Policy" header.

For nginx, see:
http://nginx.org/en/docs/http/ngx_http_headers_module.html

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by tristan-orourke** [comment]
This will involve some discussion. We need to write a policy that specifies what domains we can access scrips, fonts, images, stylesheets, etc from.

**Comment by gggrant** [comment]
Duplicate
