### ISSUE TITLE
Manager - Localization for Manager Portal

### ISSUE THREAD

**Issue by Djama613** [GCTC-NTGC/TalentCloud#433]
# Description
Move language on manager portal to lang files. Translate accordingly. Have someone demo the process for me and then I can dive into it further. 

# Images

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ x] Create pull request to `dev`
- [x ] Address issues found during peer review
- [x ] Have someone else accept pull request into `dev`

**Comment by Djama613** [comment]
Going to be redesigned/reworked. Don't worry about this right now.

**Comment by xander-miller** [comment]
PR #661
