### ISSUE TITLE
Task - Copy existing Course, Degree & Experience objects to new ExperienceEducation and ExperienceWork objects

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#4409]
# Description
Courses, Degrees, and Equivalent Experience map 1-to-1 to ExperienceEducation and ExperienceWork. We must write migrations that create new Experience objects for each of these old objects, with the data copied over.

**Comment by tristan-orourke** [comment]
@gobyrne Equivalent Experience (on the current profile) doesn't map cleanly to any of our new Experience types. The Company field suggests it should map to the new Work Experience, but Work Experience doesn't have a field to copy the old Description field to. 
![Equivalent Experience](https://user-images.githubusercontent.com/4313717/94852112-64548c00-03f7-11eb-913a-3dd3cb9a43bb.png)

**Comment by tristan-orourke** [comment]
@gobyrne One alternative would be to copy the old Equivalent Experience into Personal Experience objects instead. We could combine the old Role and Company fields to create the Title of the Personal Experience, and copy the Description over. Personal Experience might not be as good a representation, but it _would_ mean no data would be lost.

**Comment by gobyrne** [comment]
Excellent observation Tristan. We could also maybe map it to both? Let's pull some designers into this convo.

**Comment by Jerryescandon** [comment]
This actually is opening a new can of worms, if we do the transition and pour old things into the new "Personal Experience" does this not incentivize the abuse of "Personal Experience" since it's the only one which allows for an open text field? Would we be seeing a lot of people creating "Personal Experience" in their applications recreating the same problem we had with the previous design? 

I would instead not only opt for dropping "Description" in the transition, but also for heavy limiting and restricting the "Personal Experience" ' Description' field.

**Comment by gggrant** [comment]
I agree with @Jerryescandon, I thought the quality of descriptions we were receiving was the rationale for removing the field.

**Comment by bitliege** [comment]
Generally, I agree as well - we shouldn't populate data where it shouldn't be, as it will likely lead to confusion. Is there a reason we don't simply hold off on migrating this specific experience and allow the user to do so on their own? At the end of the day, how we communicate our decision to the user will be what matters most.

**Comment by Jerryescandon** [comment]
I vote for doing the migration and dropping the description, making sure this bit is communicated in our outgoing "Transition" emails and blog posts currently on the product team. We should make sure there is a coordinated launch to reduce confusing to our (admittedly small) user base.
