### ISSUE TITLE
Task - Manager/HR - Application view for new Timeline

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#4410]
# Description
Create manager and HR view for new job application (timeline). This should use the presentation from the "review" step. The "toolbar" which allows you to screen out the applicant should still appear at the top of the page.

By default, the experiences should be sorted by Skill for the manager view (which is different than the applicant view).

This is the page that is accessed by clicking "view application" on the list of applicants page, in the manager portal.

**Comment by tristan-orourke** [comment]
This is a duplication of issue #2892
