### ISSUE TITLE
Switch 3rd party email service to Notify

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#4454]
Currently using send grid, with some limits to how many emails we can send. Interested in switching to Notify by CDS:
https://digital.canada.ca/2019/11/26/introducing-notify/

**Comment by mnigh** [comment]
@gobyrne Installing the [PHP client](https://docs.notifications.service.gov.uk/php.html#set-up-the-client) linked to by GC Notify in their [technical documentation](https://notification.alpha.canada.ca/documentation) via composer triggers a _PHP Fatal error:  Allowed memory size exhausted_. Unless the environment's PHP memory limit is set to unlimited (which is not recommended), using the GC Notify service within our application would hinder environments with limited memory capacity to run the application locally. 

Beyond that memory limit exception, there would need to be some work done on the integration into Laravel. I was able to find an [example](https://ayup.agency/blog/2019/how-we-integrated-with-gov-uk-notify) of the PHP Client being used within Laravel, though the [application](https://github.com/RoyalBoroughKingston/ck-api/blob/master/composer.json#L12) is using an older version of the PHP client.
