### ISSUE TITLE
Applicant - Standardize "remote work" text

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#451]
# Description
The text for "remote work" is in 3 places on the applicant portal. On the "browse jobs" cards, at the top of the Job Poster and in the Work Environment section of the job poster. We use different text in all three places but should standardize.

In all three places it should read "Remote Work Allowed" or "Remote Work Not Allowed". On the browse jobs cards and in the Work Environment section the text should continue to be split on two separate lines.

The text for telework in the work environment section should also mimic this (until we come up with a better way to describe what it is).

# Required for Completion
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Update Translation Spreadsheet
- [ ] Create pull request to `dev`

**Comment by gobyrne** [comment]
Telework is actually different, it's not a boolean, so let's let it remain different for now.

**Comment by joshdrink** [comment]
@gobyrne Reassigning to you for French changes. See the commit history for the exact locations of the language I changed.
