### ISSUE TITLE
Scoping - Search for Applicants

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#4608]
# Description
We want to provide Managers with the ability to search for Applicants that meet various criteria.

This task is to discuss various ways of providing that functionality, including the specifics of search criteria and the backend technology used, and to (roughly) estimate the effort involved in each feature or approach.

These estimates are for creating an API endpoint that provides search results, and not for any UI associated with making or displaying the search results.

## Search Features we could support

*NOTE* Seems like each (basic) feature we want to search on will be worth 2-3 points, and combining them all together may be worth 5-8 points at the end.

Note that each of these features also require a way to order or rank the filtered results.

Feature: Decide on API format
Estimate: 2
Description: Decide how search parameters to API, and how results should be returned.

Feature: Filter by Skills
Estimate: 3
Description: Managers select skills from our lookup table. We filter out Applicants who don't have experience linked to ALL of the selected skills.
Comments: might be easier to write as a raw SQL query.

Feature: Search by Work Preferences
Estimate: 3
Description: Filter by fields that are directly part of the Applicant model, but which don't exist yet.

Feature: Search by Applicant Language
Estimate: 3
Description: Filter by fields that are directly part of the Applicant model, but which don't exist yet.
Comments: 

Feature: Search by Proferred Location
Estimate: 3
Description: Filter by Province and city values that are part of the Applicant model, but which don't exist yet. This could include ranking a City match higher than just a Province match?

Feature: Search by Classification and Level
Estimate: 3
Description: Filter by values directly associated with Applicant model. We have lookup tables for classification and level, but they aren't yet associated with Applicants. We could allow lower-ranked partial matches (ie classification but not level).

Feature: Search by Skill Keyword
Estimate: 8
Description: We could curate our own list of keywords for each skill, and then match keywords to skills to enable a roundabout Search by Skill.

Feature: Skill description Full-Text search
Estimate: 13
Description: Use full-text search to match arbitrary text to our skill descriptions to enable a roundabout Search by Skill.

Feature: Experience Title Full-Text search
Estimate: 8
Description: Search by text that appears in Experience titles.

Feature: Experience Full-Text search
Estimate: 13
Description: Use full-text search to match arbitrary text to any text fields in Applicant Experiences.

Feature: Semantic Search for Skills
Estimate: 21
Description: Match the *intent* of arbitrary text to the most similar skills in our database to enable a roundabout Search by Skill.

Feature: Semantic Search for Experience
Estimate: 21
Description: Match the *intent* of arbitrary text to the similar terms in any text fields of Applicant Experiences.

Feature: Rank applicant results
Estimate: 8
Description: Rank search results that meet more criteria, or meet criteria better. Especially complicated if there are multiple criteria that can be evaluated.

## Potential methods of search
- basic SQL queries
- SQL [full-text search functions](https://www.compose.com/articles/mastering-postgresql-tools-full-text-search-and-phrase-search/)
- Elasticsearch

## Other things to consider
- If we allow searching/filtering by multiple features at a time, how do we rank overall results?
- How do we test speed and quality of different features/techniques? Will require a production-like environment with many applicants.
- How do we evaluate quality of search results?
- Allowing applicants to hide their profile
- Allowing applicants to reveal their profile to specific Managers

**Comment by tristan-orourke** [comment]
*Elasticsearch* - I asked my partner about Elasticsearch, as she specializes in natural language processing and her company uses it.

Elasticsearch sounds great in a lot of ways. It's open source, and considered basically the best large-scale search solution in industry. Its designed to consume free-form text documents, and magically turn them into more structured data (eg extracting dates, titles, etc) but can also start from database data (as in our case). It can be queried with an SQL-like syntax and can do very fast full-text searches.

Elasticsearch runs as its own search engine server. It takes the data provided to it and constructs its own data index, which it runs searches on. In our case, it means it would need to run on its own server (or on our Nginx server with its own endpoint) and we would set it up to periodically query the database server to update its index. The web app would query the Elasticsearch server for search results, and the data used in these searches would always be slightly out-of-date with the database.

**Comment by Khristophor** [comment]
Those Postgres text search functions are pretty cool, TIL
