### ISSUE TITLE
Application - Experience Step - Saving experience deletes ExperienceSkills not relevant to current job

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#4615]
# Description
When Experience is saved, requests are sent to delete any ExperienceSkills that are no longer checked. However, this currently includes skills for which no checkbox even appears, because they aren't relevant to the current job.

**Comment by tristan-orourke** [comment]
Also, if an ExperienceSkill object has a non-empty description which is not visible here, perhaps we should use [soft deleting](https://laravel.com/docs/4.2/eloquent#soft-deleting) so it could be restored later, if a user re-adds the skill to that experience? Currently, they can delete it without realizing there is any text associated.

**Comment by gobyrne** [comment]
@tristan-orourke suggests also soft deleting so we can restore text if a skills is re-added.
