### ISSUE TITLE
Bug - Application Skill validator test failing intermittently

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#4639]
# Description
Two unit tests fail sporadically causing build issues on PRs and dependency updates:

```
1) Tests\Unit\Validators\StrategicResponseApplicationValidatorTest::testSkillsComplete

Failed asserting that true is false.

/var/www/tests/Unit/Validators/StrategicResponseApplicationValidatorTest.php:174

-------------------------------------------------------------------------------------

1) Tests\Unit\Validators\ApplicationValidatorTest::testSkillsComplete

Failed asserting that true is false.

/var/www/tests/Unit/Validators/ApplicationValidatorTest.php:120
```

either both tests are bad, the skill validator is bad, or we have some factory generation that falls outside the expected data structure and throws a failure randomly.

Reproducing locally has been problematic (I ran these tests for over an hour one day without a failure).

**Comment by tristan-orourke** [comment]
I believe the tests fail when they delete a skill criteria and expect application validation to fail, and it does not. We now only require hard skill, so ensure it doesn't delete a soft skill by mistake.
