### ISSUE TITLE
Applicant - Sort Experience Categories by Date

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#467]
# Description
Users are having a tough time understanding their experience sections because the application displays them in the order the user creates them. Ideally we should display them in chronological order or provide the user with the ability to reorder them.

**Comment by gobyrne** [comment]
I like the chronological solution since it's much simpler to implement.

**Comment by joshdrink** [comment]
Chatted with @Khristophor and this logic makes sense for the controller to handle. Sorting by field isn't native to Twig without writing a custom extension, and at the end of the day, it's more of a controller-y thing logic wise anyway.
