### ISSUE TITLE
Spike - Classifications and Levels for profile page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#4715]
# Description
How to do it

https://github.com/ToferC/payscraper

**Comment by mnigh** [comment]
@gobyrne Fetching occupational groups and their levels via the method used by [ToferC/payscraper](https://github.com/ToferC/payscraper) only pulls in 40 groups. Based on [this list](https://www.canada.ca/en/treasury-board-secretariat/services/staffing/qualification-standards/core.html) from TBS (I'm not sure if this list is comprehensive or not), there are 75 groups. Therefore based on that information, almost half of the total groups would be missing, making for an incomplete data source. 

Also of concern and unrelated to the completeness of the data, any sort of application that scrapes unstructured data from a source like this would make our application very brittle provided that the data being consumed was used in core parts of our application. The ideal solution would be to have a structured data source (in JSON format, preferably) that we could consume, though I haven't been able to find a public source where this is available. Barring the availability of an aforementioned data source, creating our own database tables with this information that we could manually update (if this is a requirement) would be the next most stable solution, in my opinion.
