### ISSUE TITLE
Manager - Server (PHP) Validation of Job Poster Fields

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#473]
# Description
Ensure all fields that a manager could fill out are being validated by the server.

# Required for Completion
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by gobyrne** [comment]
For now should do errors for invalid on "save" and should gives errors for required fields missing on "publish".

Could also require a job title for "save".

**Comment by gobyrne** [comment]
One essential criteria is required. No asset criteria is required. All other fields required.

**Comment by gobyrne** [comment]
Business logic:

- "Accepting application to" must be in the future.
-"Start date" must also be at least 1 month in the future

**Comment by gggrant** [comment]
Job poster builder makes this obsolete.
