### ISSUE TITLE
Applicant - Change "Related Projects" title on "My References" page 

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#480]
"Related Projects" title under "My References" not clear to users, they thought it meant personal side projects. "Projects You Have Worked on with this Reference" would be a clearer title. 

![my reference](https://user-images.githubusercontent.com/38079220/48288367-e15c6e00-e439-11e8-8c2f-d1093be898db.png)

**Comment by joshdrink** [comment]
@gobyrne Reassigning to you for French changes. See the commit history for the exact locations of the language I changed.
