### ISSUE TITLE
Applicant - Add word limit to Need to Have skills

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#484]
Add a word limit in the **Need to Have** skills section so that users have a better idea of how much information is expected. 

<img width="959" alt="screen shot of Skills You Need to Have page" src="https://user-images.githubusercontent.com/38079220/48573330-e312af80-e8d9-11e8-8568-ef60f71e6be2.png">

**Comment by gobyrne** [comment]
duplicate of #556
