### ISSUE TITLE
Task - Remove ClassificationId constant from frontend

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#4892]
# Description
#3908 started the process of stripping the Classification constants from the frontend, but because we have multiple areas at various stages of hook/redux usage it becomes difficult to simply strip out this functionality.

Areas affected:
- Application v2
- Job Poster Builder
- Storybook stories
- HR Index
- Review Application

The hook is available in `hooks/jobBuilderHooks.ts` as `useLoadClassifications()` (we should probably move it out of here at it's more global), and I _think_ just needs to be called in the relevant page files and passed as a Classification array prop, but taking out the `ClassificationId` constant also affects other places like `models/jobUtil.ts` since we have a helper function for constructing a classification string from a key and level concatenation. With the new `name` field added in #3908 this shouldn't be necessary.

**Comment by tristan-orourke** [comment]
I'm adding this to the Manager UI & Search Epic because I know we're going to have to add more classifications, and this should be part of that.
