### ISSUE TITLE
Task - Add Review Status endpoint

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#5052]
# Description
Review Statuses are currently hardcoded on the front end. Add an api endpoint for the ReviewStatus model to return localized names for each of the non talent response review statuses.

Requires a migration to add a localized column to the review_statuses table, endpoint creation, route registration, Redux store setup, and component consumption.

**Comment by gobyrne** [comment]
Can wait for us to re-use this functionality for GC Digital Talent build.
