### ISSUE TITLE
Bug - Expand All Skills on Application Review UI V2

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#5054]
# Description
The `Expand All Skills` button on the Application Review UI was using `resources/assets/js/app.js` logic based around ID's and classes to toggle accordions open/closed. The new Review UI uses different markup that no longer functions when the button click fires.

Either:
- Change the markup on the new UI to continue to function with the old JS functionality
or
- Add capability to the new page to expand the sections based on a prop or Redux store variable that can be triggered by a component that lives outside of the Review page component hierarchy

It might make more sense to create new buttons to Expand all Skills/Education/Experience that toggles the corresponding section and opens all accordions. Good product question for how to proceed.

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Log in as a manager at `talent.test/en/manager`
2. Click on the `My Job Posters` menu item to view the list of manager job posters
3. Select one with applications set to version 2 in the database
4. Review the list of applicants
5. Review an individual application
6. Click the `expand all` button on the top

# Images
![Screen Shot 2021-01-08 at 2.48.13 PM.png](https://images.zenhubusercontent.com/5703a53d6caf56c9d38f5099/95437594-22de-4c85-ae34-c4f938e2642f)

**Comment by tristan-orourke** [comment]
Adding this to the Update Manager UI Epic so we don't lose track of it.
