### ISSUE TITLE
Application Profile - server-side validation should check whether email already exists

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#514]
# Description
Trying to change you email to one that already exists causes an exception (because of uniqueness constraint in database) but it should be caught by validation.

# Steps to Reproduce
1. Go to application profile
2. Change your email to one that already exists in database
3. Save

**Comment by gobyrne** [comment]
Works, but gives a 500 error. I will create an issue to handle that better.

**Comment by tristan-orourke** [comment]
Turns out I pulled the pull request without actually merging it into dev
