### ISSUE TITLE
Task - Audit Logs - Log failed job application submission

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#5250]
Log when a job application submission fails, so we have a record of it in case someone claims they submitted their application but we can't find it.

If possible, it would be nice to log the reason the submission failed and maybe some of the data in the job application.

**Comment by mnigh** [comment]
@tristan-orourke It looks like this information is [already been logged](https://github.com/GCTC-NTGC/TalentCloud/commit/5c1e600953193e6f8b702b91a252fa6ada35116e#diff-aac0460f8cd44b3bdf142c9636ca301b7ee86dcd81bf919048dad9f9d8aa1b86R79), or is there something I'm missing?

**Comment by tristan-orourke** [comment]
Closed because the requested feature already exists.
