### ISSUE TITLE
Bug - Database error when entering non-unique gov_email

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#5334]
# Description
On the HR first visit pages, entering a non-unique gov_email returns a database error:

```SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "users_gov_email_unique" DETAIL: Key (gov_email)=(grant.barnes@tbs-sct.gc.ca) already exists. (SQL: update "users" set "gov_email" = grant.barnes@tbs-sct.gc.ca, "updated_at" = 2021-03-01 19:07:32 where "id" = 5274)```

An error message should be handled and displayed on the form.

- [ ] Regression test written.

**Comment by tristan-orourke** [comment]
Also check this on HR Register page, Manager First Visit and Manager Registration.

Should add front and backend validation for each failing case.
