### ISSUE TITLE
Bug - Applicant Profile - Message for empty skills groups

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/TalentCloud#5337]
# Description
When there are no skill categories added, there is no indication of why nothing appears. Either a message stating that there are no groups available should be displayed or the Group tab should be hidden.
![image](https://user-images.githubusercontent.com/22059495/109564705-71150300-7aaf-11eb-8370-3ea27ee40059.png)

# Steps to Reproduce
Steps to reproduce the behaviour.
1. Go to Applicant Profile
2. Click on My Skills
3. Scroll down to Your Skills
4. See **Sort By:** section

**Comment by tristan-orourke** [comment]
Show same "no skills" message under Group sorting as under alphabetical sorting.
