### ISSUE TITLE
Bug - JPB: Details - Add consistent options to work culture radio groups

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/TalentCloud#5345]
# Description
In the Job Poster Builder Details step, in the work culture section near the bottom of the page there are two radio groups with identical options. However, the options are in a different order on each radio group. 
![job-details-workculture-radio-button-options-bug](https://user-images.githubusercontent.com/22059495/109562652-ab30d580-7aac-11eb-930e-ca987cd43403.PNG)

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Create or open a draft job poster in the JPB
2. Go to the Details step
3. Scroll down to the work culture section
4. See error.

**Comment by tristan-orourke** [comment]
@gobyrne @Jerryescandon What's our text for this?

**Comment by Jerryescandon** [comment]
![image](https://user-images.githubusercontent.com/16977254/110150650-7de66f00-7dad-11eb-820a-c7bbd296df51.png)

With Lauren's soft approval on this. it should go:
- Never
- Rarely
- Occasionally
- Frequently
- Almost Always

Whatever the french equivalent of those is, @gobyrne ?
