### ISSUE TITLE
Bug - Application Timeline - Duplicate text

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/TalentCloud#5346]
# Description
There is duplicate text in EN and FR on the Start Your Application portion of the Job Poster Application.

# Steps to Reproduce
1. Go to Job Poster Application
2. See duplicate text

# Images
![image](https://user-images.githubusercontent.com/3046459/109564791-8b4ee100-7aaf-11eb-8b30-875b97dd2794.png)

**Comment by tristan-orourke** [comment]
Fixed in #5356
