### ISSUE TITLE
Bug - Application Skills component story shows error

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/TalentCloud#5422]
# Description
The storybook story for the Application Skills component shows an error.

# Steps to Reproduce
1. Open storybook
2. Click on Application > Skills > Skills Page
3. See error

# Images
![Screen Shot 2021-03-11 at 17 17 32](https://user-images.githubusercontent.com/3046459/110872177-86531400-829d-11eb-9524-b550929ed9fa.png)

**Comment by mnigh** [comment]
@yonikid15 mentioned this could be caused by the use of the `useDispatch` redux hook in the Skills component.

**Comment by yonikid15** [comment]
Should be resolved by #5417

**Comment by tristan-orourke** [comment]
> Should be resolved by #5417

Closing this issue.
