### ISSUE TITLE
Bug - When using a screen reader, its possible to escape a Modal with keyboard shortcuts

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#5460]
# Description
Even if we correctly set up tab loops in our modals, its possible to escape them without closing them when using other keyboard navigation tools provided by screen readers (eg arrow keys, the Next Button hotkey, the Next Header hotkey, etc).

The `aria-modal` attribute is supposed to stop this from happening, but it seems to still be experimental and only has [patchy support](https://a11ysupport.io/tech/aria/aria-modal_attribute). @bitliege also has some concerns about this attribute possibly interfering with other features unpredictably.

As far as I can tell, the only way to reliably avoid this is to have all modals live in a single root div, with _all other_ document.body content living in a sibling root div. When a modal is opened, all non-modal content could be made inaccessible to screen readers by adding `aria-hidden` to the main body root div.

**Comment by gobyrne** [comment]
Modal work has been completed separately and they are now passing Fable testing well.
