### ISSUE TITLE
Applicant - Difference between Remote, Telework and Flex Hours 

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#552]
# Description
Have definitions for _Remote Work Allowed_, _Telework_, and _Flex Hours_ on the job description page. 

Note: The text has to be reviewed. 

<img width="681" alt="descriptions for remote, telework, flex hours" src="https://user-images.githubusercontent.com/38079220/50347343-3abcc000-0503-11e9-8df7-4e8deceac701.png">

**Comment by gobyrne** [comment]
I'm still not quite happy with these definitions. @JasmitaChawla let's discuss

**Comment by gobyrne** [comment]
Duplicate of issue #417. Closing this one, but will link to it
