### ISSUE TITLE
Applicant - Definition of Tagline 

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#553]
# Description
Users are unsure of what a _Tagline_ is under _My Profile_. Include a definition and sample tagline. Replace the heading _Other Information_ with _Tagline_.

Note: The text has to be reviewed. 

# Images
<img width="574" alt="definition of tagline" src="https://user-images.githubusercontent.com/38079220/50348936-38109980-0508-11e9-903a-c31bb32a992a.png">

**Comment by gobyrne** [comment]
@laurenoncoffee can you please review the text Jasmita has proposed in the image above?

**Comment by JasmitaChawla** [comment]
I think it's hard to judge right now if there's any value in having this field, as most users weren't filling it out since they didn't understand what it meant. I believe it would be good to add an explanation like in the image above, and then see if more users fill it out. If users still don't complete this field, then we should remove it. It might also be worthwhile to check if this is something managers like reading.

**Comment by gggrant** [comment]
@JasmitaChawla @gobyrne 

Can we get EN/FR copy for this? Or please close the issue.
