### ISSUE TITLE
Applicant - State cover letter/resume isn't required 

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#554]
# Description
Users are under the impression that they will be uploading their cover letter/resume at some point during the application process, explicitly state this isn't required on the homepage. 

Note: The text has to be reviewed. 

# Images
<img width="378" alt="state cover letter/resume not required" src="https://user-images.githubusercontent.com/38079220/50349991-95f2b080-050b-11e9-9372-d75e4c8004a5.png">

**Comment by gobyrne** [comment]
I think I like it. Let's roll this into the homepage refresh that josh is working on.

**Comment by JasmitaChawla** [comment]
The text was taken straight from Josh's homepage refresh, I thought it would be useful to have on the live site as well.

**Comment by gggrant** [comment]
@JasmitaChawla @gobyrne 

Can we get EN/FR copy for this? Or please close the issue.
