### ISSUE TITLE
Spike - Creating a separate Laravel Backpack portal

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#5566]
# Description
We want to use Backpack to create a portal similar to the admin portal, but exclusive to Talent Pool managers. Look into Backpack could be configured to set up two different interfaces, at two different urls.

**Comment by gobyrne** [comment]
Seems like we can't have a separate one, but we can hide menu items on admin portal based on assigned role which should work just as well.
