### ISSUE TITLE
Applicant - Change Format for Application Deadline

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#557]
# Description
Users would prefer to see _Last Day to Apply_ instead of _Days/Hours Till Close_ on the job cards, on the _Browse Jobs_ page. 

# Images
<img width="402" alt="change app deadline format" src="https://user-images.githubusercontent.com/38079220/50356088-cdb72380-051e-11e9-8a7f-67366ce6882d.png">

**Comment by gobyrne** [comment]
In early testing that I did, when asked about it, applicants said they wanted both forms. My sense is that the absolute date would be preferable on this job card and on the poster. On the applicant dashboard and (if we add it) during the application, I suspect the time remaining might be best.

But for now, let's just do the job card as Jasmita suggests. @JasmitaChawla can you please comment on the other locations = job poster & applicant dashboard?

**Comment by JasmitaChawla** [comment]
Sorry, what do you mean by other locations = job poster & applicant dashboard?

**Comment by gobyrne** [comment]
Ideally it's in the timezone of the user with the time zone stated. But putting it in EST is OK.

**Comment by gobyrne** [comment]
@JasmitaChawla yes, but the rest of the team is saying to change it everywhere. So we will do that.
