### ISSUE TITLE
Applicant - Option to add GitHub link

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#558]
# Description
Give users option to add a link to their GitHub account under _About Me_ in _My Profile_.

# Images
<img width="471" alt="github link option" src="https://user-images.githubusercontent.com/38079220/50356558-68fcc880-0520-11e9-8ac5-c590c76f674e.png">

**Comment by gobyrne** [comment]
This is great for Digital & Tech talent, but would be weird for most other job types.

**Comment by Jerryescandon** [comment]
We could also design a more long term solution for this to include custom social media links.

**Comment by gggrant** [comment]
Stale
