### ISSUE TITLE
Applicant - Hint text for Register 

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#559]
# Description
Change the hint text in _Register_ from _Name_ to _First and Last Name_, to give users a clearer format for input. 

# Images
<img width="677" alt="hint text for register" src="https://user-images.githubusercontent.com/38079220/50356842-a9a91180-0521-11e9-90db-7e03e9d8e619.png">

**Comment by gobyrne** [comment]
French = Prénom et nom

**Comment by joshdrink** [comment]
@gobyrne Reassigning to you for French changes. See the commit history for the exact locations of the language I changed.
