### ISSUE TITLE
Task - Pools Portal - Add page to view all applicants in (their) Pools

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#5604]
# Description
Remember, this is a page built in Backpack.

It should be a table that lists all applicants in the user's pools. (Note: we only have one pool to start with, so any Pool Managers must necessarily own _that_ pool.)

**TODO**: find out exactly which fields we want to display here. For now, email and username are fine.

Preliminary list that is on google form:

- First Name
- Last Name
- Contact Information (open field, guide says email and phone)
- City (open field)
- Province (open field)

- Language of Preference
- Working Ability

- Work Locations (checkboxes)
- Comments (for location)

- Work Availability (shift work, work weekends, work scheduled overtime, work overtime on a short notice)

- Education and Certifications

- Computer Programming Languages

- Employment History

- Asset Qualifications (yes, no and explain for each)

- Salary range and/or Group and Level Expected (radio buttons per $10,000 tranche)
-Group and Level (open text)

**Comment by gobyrne** [comment]
Can start with placeholder if needed to get started while we wait for final fields.
