### ISSUE TITLE
Manager - Skills with accent character not correctly sorted on Create Job page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#564]
# Description
Skills that start with an accent character (so only in french) are always sorted to the bottom.

**Comment by gobyrne** [comment]
@Khristophor were you working on this? If so please pull it into the current sprint. If duplicate, please flag and delete.

**Comment by mnigh** [comment]
this issue related to a dropdown rendered in a Twig view that is no longer used.
