### ISSUE TITLE
Applicant - Review error messages in saving validation

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/TalentCloud#577]
# Description
E.g. "This field needs to be a string" 
This language needs to be updated for end users.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by gobyrne** [comment]
The way these are displayed also needs to be looked at by @joshdrink

**Comment by gobyrne** [comment]
@tristan-orourke where do we look to find this copy? There are authentication lang files, but they must contain a lot more than is bieng used

**Comment by tristan-orourke** [comment]
The copy for this is in resources\lang\en\validation.php and resources\lang\fr\validation.php, but now I think this might be more a dev issue. You should only see "This field needs to be a string" if you put the wrong kind of input in, like trying to submit an image file instead of text.

**Comment by tristan-orourke** [comment]
There's probably a backend bug stopping this from saying "This field is required" instead.

**Comment by gobyrne** [comment]
Ok, I'll unassign Jerbo and Myself

**Comment by gobyrne** [comment]
Might end up being part of the broader validation refactoring that we have to do.

**Comment by gggrant** [comment]
Dated issue, error messages in many areas have been refactored.
