### ISSUE TITLE
Applicant  - Links in job poster text

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/TalentCloud#592]
# Description
Links added in the job poster text should appear as clickable.

# Images
<img width="1025" alt="screen shot 2019-01-09 at 12 49 22 pm" src="https://user-images.githubusercontent.com/16977254/50918152-70bbd880-140d-11e9-83ac-9afd26d768da.png">

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by yonikid15** [comment]
@joshdrink and @Khristophor .. take a look at this when it comes time to build the job poster builder.

**Comment by tristan-orourke** [comment]
> @joshdrink and @Khristophor .. take a look at this when it comes time to build the job poster builder.

Oops. That never happened.
