### ISSUE TITLE
Backend - Create standards for translation files

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#594]
# Description
I noticed a few duplicate translation lines across the various lang files. I think it would be a useful exercise to come up with a better standard for grouping/organizing our translations so that copy changes don't have to check multiple places, developers don't have to reference multiple translation files, etc. and then ensure the correct files are bound to views with ViewComposers.

For example, I had to make some edits to the Job index and Job single view. There are many duplicate translations between the two templates because the translation files are grouped according to what view they belong to, rather than something more generic like the model itself that could apply to multiple views.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by gggrant** [comment]
@tristan-orourke Did you start on this? @gobyrne was wondering.
