### ISSUE TITLE
Applicant - Accordion triggers not obviously clickable

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#606]
# Description
Accordion triggers do not register as a link, both on profile and job application. Users with assistive technology would not know that they can be clicked on to perform addition actions.

@joshdrink would it be much effort to change this without impacting the UI?

# Images
<img width="1161" alt="screen shot 2019-01-10 at 1 49 21 pm" src="https://user-images.githubusercontent.com/31678168/50989958-ca400800-14de-11e9-8326-8b298a08a98d.png">

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by joshdrink** [comment]
Somehow these aren't button elements?!?! Anyway, easy enough to fix - I'll make it similar to the design system until that's implemented.
