### ISSUE TITLE
Applicant - Add date picker to final step of Job Application

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#608]
# Description
We have decided to remove the field altogether and display/record the current date.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by gobyrne** [comment]
Ok, this ended up being a data picker after all. I've added an issue to turn it into text instead.
