### ISSUE TITLE
Applicant - Elements using class="hidden" ignored by screen readers

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#610]
# Description
The styles used for the "hidden" class are being ignored by screen readers, but are intended to be read by screen readers as a visual alternative. Elements include Step 1-5 links, delete buttons that use an X, profile pictures.

See this link for suggested styles for hiding content as well as allowing for SR interpretation:
https://webaim.org/techniques/css/invisiblecontent/

Create a separate class for SR-only content if we are hiding content in other places for different reasons with "hidden".

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by joshdrink** [comment]
So I built the hidden class to deliberately be ignored by screen readers. I'll take a look at the elements you're describing, but this is intended behaviour.
