### ISSUE TITLE
Manager - Better Screening Tools (ROD)

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#619]
# Description
Manager portal - Need better screening tools for Record of Decision (ROD), done per skill. 

2nd pass at screening applicants (after things such as if they pass language/citizenship requirements). 

Dependencies:
- Admin portal (until admin and manager portal are separated)
- HR portal (ROD gets sent to HR portal)

**Comment by Jerryescandon** [comment]
This issue has been split into several ones. 
- Initial Screening tool #687 
- Advanced Screening Tool (RoD) #757
- Rating and Assessment Guide #756 
- Export to HR #758
