### ISSUE TITLE
Manager - Screening plan v2

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#623]
# Description
Improve current version of Screening Plan Builder.

Link to Wireframe:
https://xd.adobe.com/view/00bd3e88-5169-4bd1-4a44-1ca9e3cca1d5-768c/

Dropdown list:
 - Narrative Review (**Special rules**)
 - Application screening question
 - Group test
 - Informal phone conversation
 - Interview
 - Online exam
 - On site exam
 - Portfolio review with candidate
 - Reference check
 - Serious games
 - Take home exam

# Design Checklist
- [ ] Cleanup interface
- [ ] Include Wireframes for Dev Checklist

# Dev Checklist
## General
- [x] Ask @Jerryescandon for walkthrough.
- [x] One screening plan per job poster.
- [x] Simplify assessment tools in drop-downs (See "Dropdown list" above).
- [x] Narrative Review added for all new skills by default, **but is Removable**
- [ ] The contents of this page should still copy/paste to a word document using the "copy" button

## My Assessment Plan Summary
- [x] My Assessment Plan Summary section is updated dynamically as assessment tools are added to skills above)
- [x]  Summary line. "Using 2 tools to assess 4 skills"

## Handle Draft posters
You should now be able to build a screening plan, even if your job poster is a draft
- [x] As Skills are added or removed from a job poster, automatically add/remove accompanying elements from the Assessment Plan builder and Ratings Guide builder.
- [x] First time the Screening Plan page is viewed after these things are changed, display a notification at top of page summarizing changes.

## (New feature) My Rating Guide  
- [x] Each assessment tool has it's own section
- [x] In each section, all criteria to be evaluated by this assessment tool are initially listed at the bottom "1 essential missing: HTML, 3 Asset missing..."
### Narrative Review
- [x] Nothing is editable for the "Narrative Review" tool
- [x] "Acceptable answer..." is always the same for narrative review
### Other Assessment Tools
- [x] Questions can be added to the assessment tool
- [x] Skills can be added to the question
- [x] Only skills associated with this assessment (in the Assessment Plan) are available for adding
- [x] Each skill has a text input for "Acceptable answer"

## Validation
- [ ] Define validation rules.

**Comment by gobyrne** [comment]
Tristan and I have a little work to do for figuring out how to gracefully handle changes to the draft job poster on the screening plan.

**Comment by gobyrne** [comment]
Doesn't need to be @tristan-orourke that builds it though.

**Comment by tristan-orourke** [comment]
As per discussion with Gray, Jerbo & Josh: As Skills are added or removed from a job poster, automatically add/remove accompanying elements from the Assessment Plan builder and Ratings Guide builder. First time the Screening Plan page is viewed after these things are changed, display a notification at top of page summarizing changes.

**Comment by gggrant** [comment]
Resolved by #937
