### ISSUE TITLE
Admin - Review deploy scripts for Laravel commands

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#644]
# Description
`php artisan migrate`, `php artisan cache:clear` etc.

Also potentially merging the two deploy scripts.

# Required for Completion
Add/remove others as necessary for this specific task.
- [x] Run Lighthouse (Chrome Dev Tools)
- [x] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by gobyrne** [comment]
@gggrant should this be associated with a specific pull request?

**Comment by gggrant** [comment]
> @gggrant should this be associated with a specific pull request?

#654
