### ISSUE TITLE
Task - Make Application data immutable

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#647]
# Description

Data submitted in an application should be separated from Applicant profile, which can change.

The skills and experience submitted in an application are just links to the data on an applicant's profile. If they change their profile later, there will be no record of the data originally submitted. 

Hiring managers should only have access to the skills and experience that was submitted with an application, not the full info from applicants profile.

**Comment by xander-miller** [comment]
I think a model change tracker is a good way to tackle this. This may be a package for Laravel that does it https://laravel-news.com/laravel-auditing-package
