### ISSUE TITLE
Error handling for "Email already exists"

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#649]
# Description
If you try to change you email on your profile to one that already exists you get a 500 error (see #514). This should be handled in a way that gives useful feedback to users.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Run Lighthouse (Chrome Dev Tools)
- [ ] Run WAVE Evaluation
- [ ] Browser Compatibility Check
- [ ] Update Translation Spreadsheet
- [ ] Does this affect configuration? (If so discuss with team)
- [ ] Create pull request to `dev`
- [ ] Address issues found during peer review
- [ ] Have someone else accept pull request into `dev`

**Comment by yonikid15** [comment]
Fixed in #122
