### ISSUE TITLE
Admin - Talk to project team about value of sprint reviews

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#651]
# Description
Dev team wants to know what Product team values most about the (dev) Sprint Reviews. Also, how could we make them better? Sprint Review are really for Product Team since we already know what we've done. So we want to make the review as impactful as possible for you. All feedback is appreciated.

# Required for Completion
Add/remove others as necessary for this specific task.
- [ ] Talk to the project team

**Comment by gobyrne** [comment]
Talked to Lauren. She likes the idea that we could ask questions directly to the product team about direction we want to take our features. I think this is a great idea, but it's probably better to do it during the Product team's sprint review, since the very end of our Sprint is an awkward time to change direction.

**Comment by gobyrne** [comment]
Talked to Shelley. Shelley values hearing about how difficult things are. It has given her a better sense of what is easy to do and what is hard. She also likes hearing how things are done (or why one solution was picked over another).

**Comment by gobyrne** [comment]
Rosita says she would like to hear how the work that was done ties in to overall functionality of the site. Sometimes it's not clear if the story is just working towards something or if new functionality she can use has actually been unlocked.

**Comment by gobyrne** [comment]
Meagan says she likes to she the functionality we've added so she can think about which ones could be re-purposed for the indigenous portal. Also helps her understand what independent features could be need for indigenous portal.
