### ISSUE TITLE
502 Error while browsing manager portal

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#652]
# Description
This bug appears inconsistently, but often when signing in and out of the manager portal, we get the 502 error below. Refreshing the page usually gets rid of it. I have never noticed in on the applicant portal.

![image](https://user-images.githubusercontent.com/2494551/51616535-4d5a5880-1ef8-11e9-93a1-0f536e396968.png)

As of 2019-01-23 I get this error about %40 of the time when I log in or out of the manager portal.

**Comment by gobyrne** [comment]
Grant looked into this, but we haven't tracked it down yet.

**Comment by vid** [comment]
This only seems to happen on the production server.

**Comment by xander-miller** [comment]
Resolved by Environment changes.

**Comment by vid** [comment]
This is an ongoing intermittent issue, which be related to the https server in the hosting production environment. Investigating there.

**Comment by vid** [comment]
A ticket az-2184 was opened on the internal Jira system March 1, waiting on resolution.

**Comment by vid** [comment]
Front-end IPS has been modified. Since then, I haven't been able to reproduce the problem. Have asked affected users to report any new incidents.

**Comment by gggrant** [comment]
Original JIRA ticket resolved the original issue.

Reported happening again by @laurenoncoffee on manager screening plans.

**Comment by vid** [comment]
I've reopened the Jira ticket with updated details.

**Comment by vid** [comment]
Current issue is a 419 error. Closing this ticket.
