### ISSUE TITLE
Nginx gives a 500 error frequently in development due to permissions

### ISSUE THREAD

**Issue by xander-miller** [GCTC-NTGC/TalentCloud#656]
### Description
Nginx 500 error. 595 Connection refused. This error appears intermittently in production and development. Grabbed from the nginx log. 

`172.18.0.1 - - [24/Jan/2019:14:57:08 +0000] "POST /en/profile/1/about/update HTTP/1.1" 500 595 "https://talent.local.ca/en/profile/1/about" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"`
 
### Steps to Reproduce
Intermittent error. 

### Screen Shot

![Imgur](https://i.imgur.com/G836Vyk.png)

### Additional Context
Current confirmed observation was on a large POST request.

**Comment by xander-miller** [comment]
In development this was the permissions error. By changing the permissions on `storage/` and `bootstrap/cache/` to 777 the 500 error went away.

**Comment by Khristophor** [comment]
Actual solution locally:
```
docker exec -it nginx /bin/sh
chown nginx:nginx storage/
chown nginx:nginx bootstrap/cache/
```

From https://laravel.com/docs/5.7/installation#configuration

**Comment by xander-miller** [comment]
You need to have an nginx user created in your dev environment for that to work though. When I tried that, it did not seem that docker had provided one. Docker was running as root.

**Comment by xander-miller** [comment]
Issue is still occurring in production on the manager portal. David will take a crack at it.

**Comment by Khristophor** [comment]
> You need to have an nginx user created in your dev environment for that to work though. When I tried that, it did not seem that docker had provided one. Docker was running as root.

@xander-miller docker-compose spins up a number of containers, one of which is the nginx container that has access to the php one via networking. My command connects to the nginx container (which has the nginx user) in order to change the permissions.

**Comment by gggrant** [comment]
Resolved by https://github.com/GCTC-NTGC/tc-docker for dev, deploy script in production.
