### ISSUE TITLE
Convert Login Template from Blade to Twig

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#671]
# Description
The login, registration, password reset, etc. (all auth templates) are currently using Blade instead of Twig. The logic is a bit funky, but these templates should be moved to Twig.

**Comment by tristan-orourke** [comment]
Now we're considering moving everything to React, lets leave this for now.

**Comment by joshdrink** [comment]
@tristan-orourke I'm getting @yonikid15 to attempt this despite the React work because I think it's a great exercise to help familiarize with Twig syntax and functionality. Even if it's redundant work, it's a good learning opportunity.
