### ISSUE TITLE
Manager - Updated Dashboard

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#685]
# Description
We are re-building the manager dashboard (the "My Job Posters Page").

Jerbo's wireframe: https://xd.adobe.com/view/e79e0e9e-d1ae-4b0c-749d-9436424f1ae7-91af/

The first image below shows the wireframe we want to implement with a single Draft job poster.

### Full page
- [x] New Draft button that links to the "Create Job Poster" page
- [x] Empty state for when there are no job posters
- [x] We don't have a way to archive so no need for 2 separate sections (current & archive), just leave as one section for now. @joshdrink , you decide if it should be titled at all.

### Draft State (see first image below)
All new job posters start in the Draft state.
- [x] Edit icon on the left
- [x] Job Title is a link to the Job Poster Preview
- [x] Below Job Title: Created On (date)
- [x] Edit Job Poster button - Links to filled in "Create Job Poster" page
- [x] Edit Screening Plan - Links to screening plan builder for this job poster. Just use "Screening Plan" as text, do not add the word "edit"
- [x] Do not create the "Assessment Tools" button, we don't have anything to link to yet
- [x] *Future Feature* (no need to create it yet) Delete button for drafts
- [x] Send to review button - Open's up a dialogue with the options: Cancel and Send to Talent Cloud.
- [x] Send to talent cloud option in dialogue triggers an email to Talent Cloud with body text " *Manager Name* has submitted *Job Title* job poster for review." This action also changes the state of the job poster to "submitted"

### Submitted State (see second image below)
Submitted state starts as soon as the "send to talent cloud" dialogue has been confirmed. It ends only if job poster is flagged as "published" and the "Open" date is reached.
- [x] Waiting icon on the left
- [x] Job Title is a link to the Job Poster Preview
- [x] Below Job Title: Created On (date)
- [x] Time since sent for review in middle (don't say to HR)
- [x] Edit Job Poster button - Links to filled in "Create Job Poster" page (we might need to remove this when we transition from concierge service to managers)
- [x] Screening Plan button - Links to screening plan builder for this job poster
- [x] Do not create the "Assessment Tools" button, we don't have anything to link to yet
- [x] Send to review button - greyed out

### Posted State (see third image below)
Posted start when the poster is flagged as "published" and the "Open" date is reached. It ends when the "Closed" date is reached.
- [x] Waiting icon on the left
- [x] Job Title is a link to the live Job Poster
- [x] Below Job Title: Posted On (date)
- [x] Time until close in middle
- [x] Screening Plan button - Links to screening plan builder for this job poster
- [x] Do not create the "Assessment Tools" button, we don't have anything to link to yet
- [x] Review Applicants button - disabled

### Closed State (see last image below)
Closed starts when the poster is flagged as "published" and "Closed" date is reached. For now it does not end.
- [x] Action Required icon on the left
- [x] Job Title is a link to the (archived) Job Poster
- [x] Below Job Title: Closed On (date)
- [x] Number of applicants in middle
- [ ] Clock counting up from Closed Date in middle
- [x] Screening Plan button - Links to screening plan builder for this job poster
- [x] Do not create the "Assessment Tools" button, we don't have anything to link to yet
- [ ] Review Applicants button - links to new Review Applicants page #687

## Images
Draft State (full page)
![image](https://user-images.githubusercontent.com/2494551/52150275-750a9880-263d-11e9-8a87-ef8e3f1a6c6c.png)

Submitted State
![image](https://user-images.githubusercontent.com/2494551/52151800-43480080-2642-11e9-8ccb-c1614cb1e48c.png)

Posted State
![image](https://user-images.githubusercontent.com/2494551/52152011-f284d780-2642-11e9-93ae-164d8695bb15.png)

Closed State
![image](https://user-images.githubusercontent.com/16977254/52301346-3edc5a00-2958-11e9-93a0-49961e2eb348.png)

**Comment by Jerryescandon** [comment]
I would prefer if we keep the "Archived" section in the front-end, even if it's not currently plugged into anything in the backend.

**Comment by xander-miller** [comment]
Required Backend Work:

- [ ] Route and Controller Action for send to Reviewer 'Post' Request Updates Job and sends email.
- [ ] Methods to calculate the state of the job post from other attributes (published_flag, opened_at, closed_at, review_requested_at)
- [ ] Migrate review_requested_at Time Stamp database
- [ ] Add .env Variable for review email. Notify deployers about the .env change.

Testing
- [ ] Add factories for new Job Attributes
- [ ] Unit Tests for State calculated method
- [ ] Test Controller Action including sending email
- [ ] 

Cleaning up:
- [ ] Add Localization Strings

**Comment by xander-miller** [comment]
Resolved by #707
