### ISSUE TITLE
Admin - Flag specific user as priority

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#690]
# Description
Admins (Talent Cloud Concierge) should have the ability to flag an applicant (Identifiable by name and/or email) as a Priority. Priorities are treated differently in the application process, so they need to be made visible to managers. The intent is to have them displayed separately on the Review Applicants page #687.

Down the road we will try and build something that allows priorities to self-identify, but for now, they have to contact Talent Cloud and our concierge service will upgrade their user profile through the admin portal.

For now users are either priorities or they are not, but in the future we might want to allow for various types (levels) of priorities. It's not of interest right now, but we might put a time limit on how long a person is a priority for (since priority status normally expires at some point).

This issue is a dependency of #690.

**Comment by tristan-orourke** [comment]
- [ ] Users can be flagged as priority on the admin portal
- [ ] Priority users appear in their own section of the Application Review page

**Comment by Khristophor** [comment]
@tristan-orourke I pushed up what I have working so far on `feature/add-priority-to-applicants`. I've hit a bit of a wall around assigning the checkbox value to the applicant priority field, as it doesn't seem to work the way I thought it could.

It seems that in the index view, you can specify a property of a relationship with dot notation, but you can't do the same for a field:
https://github.com/GCTC-NTGC/TalentCloud/blob/task/add-priority-to-applicants/app/Http/Controllers/Admin/UserCrudController.php#L77-L81

We might have to hijack the update method and set/unset the value manually.

I also grabbed the toggle control from [this PR that hasn't been merged](https://github.com/Laravel-Backpack/CRUD/pull/165).

**Comment by Khristophor** [comment]
After discussion with @gobyrne we opted to add a boolean field to the User model instead.
PR [can be found here](https://github.com/GCTC-NTGC/TalentCloud/pull/783).

**Comment by gggrant** [comment]
Resolved by #783
