### ISSUE TITLE
Applicant - Success logic for Step 4 (Nice to Have)

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#696]
# Description
Step 4 of application should be successful (green checkmark) when a user clicks Save & Continue, instead of when they fill out all skills on the page. This prevents Step 5 (Review) from green lighting.

**Comment by gobyrne** [comment]
This issue overlaps with #640

**Comment by gggrant** [comment]
Outdated: Applicant timeline.
