### ISSUE TITLE
Refactor Published flag to published_at DateTime

### ISSUE THREAD

**Issue by xander-miller** [GCTC-NTGC/TalentCloud#713]
A published flag is no longer sufficient for the data resolution requested by the product team. In  #707 a published_at field is added to the job poster as an interim solution. Refactor out the published flag and replace it with references to the published_at field. 

- [x] This task requires a unit test.
- [x] This task is complex and needs acceptance criteria.

**Comment by gggrant** [comment]
Outdated: #2189
