### ISSUE TITLE
Applicant - Bilingual prompt

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/TalentCloud#715]
# Description
The lack of clarification in bilingualism at poster level has caused current processes to crash, after managers find a large number of applicants without the bilingual skills on a bilingual position. We need an improved solution to flag bilingual requirements and their full impact at the job poster level to guarantee applicants understanding of language level requirements before applying.

- [ ] This task requires a unit test.
- [ ] This task is complex and needs acceptance criteria.

# Images
Place image attachments (wireframes, etc.) here.

**Comment by Jerryescandon** [comment]
@gobyrne Per Lauren's request, this is affecting current job processes and should be prioritized.

**Comment by Jerryescandon** [comment]
Assigned @JasmitaChawla to this. Please add wireframe to this issue and and tag Josh when ready to move to dev.

**Comment by JasmitaChawla** [comment]
Add a Language Requirements section after the Criteria section. The copy would be different for each job poster depending on the requirement for that position: Bilingual, English Essential, French Essential, and English or French Essential. 

@gobyrne Could you review the copy in the wireframes?

Job Poster - Bilingual:

<img width="539" alt="jobposter-bilingual" src="https://user-images.githubusercontent.com/38079220/52864136-835db780-3107-11e9-9266-d9fe5905648f.png">

Add a question on Step 1 of the application. This would also change depending on the requirement for the job poster. 

Application - Bilingual:

<img width="488" alt="applicant-bilingual" src="https://user-images.githubusercontent.com/38079220/52864284-d7689c00-3107-11e9-8317-d2e7f69c3dad.png">

Job Poster - English Essential

<img width="429" alt="jobposter-engess" src="https://user-images.githubusercontent.com/38079220/52864945-60cc9e00-3109-11e9-8146-5f1c82548b54.png">

Application - English Essential

<img width="512" alt="applicant-engess" src="https://user-images.githubusercontent.com/38079220/52865238-2adbe980-310a-11e9-9a83-140b0f6ad6c4.png">

Job Poster - French Essential

<img width="444" alt="jobposter-fress" src="https://user-images.githubusercontent.com/38079220/52865565-ee5cbd80-310a-11e9-9a11-bc9ac2c2b0ac.png">

Applicant - French Essential

<img width="500" alt="applicant-fress" src="https://user-images.githubusercontent.com/38079220/52865893-94102c80-310b-11e9-889a-57847a9935a6.png">

Job Poster - English or French Essential

<img width="418" alt="jobposter-engorfress" src="https://user-images.githubusercontent.com/38079220/52866167-1c8ecd00-310c-11e9-8c4e-ca099402a921.png">

Application - English or French Essential

<img width="516" alt="applicant-engorfress" src="https://user-images.githubusercontent.com/38079220/52866270-54961000-310c-11e9-9b26-616ef872e5e3.png">

If an applicant tries to move onto the next page of the application without checking the checkbox:

<img width="506" alt="applicant-prompt" src="https://user-images.githubusercontent.com/38079220/52866398-91fa9d80-310c-11e9-9d5f-d92ea0ed747c.png">

**Comment by gobyrne** [comment]
Do we have a strategy for accessing the effectiveness of this intervention? I'm ok with it in general though. If possible I would like to put a few alternatives to this in front of users.

I would propose asking for their estimated levels instead of checkbox.

Should we add a "bilingual badge" to posters (and eventually users maybe).

**Comment by gobyrne** [comment]
Also, I don't think "English Or French" is a thing for Talent Cloud

**Comment by Jerryescandon** [comment]
@laurenoncoffee for review

**Comment by laurenoncoffee** [comment]
The copy is fine as is, with the exception of the "If my first official language is English, I will be tested in French, and vice versa". 

This makes it sound like the applicant has to do all the requirements in their second language.

How about this:
"You are entitled to be assessed on the "Need to Have" and "Nice to Have| criteria for this position in the Official Language of your choice (English or French). But if the position requires bilingual competencies, you will have to do additional testing in your second language to confirm your language ability."

**Comment by Jerryescandon** [comment]
@gobyrne move to dev backlog

**Comment by joshdrink** [comment]
@gobyrne `English or French` is indeed an option in the database right now, so let me know how to proceed copy-wise on that option.

**Comment by joshdrink** [comment]
@laurenoncoffee I modified your proposed text ever so slightly to match the tense used elsewhere in this copy: "I understand that this position has a bilingual language requirement. Knowledge of both English and French are required. I am entitled to be assessed on the "Need to Have" and "Nice to Have" criteria for this position in the Official Language of my choice (English or French), however the bilingual requirement means I will have to do additional testing in my second language to confirm my language ability."
