### ISSUE TITLE
Admin - Revise Docker and docker-compose build

### ISSUE THREAD

**Issue by vid** [GCTC-NTGC/TalentCloud#722]
# Description
Revised docker-compose setup that supports:
* [x] Completely automated deployment of the stack on a workstation or public host
* [x] Use by workstation developers, where it will support development without requiring development tools past docker-compose
* [ ] Consolidate logs from running services
* [x] App permissions for Laravel directories
* [ ] Ability to use the same app image in development and deployment
* [x] Hosted in its own GCTC-NTGC repo

**Comment by gggrant** [comment]
Resolved by https://github.com/GCTC-NTGC/tc-docker
