### ISSUE TITLE
Admin - Update Laravel Mix

### ISSUE THREAD

**Issue by Khristophor** [GCTC-NTGC/TalentCloud#727]
# Description
Laravel Mix is two major versions behind (2.4 vs 4.0) and npm throws a high severity security warning when running `npm install`. I attempted to update Mix and the rest of the npm dependencies but got into an issue compiling sass after trying to consolidate our sass dependencies. Might be easier at this point to leave everything else as-is and just update Mix.

**Comment by gggrant** [comment]
Managed to solve that with instructions here: https://laravel-mix.com/docs/4.0/upgrade The `node-sass` package needed to be reinstalled and added to the sass mix.

@joshdrink the webpack options could be reviewed for relevance as well as some of the package dependencies.
