### ISSUE TITLE
Admin - Admins need a way to edit all details on any job poster

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#728]
Admins need to able to edit any job poster.
For now, if an admin user navigates to the manager/jobs page, they should see and be able to edit all job posters.

Link to edit page from admin portal as a shorter-term solution. Resolved by #788

**Comment by Khristophor** [comment]
Add a link from the admin portal Job Poster index to the edit form.

**Comment by xander-miller** [comment]
Could we make a different route and controller, `admin/jobs`, that uses the same view template? It seems strange that you would go to 'manager/jobs' to edit jobs you don't own.
