### ISSUE TITLE
Show last full Day in Job Apply By Fields

### ISSUE THREAD

**Issue by xander-miller** [GCTC-NTGC/TalentCloud#747]
Priority Fix

- [x] `/jobs` shows last full day in apply by field
- [x] `/jobs/#` shows last full day in apply by field
- [x] Change Date format to full month with just the number 1, 2 instead of '1st' '2nd'

**Comment by gobyrne** [comment]
@xander-miller Could you please add here the Exact logic you're using to calculate what day to display?

**Comment by gobyrne** [comment]
This was addressed in Sprint Review. Logic is that 1 day is subtracted from the input UTC date to determine the display date.
