### ISSUE TITLE
Manager - Empty applicant profile questions not displaying correctly.

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#751]
The empty state for applicant profile is not being presented properly to hiring managers on the "review application" page.

Current behaviour: Empty answer in applicant profile
![image](https://user-images.githubusercontent.com/44560341/53520009-9a56bf00-3aa2-11e9-9ca6-654a52fca1ff.png)

Expected behaviour: "The applicant didn't complete profile"
![image](https://user-images.githubusercontent.com/44560341/53520026-a5115400-3aa2-11e9-982b-b014d8603819.png)

# Steps to Reproduce

# Images
Place image attachments (wireframes, etc.) here.

# Additional Context

**Comment by xander-miller** [comment]
Created branch `feature/manager-application-review-null-state-handling`

**Comment by xander-miller** [comment]
In #787 I added handling for individual questions.
