### ISSUE TITLE
Screening Plan Builder

### ISSUE THREAD

**Issue by rositak** [GCTC-NTGC/TalentCloud#753]
Please name the task using the following information: **Browser - Name**. Give this issue a "FED" or "BED" label, alongside the "**Bug**" label.

# Description
Current: Skill names have disappeared
![image](https://user-images.githubusercontent.com/44560341/53528966-38ee1a80-3ab9-11e9-9f3b-d2d999d474d1.png)
![image](https://user-images.githubusercontent.com/44560341/53529002-59b67000-3ab9-11e9-8e9e-fb949ecf1659.png)
![image](https://user-images.githubusercontent.com/44560341/53529017-633fd800-3ab9-11e9-89ae-d4e41f7ce5f6.png)

Expected: Skill names should appear left of/above description

- [ ] This bug requires a unit test.

# Steps to Reproduce

# Images
Place image attachments (wireframes, etc.) here.

# Additional Context

**Comment by gggrant** [comment]
Duplicate
