### ISSUE TITLE
Manager: re-routing for non-manager login

### ISSUE THREAD

**Issue by laurenoncoffee** [GCTC-NTGC/TalentCloud#755]
**Re-routing when you sign in to the wrong (manager or applicant) portal is confusing. Applicants signing in to manager portal end up back on applicant portal and vice-versa.

Tried to login to my manager account. It opened as though I was in the manager portal. but when I went to My Profile and clicked there, it routed me through to a regular applicant account.

Apparently I'm not a manager yet.

I didn't notice until I went to save the profile fields I'd completed and they got erased :(

This will be confusing when we release the Freemium version for managers. We need some way to clearly identify this. Maybe UX help?

**Comment by gobyrne** [comment]
I have a bunch of question/thoughts that need to be addressed here. As Lauren indicates, these will be important to figure out before we go Freemium (end of April targeted)

- Do you need a separate account & email to sign in to each portal? Or can one user use both portals?
- Do we white list government emails for the manager portal
- Do we make the 2 portals very distinct (ui differences, "sign in to manager portal", etc...)
- Do we make it easier to hop between the 2?

 @joshdrink @Jerryescandon @nicolsonaitken can we plan to put some design effort on this between here sometime in March? We could also discuss as a whole team, as it could be influenced by Dev and Pro requirements as well.
