### ISSUE TITLE
Server should use security header best practices

### ISSUE THREAD

**Issue by vid** [GCTC-NTGC/TalentCloud#761]
# Description
The server should enforce best practices for server headers. Specifically:

* Content-Security-Policy
* Referrer-Policy
* Feature-Policy

- [ ] This bug requires an integration test.

# Steps to Reproduce

Conformance can be validated from eg https://securityheaders.com/?q=https%3A%2F%2Ftalent.canada.ca%2F&followRedirects=on

**Comment by gggrant** [comment]
Resolved by #839 .

https://securityheaders.com/?q=talent.canada.ca&followRedirects=on
