### ISSUE TITLE
Applicant - Incorrect layout/style on error message 

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/TalentCloud#766]
The  Login and Reset Password pages Error messages requires appropriate layout/style changes to fit theme of site.

![screen shot 2019-03-04 at 3 48 11 pm](https://user-images.githubusercontent.com/22059495/53762488-3cf1b200-3e96-11e9-8c14-b3c678d69e72.png)

**Comment by gggrant** [comment]
Resolved by #782
