### ISSUE TITLE
Remove "English or French essential" from language options

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#779]
# Description
When creating a job poster, one of the language options is "English or French essential". This is not a viable option for Talent Cloud, so we should remove it from the list of options.

**Comment by gobyrne** [comment]
@laurenoncoffee can you please confirm that removing this option is the correct approach? It's not a big deal, but it has come up (see #715) because language options impact other parts of the site.

**Comment by gobyrne** [comment]
Description from @xander-miller for #799 :
Remove english_or_french from language_requirements table in database. Will also recommend refactoring enum options like language_requirements out of database and into job post model so they are easier to update and manage.

**Comment by gggrant** [comment]
Resolved by #824
