### ISSUE TITLE
419 Error while logging out of Manager Portal

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#786]
# Description
When logging out of the Manager Portal I received an error page. Error 419. This happened on two occasions in Chrome.

- [ ] This bug requires a unit test.

# Steps to Reproduce
Steps to reproduce the behaviour:
1. Login to the Manager's portal: https://talent.canada.ca/en/manager/login 
2. Click from page-to-page.
3. Logout

# Images
Place image attachments (wireframes, etc.) here.
![image](https://user-images.githubusercontent.com/5738959/53993854-83e1e080-40fe-11e9-9cd4-57a63bff2e7b.png)

# Additional Context
There is no additional context.

**Comment by gggrant** [comment]
Addressed in #834
