### ISSUE TITLE
FAQ link in Manager Portal goes to wrong page

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#800]
Please name the task using the following information: **Browser - Name**. Give this issue a "FED" or "BED" label, alongside the "**Bug**" label.

# Description
Clicking on the FAQ link within the main menu goes to the Jobs page and not the FAQ page. 

- [ ] This bug requires a unit test.

# Steps to Reproduce
1. Go to 'https://talent.canada.ca/en/manager/create'
2. Click on 'FAQ' in the main menu
3. Page goes to 'https://talent.canada.ca/en/manager/jobs'

**Comment by gggrant** [comment]
Close, but it actually goes nowhere.

Will we be adding copy for a FAQ when these pages are publically accessible? That's a separate discussion.
