### ISSUE TITLE
Hiring Manager - Application Screening Navigation

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#806]
# Description
Lauren's Comment: 
```navigation for screening applications on the new portal needs work. Especially need a “back” button at the top of the nav options, which currently list save and job poster only```

Suggested Additions:
- Back Button

**Comment by joshdrink** [comment]
Chatted with @laurenoncoffee & @gobyrne - just a simple Save & Back button for managers when viewing an application.

**Comment by gggrant** [comment]
Resolved by #828
