### ISSUE TITLE
Manager Ready: Admins Should Be Able to View/Edit DRAFT Job Posters

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#808]
# Description
This issue applies to allowing admin users the ability to see and edit job posters that are drafts.
This includes the ability to follow a link on the admin portal to the manager view to allow them to edit the job poster in it's entirety.

## Criteria:
- [x] Admins can see draft job posters.
- [x] Draft posters are distinct from submitted posters in some way.
- [x] Posters have a link to the "Edit Job Poster" view so that admins can edit said posters.
- [ ] This task requires a unit test.

**Comment by gggrant** [comment]
Addressed in #788
