### ISSUE TITLE
Manager Ready: Admins Should Be Able to View Applicants, Applications, and Save Both as PDFs

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#809]
# Description
Admins should have the ability to view applicant profiles (the same view hiring managers have), unique applications, and should be able to save both of these as PDF documents through the browsers print function.

## Criteria
- [x] Admins can view the manager version of an applicant's profile.
- [x] Admins can view the manager version of an application.
- [x] Admins can save both views as PDFs through native print functionality.
- [ ] This task requires a unit test.

**Comment by Khristophor** [comment]
@joshdrink from what I can tell locally, this functionality is already in place. Closing.
