### ISSUE TITLE
Manager Ready: Admins Should Be Able to Enter Translated Copy in Multiple Locations

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#811]
# Description
Admins should be able to view and edit the following views in order to facilitate the entry of translated copy:
- Job Posters
- Manager Profiles
- Manager's Work Environment
- Manager's Team Culture

Admins should be able to follow links to these views.

## Criteria
- [x] Admins can follow a link to view the "Edit Job Poster" view.
- [x] Admins can follow a link to view and edit Manager profiles.
- [x] Admins can follow a link to view and edit a manager's work environment section.
- [x] Admins can follow a link to view and edit a manager's team culture section.
- [x] Admins can enter and save French language translations.
- [x] Admins can enter and save this data on job posters without publishing (they can edit a draft).
- [x] This task requires a unit test.

**Comment by gggrant** [comment]
Resolved by #850
