### ISSUE TITLE
Localization of Manager React Views

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#814]
# Description
The new React-based views need a broader localization strategy, as well as localization proper.

## Criteria
- [x] A localization strategy has been decided on for React.
- [x] Manager facing React views have French copy.
- [ ] This task requires a unit test.

PR for this issue: #819

**Comment by gggrant** [comment]
Duplicate of #814

**Comment by xander-miller** [comment]
Working on this will PR #819

**Comment by xander-miller** [comment]
PR #819 Ready for Review
