### ISSUE TITLE
Manager Ready: Remove Time Selection From Job Poster Creation Form

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#816]
# Description
Time selection should be removed from the open/close dates on the job poster builder to avoid confusion. This means that jobs should open and close at the start/end of the day respectively in PST.

## Criteria
- [ ] Job poster creation forms no longer have time select inputs for open/close dates.
- [ ] Job posters open at 12:00AM PST on the date selected.
- [ ] Job posters close at 11:59PM PST on the date selected.
- [ ] This task requires a unit test.

**Comment by gggrant** [comment]
Resolved by #841
