### ISSUE TITLE
Manager Ready: Optimization Issues

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#818]
# Description
The site has a handful of speed issues that seem to be getting progressively worse. I've assigned all of us to this issue because I think that there's something we can all touch on.

@Khristophor already has some work done on this here: #807 

## Issues
- [ ] Site takes forever to load.
- [x] Assets begin loading about a second after the initial http request happens (we're seeing a flash of raw HTML before assets are loaded). This started happening about 1-2 months ago?

## Possible Actions
- [ ] Review CSS/JS/Image Compression
- [x] Review PHP/Laravel Methods
- [ ] Review Server Optimization

**Comment by gggrant** [comment]
Resolved by #807, #831, #832, #839
