### ISSUE TITLE
Bug - Job Poster Close Discrepancy During DST

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#838]
# Description
As it stands, job posters close at 23:59PM PST on the close date.

Daylight savings time complicates this, because job posters are actually closing at 01:59AM PDT during daylight savings time. Discussed with @laurenoncoffee and for now this is okay, but it will have to be fixed eventually so that job posters are always closing at midnight.

**Comment by gggrant** [comment]
Resolved by #859
