### ISSUE TITLE
Applicant/Sitewide - Icon change

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/TalentCloud#840]
# Description
Exchange "Delete" (X) icon for "Trashcan" to avoid confusion. This should be everywhere where in item can be attached and removed.
"When I see this I think I did something wrong cause it's all red and agressive" - Jerbo 2019

- [ ] My Skills
- [ ] My References
- [ ] My Work Samples
- [ ] Application / Need to have
- [ ] Application / Nice to have

# Images
![image](https://user-images.githubusercontent.com/16977254/54953672-2b447d00-4f1f-11e9-8959-4e6eeed7366c.png)

**Comment by joshdrink** [comment]
@Jerryescandon In the linked relatives case (like your screenshot above) you're actually not sending that object to the trash, which is why I went with an "X". The action removes the relationship, not trashes the reference.

**Comment by Jerryescandon** [comment]
In that case we might want to do the 'Minus in a circle' (-), maybe dark gray or blue coloured. Because the red 'X' is very distracting. Like.. I feel personally assaulted by it, every time I walk past it I have to be clutching my pearls.

**Comment by gggrant** [comment]
Stalemate.
