### ISSUE TITLE
Bug - Assessment plan titles load incorrectly

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/TalentCloud#843]
# Description
The levels and Level descriptions aren't loading correctly.

- [ ] This bug requires a unit test.

# Steps to Reproduce
1. Steal Gray's login credentials
2. Log in as manager
3. Click on Assessment plan
4. See error on level titles and descriptions in each skill

# Images
![image](https://user-images.githubusercontent.com/16977254/55023688-bc752b80-4fd3-11e9-94cb-d8a22a15f8c6.png)

**Comment by gggrant** [comment]
Resolved by #881
