### ISSUE TITLE
Manager - Get all emails in category

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#851]
# Description
On the "Review Applicants" page, add a link on the top of each section that allows you to access the emails for all candidates in that section. It could be as simple as copying them to the clipboard.

In the future, Talent Cloud should be able to email the candidates directly, but we're not there yet.

# Images
Could be placed here:

![image](https://user-images.githubusercontent.com/2494551/55329859-a2b56780-545d-11e9-8837-f3f9acce0bde.png)

**Comment by gobyrne** [comment]
Ideally it would have the markup that puts the person's name in front of the email address.

**Comment by gggrant** [comment]
Resolved by #856
