### ISSUE TITLE
Spike - Research Implementation of Automated Browser Testing

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#852]
# Description
We're looking at implementing a new automated test suite for browser testing. It needs to be able to test in multiple browsers. [Test Cafe](https://devexpress.github.io/testcafe/documentation/getting-started/) and Selenium were thrown out as options.

**Comment by Khristophor** [comment]
Test Cafe seems to be robust enough for our needs

- [x] Multiple browsers supported
- [x] Runs on any environment
- [x] Easy setup/install
- [x] Open Source
- [x] Nodejs based with support for Typescript/ES2017

 Also has an IDE available for Visual Test Recording

**Comment by gggrant** [comment]
Test Cafe looks great, some issues integrating with Travis but the browser tests could be run using git hooks or another means.
