### ISSUE TITLE
Admin - (Concierge) Scripting Downloading All Applications for a Job

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#860]
# Description
@gobyrne mentioned having one of us look into ways we might be able to script the process of downloading (printing as PDF) all the applications associated to a particular job poster so that it's super easy to send them as a package for HR.

The script might do things like:
- Take a job poster ID as a parameter
- Navigate to the correct page in the browser
- Open all applications for that job in new tabs
- CTRL P and Print as PDF for all tabs
- Save to a unique folder

**Comment by gggrant** [comment]
https://github.com/alvarcarto/url-to-pdf-api
Perhaps?

**Comment by gobyrne** [comment]
@gggrant Can you give a super rough guess of how long it would take you to set this up for us?

**Comment by gggrant** [comment]
Less than a fortnight. Couple days tops?

I'm currently "between tasks" so could get on it.
