### ISSUE TITLE
Bug - Deployment: 500 Error on Creating Job Poster

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#870]
# Description
@gobyrne is reporting receiving a 500 error after trying to create a job poster (he'll fill it out and then it will error or values will be empty). Please see him if you need more context.

# Steps to Reproduce
1. Log in as admin
2. Create job poster
3. Save job poster
4. See error/missing values

**Comment by gggrant** [comment]
Resolved by #876
