### ISSUE TITLE
Manager - Change "Meed" to "Need", Spell Check TypeScript

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#871]
# Description
There is a typo on the manager portal where it says "meed" instead of "need" in `https://github.com/GCTC-NTGC/TalentCloud/blob/dev/resources/assets/js/components/ApplicationReview/ReviewCategory.tsx#L85`

If possible, @Khristophor has noticed other typos, so we'd love a full spell check of the typescript files.

**Comment by Khristophor** [comment]
Found another small typo on the Job Poster create/edit form:
<img width="365" alt="Screen Shot 2019-04-03 at 2 47 59 PM" src="https://user-images.githubusercontent.com/6796588/55501283-7564e700-5620-11e9-8a11-66d626870ba0.png">
