### ISSUE TITLE
Manager - Visual indicator for applicant language preference

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/TalentCloud#890]
# Description
On the list of applicants, it would be helpful to provide managers with a visual indicator of what language the applicants have requested to be contacted in.

I find it hard to keep track of and I never think to look for it in the application.

I would recommend that we only indicate "french preference" for managers who are browsing in English and "english preference" for managers browsing in French. I could be convinced to always display it though.

I think we can use the same icons as in the Language requirements section.

**Comment by tristan-orourke** [comment]
@gobyrne Could you discuss this with Design?
