### ISSUE TITLE
Bug - 502 Error on HM Password Reset, 500 Error on Applicant Password Reset

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#901]
# Description
Gray and hiring managers are reporting 502 errors when trying to reset hiring manager passwords.

Similarly, they are reporting a 500 error when trying to reset applicant passwords.

- [ ] Add to test path.

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Try to reset a hiring manager or applicant password.

**Comment by Khristophor** [comment]
Tried yesterday locally and in production, unable to recreate. @gobyrne tried it out today in production and was also unable to recreate. Closing for now.
