### ISSUE TITLE
Applicant - Word Counter (for skill declarations) 

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/TalentCloud#917]
# Description
Follow up on PR #915 and #874 

- The word counter still needs a few more things before it can be added in:

   - [ ] Info message correlating to amount of words
   - [ ] what the max/goldilock/min amount of words should be

# Wireframe
- https://xd.adobe.com/view/e79e0e9e-d1ae-4b0c-749d-9436424f1ae7-91af/

**Comment by yonikid15** [comment]
@Jerryescandon

**Comment by Jerryescandon** [comment]
0 - 100 - "This is too short, try including examples or lessons learned"
101 - 200 - "Seems short, try adding examples"
201 - 800 - "Looks the right size"
801 - 1000 - "This is starting to get too long"
1001 - 1300 - "This looks really long, try summarizing some text"
1301 - 1500 - "This is way too long, try deleting irrelevant content, or see an example"

@gobyrne 
could you help me out with some French here?
