### ISSUE TITLE
Applicant/Manager - Update Language Options

### ISSUE THREAD

**Issue by joshdrink** [GCTC-NTGC/TalentCloud#919]
# Description

- Language requirements for the job poster, in the special case there's a job that accepts English or French or both (bilingual). 

- Language requirements for Bilingual - Intermediate (to differentiate from Bilingual - Advanced)

- Updated copy for language requirements for Bilingual - Advanced

- Copy  (updated and new) for language checkbox on Job Application Step 1 (for these 3 language requirements)

# Copy
**- English copy for language checkbox on application Step 1 (English or French):**

- I have strong reading, writing and verbal communication skills in English or French

**- French copy for language checkbox on application Step 1 (English or French):**

- Je possède de solides compétences en lecture, en rédaction et en communication verbale en français ou en anglais

**- English copy for Language Requirements on job poster(English or French):**

English or French

For this position, you meet the language requirements if you have strong reading, writing and verbal communication skills in either English or French, or both (bilingual).

You can submit this application in the official language of your choice (English or French).

**- French copy for Language Requirements on job poster(English or French):**

Français ou anglais 

Pour ce poste, vous répondez aux exigences linguistiques si vous possédez de solides compétences en lecture, en rédaction et en communication verbale en français, en anglais ou dans les deux (bilingue).

Vous pouvez présenter cette demande dans la langue officielle de votre choix (français ou anglais).

**Wireframe:**

![image](https://user-images.githubusercontent.com/38079220/56757429-29f6b200-6762-11e9-8fe1-f0394dd662ba.png)

**- English copy for language checkbox on application Step 1 (Bilingual - Intermediate):**

- I have intermediate or better reading, writing and verbal communication skills in English or French

**- French copy for language checkbox on application Step 1 (Bilingual - Intermediate):**

- Je possède des compétences intermédiaires ou mieux en lecture, en rédaction et en communication verbale en français et en anglais

**- English copy for Language Requirements on job poster(Bilingual - Intermediate):** 

This position requires working knowledge of both French and English. This means that you can take on job duties in either French or English, and you have intermediate reading, writing and verbal communication skills in both official languages. As part of this selection process, your language abilities will be tested by the [Public Service Commission of Canada](https://www.canada.ca/en/public-service-commission/jobs/services/gc-jobs/information-candidates/language-requirements-candidates.html).

You can complete all other steps of this assessment process in the official language of your choice, including the initial application, interview, exam and any other evaluation components.

**- French copy for Language Requirements on job poster(Bilingual - Intermediate):**

Bilingue — Intermédiaire

Ce poste exige une connaissance pratique du français et de l’anglais. Cela signifie que vous pouvez assumer les fonctions du poste en français ou en anglais, et que vous possédez des compétences intermédiaires en lecture, en rédaction et en communication verbale dans les deux langues officielles. Dans le cadre de ce processus de sélection, vos compétences linguistiques seront évaluées par la [Commission de la fonction publique du Canada.](https://www.canada.ca/fr/commission-fonction-publique/emplois/services/emplois-gc/renseignements-candidats/exigences-linguistiques.html)

Vous pouvez suivre toutes les autres étapes de ce processus d’évaluation dans la langue officielle de votre choix, y compris la demande initiale, l’entrevue, l’examen et toute autre composante de l’évaluation.

**Wireframe:**

![image](https://user-images.githubusercontent.com/38079220/56757559-822db400-6762-11e9-9592-546bfbad6e50.png)

**- English copy for language checkbox on application Step 1 (Bilingual - Advanced):**

- I have strong reading, writing and verbal communication skills in English and French

**- French copy for language checkbox on application Step 1 (Bilingual - Advanced):**

- Je possède de solides compétences en lecture, en rédaction et en communication verbale en français et en anglais

**- English copy for Language Requirements on job poster(Bilingual - Advanced):**

This position requires advanced knowledge of both French and English. This means that you can take on job duties in either French or English, and you have strong reading, writing and verbal communication skills in both official languages. As part of this selection process, your language abilities will be tested by the Public Service Commission of Canada [link like Intermediate].

You can complete all other steps of this assessment process in the official language of your choice, including the initial application, interview, exam and any other evaluation components.

**- French copy for Language Requirements on job poster(Bilingual - Advanced):**

Ce poste exige une connaissance avancé du français et de l’anglais. Cela signifie que vous pouvez assumer les fonctions du poste en français ou en anglais, et que vous possédez des solides compétences en lecture, en rédaction et en communication verbale dans les deux langues. Dans le cadre de ce processus de sélection, vos compétences linguistiques seront évaluées par la [Commission de la fonction publique du Canada.](https://www.canada.ca/fr/commission-fonction-publique/emplois/services/emplois-gc/renseignements-candidats/exigences-linguistiques.html)

Vous pouvez suivre toutes les autres étapes de ce processus d’évaluation dans la langue officielle de votre choix, y compris la demande initiale, l’entrevue, l’examen et toute autre composante de l’évaluation.

**Comment by gobyrne** [comment]
Ok, I think this is ready to go
