### ISSUE TITLE
Applicant/Manager - Options for applicant confirming language requirements

### ISSUE THREAD

**Issue by JasmitaChawla** [GCTC-NTGC/TalentCloud#920]
# Description

As per issue #919, some positions accept English or French or both for their language requirements. The options for when the applicant is confirming they meet the language requirements needs to be updated for this scenario. This will include 3 options, and the results will need to be displayed on the application preview (and on the application view for managers).

This also means that we will need to display these checkboxes on the job application preview and on the job application view for hiring managers.

Please note that the bullet points should be radio buttons. 

**- English copy:**

- I have strong reading, writing and verbal communication skills in English
- I have strong reading, writing and verbal communication skills in French
- I have strong reading, writing and verbal communication skills in both English and French

**- French copy:**

- Je possède de solides compétences en lecture, en rédaction et en communication verbale en français.
- Je possède de solides compétences en lecture, en rédaction et en communication verbale en anglais.
- Je possède de solides compétences en lecture, en rédaction et en communication verbale en français et en anglais.

**Comment by gobyrne** [comment]
I think these should be radio buttons and not checkboxes? @JasmitaChawla

**Comment by JasmitaChawla** [comment]
Yeah you're right, I'll change it

**Comment by gobyrne** [comment]
@JasmitaChawla can you look into whether or not we should always display these checkboxes or if we should only do it for the "English or French" special case. I'm inclined to go with whatever the devs think is easiest, but thought the UX team might have a stronger preference.

**Comment by JasmitaChawla** [comment]
I think it's fine if we always display them. Even if it is for an English position, seeing all the options here could help clear any uncertainties from the job poster.
