### ISSUE TITLE
Spike - Improve auth

### ISSUE THREAD

**Issue by vid** [GCTC-NTGC/TalentCloud#922]
# Description
Currently, the app's main auth uses form POST. There are also various corner cases in the different portals which could use consolidation to improve support and ongoing development. In order to move toward a more API focused approach, this spike will research using JWT and OpenID connect, by looking at mainstream solutions, determining where in the current app improvements and enhancements can be made, and creating an implementation plan.

JWT approach: https://github.com/tymondesigns/jwt-auth
OpenID Connect: https://github.com/jumbojett/OpenID-Connect-PHP

**Comment by gggrant** [comment]
Discuss OIDC vs JWT.
