### ISSUE TITLE
Admin - Improve Authentication

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/TalentCloud#932]
# Description
Currently, the app's main auth uses form POST. There are also various corner cases in the different portals which could use consolidation to improve support and ongoing development. In order to move toward a more API focused approach, this spike will research using JWT and OpenID connect, by looking at mainstream solutions, determining where in the current app improvements and enhancements can be made, and creating an implementation plan.

## Spike results
JWT approach: https://github.com/tymondesigns/jwt-auth
OpenID Connect: https://github.com/jumbojett/OpenID-Connect-PHP

- [ ] This task requires a unit test.
- [ ] This task is complex and needs acceptance criteria.

**Comment by gobyrne** [comment]
Any sense after the spike in what the net benefit of this is?

**Comment by gggrant** [comment]
Improved security.

We have two options for moving forward, but the spike to research _where_ improvements can be made on TalentCloud has not been done yet, as far as I know.

**Comment by gobyrne** [comment]
Chris says he could look into Laraval's default auth (Laraval passport).
