### ISSUE TITLE
Sitewide - Move server calls in frontend to redux Middleware

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#936]
# Description
Currently calls to the server happen in Thunk action creator functions. Moving this functionality to a middleware would allow it to be removed, or replaced with mock functionality, by reconfiguring the redux store. This will enable more testing, or use with Storybook.

- [ ] This task requires a unit test.

**Comment by gobyrne** [comment]
This is mostly done, closing issue.
