### ISSUE TITLE
Bug - Assessment Plan - Narrative Assessment added on page refresh if skill has no assessments

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/TalentCloud#948]
# Description
If you remove all assessments from a skill on the screening plan builder, and refresh the page, it will be given the Narrative Assessment type. Is this desired behaviour? If it is, it should probably not be triggered by a page refresh.

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Go to Assessment Plan builder
2. Remove all assessment types from skills.
3. Refresh the page
4. See that all skills have Narrative Assessment now.

**Comment by gobyrne** [comment]
Not desired behavior. But this really doesn't stop users for completing anything. Also, this will likely be rebuilt anyway when we add functionality for managers to limit which skills allow candidates to add narrative. (in the future it shouldn't be every skill)

**Comment by gobyrne** [comment]
So I would just park this issue.
