### ISSUE TITLE
Applicant - post employee benefits primer

### ISSUE THREAD

**Issue by mattejackson** [GCTC-NTGC/TalentCloud#965]
# Description
-reminder to @joshdrink post employee benefits primer
-Could go in FAQ or its own tab

# Images
Place image attachments here.

# Changes
Enter the approved copy here:

[Talent Cloud - Employee Benefits_v6 (EN).docx](https://github.com/GCTC-NTGC/TalentCloud/files/3182860/Talent.Cloud.-.Employee.Benefits_v6.EN.docx)

[Talent Cloud - Employee Benefits_v6 (FR).docx](https://github.com/GCTC-NTGC/TalentCloud/files/3182866/Talent.Cloud.-.Employee.Benefits_v6.FR.docx)

| English  | French |
| ------- | ------- |
| Content | Content |

- [x] Copy provided in English and French.

**Comment by joshdrink** [comment]
Addressed in #1430
