### ISSUE TITLE
Job Poster Builder: Step 06 - Skills

### ISSUE THREAD

**Issue by nicolsonaitken** [GCTC-NTGC/TalentCloud#967]
# Description
The sixth step in creating a job poster is Skills. A skill is the ability (or expertise) to perform a specific function in order to complete a Key Task (or Tasks). Skills and their definitions are provided by Talent Cloud and are selected by the user based on the Key Tasks previously written by the user in Job Poster Builder: Step 05 - Tasks #959 

- [x] This task requires a unit test.
- [x] This task is complex and needs acceptance criteria.

**Acceptance Criteria**

***Progress Bar***
- [x] As skills are added they get added to either one or both of the progress bar counters. One bar indicated the number of Essential Skills that have been added and the other indicates the number of total skills added.
- [x] Each progress bar will indicate a sweet spot that is an indication of optimized for best results. 

***Skills, Work Environment***
- [ ] On page load a minimum of 1 and a maximum of 2 Work Environment skills will be presented to the user within the Work Environment section of this page. These pre-selected skills will be created based on the results within Job Poster Builder: Step 03 - Work Environment #745.
- [x] Users will have the ability to add the the recommended skills or add any other skill listed.

***Skills***
- [x] On page load the user will be presented with the list of Key Tasks as previously written by the user in Job Poster Builder: Step 05 - Tasks #959.  
- [x] Skills are categorized as Occupational Skills, Cultural Skills and Future Skills.
- [x] All skills will be manually tagged to fall into one (or more) of these categories.
- [x] Once a skill is added a modal will pop-up allowing the user to add specificity to the definition and to determine the level.
- [ ] The definition will be capped at 50 words.
- [x] Once a skill has been added, it will be added to the list of skills under either Essential or Asset.
- [x] Once a skill has been added, the Skills counter will increase by a value of one. If the Skill is Essential, the Essential Skills counter will also increase by one. 
- [x] Skills can be removed by either the selecting the icon on the skill itself or from the icon within the skills list. 
- [x] Skills can be edited by selecting the icon within the skills list.
- [x] Users will have the ability to Save their progress through a save button within the skills list area. 
- [x] If the user wants a new skill added, they will have an option at the bottom of the page to Add Your Own Skill. This will be an email to the Talent Cloud team to inquiry about adding a new skill. 

***Saving***
- [x] Once a level has been selected the user will **Save and Preview**. This will take the user to a new page highlighting the Key Task, the Skill, the definition and the level. 

# Link to wireframes:
[Skills wireframe](https://xd.adobe.com/view/b27b7bbc-5560-4e73-65aa-1c12787a2c94-c44a/?fullscreen&hints=off)

# Link to content:
[Skills content](https://docs.google.com/document/d/16Yqg5Q8Sruk1ujdaq8nkYMFXz2OReHqLf-8PSWczNzc/edit?usp=sharing)

**Comment by joshdrink** [comment]
Because I'm removing a lot of the aesthetic examples for comments' sake, here's a screenshot.

![talent test_en_builder-06 (1)](https://user-images.githubusercontent.com/6960386/60734665-a950f080-9f1e-11e9-9d68-3a2bd5abeac8.png)
