### ISSUE TITLE
Update partners list (in FAQ)

### ISSUE THREAD

**Issue by mattejackson** [GCTC-NTGC/TalentCloud#979]
# Description
Update list of partner departments on FAQ page

# Images
Place image attachments here.

# Changes
Enter the approved copy here:

https://docs.google.com/document/d/1ehPPnCrK5fidE68YjzpmiArKMoqPRtJSfocRAXKbOPY/edit#

| English  | French |
| ------- | ------- |
| Content | Content |

- [ ] Copy provided in English and French.

I still can't assign issues so I'll just tag you here, @joshdrink 

- [ ]

**Comment by gggrant** [comment]
Resolved by #1089
